<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Billing.Client</RootNamespace>
    <AssemblyName>Billing.Client</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Models236\Auth.Models236.csproj" />
    <ProjectReference Include="..\Scheduling.Api185\Scheduling.Api185.csproj" />
    <ProjectReference Include="..\Auth.Events\Auth.Events.csproj" />
    <ProjectReference Include="..\Integration.Events\Integration.Events.csproj" />
    <ProjectReference Include="..\Utilities.Core\Utilities.Core.csproj" />
    <ProjectReference Include="..\Utilities.Data415\Utilities.Data415.csproj" />
    <ProjectReference Include="..\Auth.Web\Auth.Web.csproj" />
    <ProjectReference Include="..\Import.Tests\Import.Tests.csproj" />
    <ProjectReference Include="..\Import.Service265\Import.Service265.csproj" />
    <ProjectReference Include="..\Reporting.Client422\Reporting.Client422.csproj" />
    <ProjectReference Include="..\Admin.Models\Admin.Models.csproj" />
    <ProjectReference Include="..\Import.Events493\Import.Events493.csproj" />
    <ProjectReference Include="..\DataAccess.Validators\DataAccess.Validators.csproj" />
    <ProjectReference Include="..\Billing.Data\Billing.Data.csproj" />
    <ProjectReference Include="..\Billing.Contracts44\Billing.Contracts44.csproj" />
    <ProjectReference Include="..\Export.Core168\Export.Core168.csproj" />
  </ItemGroup>
</Project>
