<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Portal.Contracts170</RootNamespace>
    <AssemblyName>Portal.Contracts170</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Service247\Admin.Service247.csproj" />
    <ProjectReference Include="..\Admin.Data117\Admin.Data117.csproj" />
    <ProjectReference Include="..\BatchJobs.Contracts\BatchJobs.Contracts.csproj" />
    <ProjectReference Include="..\DataAccess.Api307\DataAccess.Api307.csproj" />
    <ProjectReference Include="..\Security.Handlers\Security.Handlers.csproj" />
    <ProjectReference Include="..\Billing.Service302\Billing.Service302.csproj" />
    <ProjectReference Include="..\Imaging.Validators108\Imaging.Validators108.csproj" />
    <ProjectReference Include="..\Imaging.Models\Imaging.Models.csproj" />
    <ProjectReference Include="..\BatchJobs.Handlers\BatchJobs.Handlers.csproj" />
    <ProjectReference Include="..\BatchJobs.Data\BatchJobs.Data.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data453\GalaxyWorks.Data453.csproj" />
    <ProjectReference Include="..\Notifications.Validators\Notifications.Validators.csproj" />
    <ProjectReference Include="..\Export.Api49\Export.Api49.csproj" />
    <ProjectReference Include="..\Portal.Data\Portal.Data.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Events256\GalaxyWorks.Events256.csproj" />
    <ProjectReference Include="..\Portal.Mappers\Portal.Mappers.csproj" />
    <ProjectReference Include="..\Auth.Client\Auth.Client.csproj" />
  </ItemGroup>
</Project>
