<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Reporting.Tests67</RootNamespace>
    <AssemblyName>Reporting.Tests67</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Client249\Auth.Client249.csproj" />
    <ProjectReference Include="..\Imaging.Tests\Imaging.Tests.csproj" />
    <ProjectReference Include="..\Utilities.Contracts\Utilities.Contracts.csproj" />
    <ProjectReference Include="..\Workflow.Mappers\Workflow.Mappers.csproj" />
    <ProjectReference Include="..\Reporting.Events\Reporting.Events.csproj" />
    <ProjectReference Include="..\Admin.Tests10\Admin.Tests10.csproj" />
    <ProjectReference Include="..\Billing.Api\Billing.Api.csproj" />
    <ProjectReference Include="..\Auth.Api116\Auth.Api116.csproj" />
    <ProjectReference Include="..\Integration.Processors241\Integration.Processors241.csproj" />
    <ProjectReference Include="..\Reporting.Api\Reporting.Api.csproj" />
    <ProjectReference Include="..\Billing.Events\Billing.Events.csproj" />
    <ProjectReference Include="..\DataAccess.Models\DataAccess.Models.csproj" />
    <ProjectReference Include="..\Logging.Data\Logging.Data.csproj" />
    <ProjectReference Include="..\Billing.Service432\Billing.Service432.csproj" />
    <ProjectReference Include="..\Reporting.Client\Reporting.Client.csproj" />
    <ProjectReference Include="..\Portal.Data\Portal.Data.csproj" />
  </ItemGroup>
</Project>
