<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Notifications.Mappers110</RootNamespace>
    <AssemblyName>Notifications.Mappers110</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Core\Auth.Core.csproj" />
    <ProjectReference Include="..\Admin.Api\Admin.Api.csproj" />
    <ProjectReference Include="..\Admin.Handlers\Admin.Handlers.csproj" />
    <ProjectReference Include="..\Workflow.Events\Workflow.Events.csproj" />
    <ProjectReference Include="..\Export.Mappers237\Export.Mappers237.csproj" />
    <ProjectReference Include="..\Documents.Core357\Documents.Core357.csproj" />
    <ProjectReference Include="..\Imaging.Mappers275\Imaging.Mappers275.csproj" />
    <ProjectReference Include="..\Export.Web229\Export.Web229.csproj" />
    <ProjectReference Include="..\Billing.Handlers122\Billing.Handlers122.csproj" />
    <ProjectReference Include="..\Workflow.Service463\Workflow.Service463.csproj" />
    <ProjectReference Include="..\Security.Processors\Security.Processors.csproj" />
    <ProjectReference Include="..\Export.Shared\Export.Shared.csproj" />
    <ProjectReference Include="..\Admin.Web4\Admin.Web4.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Shared\GalaxyWorks.Shared.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Tests445\GalaxyWorks.Tests445.csproj" />
    <ProjectReference Include="..\DataAccess.Shared189\DataAccess.Shared189.csproj" />
    <ProjectReference Include="..\Security.Tests\Security.Tests.csproj" />
    <ProjectReference Include="..\Workflow.Service161\Workflow.Service161.csproj" />
  </ItemGroup>
</Project>
