<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>BatchJobs.Events435</RootNamespace>
    <AssemblyName>BatchJobs.Events435</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Shared14\Admin.Shared14.csproj" />
    <ProjectReference Include="..\Admin.Web46\Admin.Web46.csproj" />
    <ProjectReference Include="..\Portal.Mappers233\Portal.Mappers233.csproj" />
    <ProjectReference Include="..\Scheduling.Core480\Scheduling.Core480.csproj" />
    <ProjectReference Include="..\Documents.Tests106\Documents.Tests106.csproj" />
    <ProjectReference Include="..\Logging.Handlers141\Logging.Handlers141.csproj" />
    <ProjectReference Include="..\Billing.Mappers124\Billing.Mappers124.csproj" />
    <ProjectReference Include="..\Imaging.Models459\Imaging.Models459.csproj" />
    <ProjectReference Include="..\Billing.Web\Billing.Web.csproj" />
    <ProjectReference Include="..\Portal.Service489\Portal.Service489.csproj" />
    <ProjectReference Include="..\Admin.Shared310\Admin.Shared310.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Contracts485\GalaxyWorks.Contracts485.csproj" />
    <ProjectReference Include="..\Billing.Processors388\Billing.Processors388.csproj" />
    <ProjectReference Include="..\Scheduling.Api185\Scheduling.Api185.csproj" />
    <ProjectReference Include="..\BatchJobs.Client109\BatchJobs.Client109.csproj" />
    <ProjectReference Include="..\Notifications.Data348\Notifications.Data348.csproj" />
    <ProjectReference Include="..\Workflow.Web\Workflow.Web.csproj" />
  </ItemGroup>
</Project>
