<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Documents.Client58</RootNamespace>
    <AssemblyName>Documents.Client58</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Mappers28\Auth.Mappers28.csproj" />
    <ProjectReference Include="..\Auth.Api116\Auth.Api116.csproj" />
    <ProjectReference Include="..\Admin.Shared14\Admin.Shared14.csproj" />
    <ProjectReference Include="..\DataAccess.Service464\DataAccess.Service464.csproj" />
    <ProjectReference Include="..\DataAccess.Api454\DataAccess.Api454.csproj" />
    <ProjectReference Include="..\Portal.Mappers\Portal.Mappers.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Handlers\GalaxyWorks.Handlers.csproj" />
    <ProjectReference Include="..\Documents.Contracts\Documents.Contracts.csproj" />
    <ProjectReference Include="..\Billing.Mappers\Billing.Mappers.csproj" />
    <ProjectReference Include="..\Utilities.Events\Utilities.Events.csproj" />
    <ProjectReference Include="..\Export.Core386\Export.Core386.csproj" />
    <ProjectReference Include="..\Integration.Shared\Integration.Shared.csproj" />
    <ProjectReference Include="..\Common.Shared297\Common.Shared297.csproj" />
    <ProjectReference Include="..\Imaging.Core\Imaging.Core.csproj" />
    <ProjectReference Include="..\Security.Client137\Security.Client137.csproj" />
    <ProjectReference Include="..\Auth.Data\Auth.Data.csproj" />
    <ProjectReference Include="..\Imaging.Contracts89\Imaging.Contracts89.csproj" />
    <ProjectReference Include="..\Notifications.Shared396\Notifications.Shared396.csproj" />
  </ItemGroup>
</Project>
