<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Notifications.Data</RootNamespace>
    <AssemblyName>Notifications.Data</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Processors\Auth.Processors.csproj" />
    <ProjectReference Include="..\Auth.Handlers281\Auth.Handlers281.csproj" />
    <ProjectReference Include="..\Common.Client53\Common.Client53.csproj" />
    <ProjectReference Include="..\Documents.Web\Documents.Web.csproj" />
    <ProjectReference Include="..\DataAccess.Web\DataAccess.Web.csproj" />
    <ProjectReference Include="..\Portal.Mappers\Portal.Mappers.csproj" />
    <ProjectReference Include="..\Notifications.Data406\Notifications.Data406.csproj" />
    <ProjectReference Include="..\Workflow.Api\Workflow.Api.csproj" />
    <ProjectReference Include="..\Workflow.Web\Workflow.Web.csproj" />
    <ProjectReference Include="..\Export.Client13\Export.Client13.csproj" />
    <ProjectReference Include="..\Scheduling.Web19\Scheduling.Web19.csproj" />
    <ProjectReference Include="..\Documents.Data419\Documents.Data419.csproj" />
    <ProjectReference Include="..\Auth.Contracts395\Auth.Contracts395.csproj" />
    <ProjectReference Include="..\Security.Shared365\Security.Shared365.csproj" />
    <ProjectReference Include="..\Billing.Shared\Billing.Shared.csproj" />
    <ProjectReference Include="..\Security.Service\Security.Service.csproj" />
    <ProjectReference Include="..\Security.Data278\Security.Data278.csproj" />
  </ItemGroup>
</Project>
