<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Workflow.Validators</RootNamespace>
    <AssemblyName>Workflow.Validators</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Client\Auth.Client.csproj" />
    <ProjectReference Include="..\Auth.Models236\Auth.Models236.csproj" />
    <ProjectReference Include="..\Imaging.Core\Imaging.Core.csproj" />
    <ProjectReference Include="..\Import.Data\Import.Data.csproj" />
    <ProjectReference Include="..\Security.Data\Security.Data.csproj" />
    <ProjectReference Include="..\Workflow.Web377\Workflow.Web377.csproj" />
    <ProjectReference Include="..\Logging.Service160\Logging.Service160.csproj" />
    <ProjectReference Include="..\Documents.Processors\Documents.Processors.csproj" />
    <ProjectReference Include="..\Auth.Client249\Auth.Client249.csproj" />
    <ProjectReference Include="..\Utilities.Data\Utilities.Data.csproj" />
    <ProjectReference Include="..\Imaging.Models459\Imaging.Models459.csproj" />
    <ProjectReference Include="..\Notifications.Web90\Notifications.Web90.csproj" />
    <ProjectReference Include="..\Logging.Models436\Logging.Models436.csproj" />
    <ProjectReference Include="..\DataAccess.Contracts404\DataAccess.Contracts404.csproj" />
    <ProjectReference Include="..\Imaging.Client\Imaging.Client.csproj" />
    <ProjectReference Include="..\Scheduling.Processors337\Scheduling.Processors337.csproj" />
    <ProjectReference Include="..\Export.Processors468\Export.Processors468.csproj" />
  </ItemGroup>
</Project>
