<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
    <RootNamespace>Integration.Handlers244</RootNamespace>
    <AssemblyName>Integration.Handlers244</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Validators\Admin.Validators.csproj" />
    <ProjectReference Include="..\Logging.Web\Logging.Web.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Client366\GalaxyWorks.Client366.csproj" />
    <ProjectReference Include="..\Security.Validators418\Security.Validators418.csproj" />
    <ProjectReference Include="..\Integration.Service147\Integration.Service147.csproj" />
    <ProjectReference Include="..\Security.Contracts\Security.Contracts.csproj" />
    <ProjectReference Include="..\Common.Models\Common.Models.csproj" />
    <ProjectReference Include="..\Imaging.Service\Imaging.Service.csproj" />
    <ProjectReference Include="..\Auth.Client271\Auth.Client271.csproj" />
    <ProjectReference Include="..\Common.Client\Common.Client.csproj" />
    <ProjectReference Include="..\Portal.Mappers233\Portal.Mappers233.csproj" />
    <ProjectReference Include="..\Common.Data21\Common.Data21.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data153\GalaxyWorks.Data153.csproj" />
    <ProjectReference Include="..\Documents.Service\Documents.Service.csproj" />
    <ProjectReference Include="..\Workflow.Tests222\Workflow.Tests222.csproj" />
    <ProjectReference Include="..\Workflow.Contracts330\Workflow.Contracts330.csproj" />
  </ItemGroup>
</Project>
