<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>Imaging.Events424</RootNamespace>
    <AssemblyName>Imaging.Events424</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Api\Auth.Api.csproj" />
    <ProjectReference Include="..\Billing.Client491\Billing.Client491.csproj" />
    <ProjectReference Include="..\Admin.Validators\Admin.Validators.csproj" />
    <ProjectReference Include="..\Common.Shared297\Common.Shared297.csproj" />
    <ProjectReference Include="..\Security.Client349\Security.Client349.csproj" />
    <ProjectReference Include="..\Portal.Handlers\Portal.Handlers.csproj" />
    <ProjectReference Include="..\Portal.Api51\Portal.Api51.csproj" />
    <ProjectReference Include="..\Admin.Api255\Admin.Api255.csproj" />
    <ProjectReference Include="..\Billing.Handlers122\Billing.Handlers122.csproj" />
    <ProjectReference Include="..\Logging.Models\Logging.Models.csproj" />
    <ProjectReference Include="..\DataAccess.Events\DataAccess.Events.csproj" />
    <ProjectReference Include="..\Admin.Core121\Admin.Core121.csproj" />
    <ProjectReference Include="..\Documents.Shared427\Documents.Shared427.csproj" />
    <ProjectReference Include="..\Billing.Processors259\Billing.Processors259.csproj" />
    <ProjectReference Include="..\Logging.Handlers368\Logging.Handlers368.csproj" />
    <ProjectReference Include="..\Import.Models\Import.Models.csproj" />
  </ItemGroup>
</Project>
