<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Documents.Events</RootNamespace>
    <AssemblyName>Documents.Events</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Events78\Auth.Events78.csproj" />
    <ProjectReference Include="..\Auth.Core140\Auth.Core140.csproj" />
    <ProjectReference Include="..\Documents.Service471\Documents.Service471.csproj" />
    <ProjectReference Include="..\Documents.Tests171\Documents.Tests171.csproj" />
    <ProjectReference Include="..\Security.Events288\Security.Events288.csproj" />
    <ProjectReference Include="..\Scheduling.Shared39\Scheduling.Shared39.csproj" />
    <ProjectReference Include="..\Security.Events\Security.Events.csproj" />
    <ProjectReference Include="..\Logging.Tests\Logging.Tests.csproj" />
    <ProjectReference Include="..\Auth.Api143\Auth.Api143.csproj" />
    <ProjectReference Include="..\BatchJobs.Tests\BatchJobs.Tests.csproj" />
    <ProjectReference Include="..\Logging.Shared315\Logging.Shared315.csproj" />
    <ProjectReference Include="..\Common.Validators50\Common.Validators50.csproj" />
    <ProjectReference Include="..\Scheduling.Processors25\Scheduling.Processors25.csproj" />
    <ProjectReference Include="..\Common.Contracts\Common.Contracts.csproj" />
    <ProjectReference Include="..\Scheduling.Service\Scheduling.Service.csproj" />
    <ProjectReference Include="..\Security.Core274\Security.Core274.csproj" />
    <ProjectReference Include="..\Admin.Processors\Admin.Processors.csproj" />
  </ItemGroup>
</Project>
