<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Workflow.Tests75</RootNamespace>
    <AssemblyName>Workflow.Tests75</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Mappers28\Auth.Mappers28.csproj" />
    <ProjectReference Include="..\Auth.Core\Auth.Core.csproj" />
    <ProjectReference Include="..\Imaging.Client331\Imaging.Client331.csproj" />
    <ProjectReference Include="..\Documents.Api439\Documents.Api439.csproj" />
    <ProjectReference Include="..\Integration.Validators369\Integration.Validators369.csproj" />
    <ProjectReference Include="..\Utilities.Service\Utilities.Service.csproj" />
    <ProjectReference Include="..\Scheduling.Handlers63\Scheduling.Handlers63.csproj" />
    <ProjectReference Include="..\Export.Events\Export.Events.csproj" />
    <ProjectReference Include="..\Admin.Processors\Admin.Processors.csproj" />
    <ProjectReference Include="..\Security.Shared155\Security.Shared155.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Contracts485\GalaxyWorks.Contracts485.csproj" />
    <ProjectReference Include="..\Logging.Service\Logging.Service.csproj" />
    <ProjectReference Include="..\Security.Models284\Security.Models284.csproj" />
    <ProjectReference Include="..\BatchJobs.Contracts\BatchJobs.Contracts.csproj" />
    <ProjectReference Include="..\Scheduling.Models441\Scheduling.Models441.csproj" />
    <ProjectReference Include="..\Workflow.Models\Workflow.Models.csproj" />
    <ProjectReference Include="..\Export.Client\Export.Client.csproj" />
  </ItemGroup>
</Project>
