<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Utilities.Mappers197</RootNamespace>
    <AssemblyName>Utilities.Mappers197</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Processors35\Admin.Processors35.csproj" />
    <ProjectReference Include="..\Imaging.Models459\Imaging.Models459.csproj" />
    <ProjectReference Include="..\Admin.Core121\Admin.Core121.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data375\GalaxyWorks.Data375.csproj" />
    <ProjectReference Include="..\Scheduling.Models\Scheduling.Models.csproj" />
    <ProjectReference Include="..\Security.Core243\Security.Core243.csproj" />
    <ProjectReference Include="..\Documents.Handlers\Documents.Handlers.csproj" />
    <ProjectReference Include="..\Reporting.Processors326\Reporting.Processors326.csproj" />
    <ProjectReference Include="..\Export.Data\Export.Data.csproj" />
    <ProjectReference Include="..\Import.Web\Import.Web.csproj" />
    <ProjectReference Include="..\Reporting.Events317\Reporting.Events317.csproj" />
    <ProjectReference Include="..\Billing.Handlers\Billing.Handlers.csproj" />
    <ProjectReference Include="..\Admin.Models476\Admin.Models476.csproj" />
    <ProjectReference Include="..\Portal.Handlers26\Portal.Handlers26.csproj" />
    <ProjectReference Include="..\Imaging.Data\Imaging.Data.csproj" />
    <ProjectReference Include="..\Import.Mappers56\Import.Mappers56.csproj" />
  </ItemGroup>
</Project>
