<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Reporting.Events317</RootNamespace>
    <AssemblyName>Reporting.Events317</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Processors35\Admin.Processors35.csproj" />
    <ProjectReference Include="..\Admin.Web4\Admin.Web4.csproj" />
    <ProjectReference Include="..\Workflow.Data\Workflow.Data.csproj" />
    <ProjectReference Include="..\Workflow.Tests222\Workflow.Tests222.csproj" />
    <ProjectReference Include="..\Imaging.Mappers93\Imaging.Mappers93.csproj" />
    <ProjectReference Include="..\Workflow.Contracts434\Workflow.Contracts434.csproj" />
    <ProjectReference Include="..\Security.Processors\Security.Processors.csproj" />
    <ProjectReference Include="..\Logging.Models379\Logging.Models379.csproj" />
    <ProjectReference Include="..\Export.Processors104\Export.Processors104.csproj" />
    <ProjectReference Include="..\Notifications.Core\Notifications.Core.csproj" />
    <ProjectReference Include="..\Admin.Events235\Admin.Events235.csproj" />
    <ProjectReference Include="..\Portal.Shared\Portal.Shared.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Api390\GalaxyWorks.Api390.csproj" />
    <ProjectReference Include="..\Logging.Shared315\Logging.Shared315.csproj" />
    <ProjectReference Include="..\Scheduling.Models342\Scheduling.Models342.csproj" />
    <ProjectReference Include="..\Scheduling.Models260\Scheduling.Models260.csproj" />
    <ProjectReference Include="..\DataAccess.Shared189\DataAccess.Shared189.csproj" />
  </ItemGroup>
</Project>
