<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Integration.Contracts290</RootNamespace>
    <AssemblyName>Integration.Contracts290</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Data\Admin.Data.csproj" />
    <ProjectReference Include="..\Admin.Api255\Admin.Api255.csproj" />
    <ProjectReference Include="..\Admin.Validators336\Admin.Validators336.csproj" />
    <ProjectReference Include="..\DataAccess.Validators409\DataAccess.Validators409.csproj" />
    <ProjectReference Include="..\Auth.Client\Auth.Client.csproj" />
    <ProjectReference Include="..\Billing.Shared149\Billing.Shared149.csproj" />
    <ProjectReference Include="..\BatchJobs.Mappers\BatchJobs.Mappers.csproj" />
    <ProjectReference Include="..\Imaging.Data\Imaging.Data.csproj" />
    <ProjectReference Include="..\Auth.Models23\Auth.Models23.csproj" />
    <ProjectReference Include="..\Imaging.Models\Imaging.Models.csproj" />
    <ProjectReference Include="..\Logging.Core\Logging.Core.csproj" />
    <ProjectReference Include="..\Utilities.Data415\Utilities.Data415.csproj" />
    <ProjectReference Include="..\Imaging.Contracts473\Imaging.Contracts473.csproj" />
    <ProjectReference Include="..\Workflow.Service\Workflow.Service.csproj" />
    <ProjectReference Include="..\Utilities.Contracts228\Utilities.Contracts228.csproj" />
    <ProjectReference Include="..\Portal.Core\Portal.Core.csproj" />
    <ProjectReference Include="..\Imaging.Validators\Imaging.Validators.csproj" />
    <ProjectReference Include="..\Security.Tests\Security.Tests.csproj" />
  </ItemGroup>
</Project>
