<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Export.Data150</RootNamespace>
    <AssemblyName>Export.Data150</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Mappers208\Auth.Mappers208.csproj" />
    <ProjectReference Include="..\Auth.Contracts395\Auth.Contracts395.csproj" />
    <ProjectReference Include="..\Export.Processors79\Export.Processors79.csproj" />
    <ProjectReference Include="..\Imaging.Service\Imaging.Service.csproj" />
    <ProjectReference Include="..\Auth.Handlers209\Auth.Handlers209.csproj" />
    <ProjectReference Include="..\Billing.Shared149\Billing.Shared149.csproj" />
    <ProjectReference Include="..\Utilities.Handlers268\Utilities.Handlers268.csproj" />
    <ProjectReference Include="..\Reporting.Tests\Reporting.Tests.csproj" />
    <ProjectReference Include="..\DataAccess.Shared189\DataAccess.Shared189.csproj" />
    <ProjectReference Include="..\Portal.Processors52\Portal.Processors52.csproj" />
    <ProjectReference Include="..\Auth.Contracts402\Auth.Contracts402.csproj" />
    <ProjectReference Include="..\Admin.Service247\Admin.Service247.csproj" />
    <ProjectReference Include="..\Billing.Processors103\Billing.Processors103.csproj" />
    <ProjectReference Include="..\Utilities.Shared114\Utilities.Shared114.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Validators\GalaxyWorks.Validators.csproj" />
    <ProjectReference Include="..\BatchJobs.Models329\BatchJobs.Models329.csproj" />
    <ProjectReference Include="..\Billing.Mappers124\Billing.Mappers124.csproj" />
  </ItemGroup>
</Project>
