<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>DataAccess.Contracts203</RootNamespace>
    <AssemblyName>DataAccess.Contracts203</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Contracts402\Auth.Contracts402.csproj" />
    <ProjectReference Include="..\Auth.Api143\Auth.Api143.csproj" />
    <ProjectReference Include="..\Auth.Core\Auth.Core.csproj" />
    <ProjectReference Include="..\Security.Models136\Security.Models136.csproj" />
    <ProjectReference Include="..\Security.Validators\Security.Validators.csproj" />
    <ProjectReference Include="..\Common.Mappers\Common.Mappers.csproj" />
    <ProjectReference Include="..\Common.Core417\Common.Core417.csproj" />
    <ProjectReference Include="..\Scheduling.Handlers63\Scheduling.Handlers63.csproj" />
    <ProjectReference Include="..\Admin.Models476\Admin.Models476.csproj" />
    <ProjectReference Include="..\Import.Core\Import.Core.csproj" />
    <ProjectReference Include="..\Utilities.Contracts32\Utilities.Contracts32.csproj" />
    <ProjectReference Include="..\Scheduling.Client\Scheduling.Client.csproj" />
    <ProjectReference Include="..\Imaging.Events303\Imaging.Events303.csproj" />
    <ProjectReference Include="..\Documents.Api129\Documents.Api129.csproj" />
    <ProjectReference Include="..\Export.Web\Export.Web.csproj" />
    <ProjectReference Include="..\Documents.Tests458\Documents.Tests458.csproj" />
    <ProjectReference Include="..\Security.Shared448\Security.Shared448.csproj" />
  </ItemGroup>
</Project>
