<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Billing.Shared312</RootNamespace>
    <AssemblyName>Billing.Shared312</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Models236\Auth.Models236.csproj" />
    <ProjectReference Include="..\Admin.Mappers\Admin.Mappers.csproj" />
    <ProjectReference Include="..\Admin.Processors35\Admin.Processors35.csproj" />
    <ProjectReference Include="..\Utilities.Contracts228\Utilities.Contracts228.csproj" />
    <ProjectReference Include="..\Import.Data193\Import.Data193.csproj" />
    <ProjectReference Include="..\BatchJobs.Processors410\BatchJobs.Processors410.csproj" />
    <ProjectReference Include="..\Documents.Api129\Documents.Api129.csproj" />
    <ProjectReference Include="..\DataAccess.Handlers\DataAccess.Handlers.csproj" />
    <ProjectReference Include="..\Logging.Contracts74\Logging.Contracts74.csproj" />
    <ProjectReference Include="..\Utilities.Data415\Utilities.Data415.csproj" />
    <ProjectReference Include="..\Admin.Api\Admin.Api.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Handlers84\GalaxyWorks.Handlers84.csproj" />
    <ProjectReference Include="..\Common.Shared95\Common.Shared95.csproj" />
    <ProjectReference Include="..\Documents.Events\Documents.Events.csproj" />
    <ProjectReference Include="..\Admin.Web46\Admin.Web46.csproj" />
    <ProjectReference Include="..\Documents.Processors133\Documents.Processors133.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Client\GalaxyWorks.Client.csproj" />
    <ProjectReference Include="..\Portal.Events139\Portal.Events139.csproj" />
  </ItemGroup>
</Project>
