<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Logging.Core</RootNamespace>
    <AssemblyName>Logging.Core</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Service364\Admin.Service364.csproj" />
    <ProjectReference Include="..\Workflow.Events327\Workflow.Events327.csproj" />
    <ProjectReference Include="..\Common.Data\Common.Data.csproj" />
    <ProjectReference Include="..\Reporting.Client146\Reporting.Client146.csproj" />
    <ProjectReference Include="..\Portal.Events139\Portal.Events139.csproj" />
    <ProjectReference Include="..\Import.Service496\Import.Service496.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Shared\GalaxyWorks.Shared.csproj" />
    <ProjectReference Include="..\BatchJobs.Core\BatchJobs.Core.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Validators\GalaxyWorks.Validators.csproj" />
    <ProjectReference Include="..\Reporting.Web345\Reporting.Web345.csproj" />
    <ProjectReference Include="..\Auth.Core2\Auth.Core2.csproj" />
    <ProjectReference Include="..\Common.Contracts279\Common.Contracts279.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Events77\GalaxyWorks.Events77.csproj" />
    <ProjectReference Include="..\Integration.Tests86\Integration.Tests86.csproj" />
    <ProjectReference Include="..\Utilities.Contracts228\Utilities.Contracts228.csproj" />
    <ProjectReference Include="..\Notifications.Web90\Notifications.Web90.csproj" />
  </ItemGroup>
</Project>
