<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Scheduling.Service</RootNamespace>
    <AssemblyName>Scheduling.Service</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Processors35\Admin.Processors35.csproj" />
    <ProjectReference Include="..\Documents.Processors\Documents.Processors.csproj" />
    <ProjectReference Include="..\Notifications.Shared396\Notifications.Shared396.csproj" />
    <ProjectReference Include="..\Export.Service\Export.Service.csproj" />
    <ProjectReference Include="..\DataAccess.Contracts404\DataAccess.Contracts404.csproj" />
    <ProjectReference Include="..\DataAccess.Shared\DataAccess.Shared.csproj" />
    <ProjectReference Include="..\Portal.Tests173\Portal.Tests173.csproj" />
    <ProjectReference Include="..\BatchJobs.Handlers\BatchJobs.Handlers.csproj" />
    <ProjectReference Include="..\Common.Validators\Common.Validators.csproj" />
    <ProjectReference Include="..\DataAccess.Tests286\DataAccess.Tests286.csproj" />
    <ProjectReference Include="..\Scheduling.Models342\Scheduling.Models342.csproj" />
    <ProjectReference Include="..\Common.Events\Common.Events.csproj" />
    <ProjectReference Include="..\Imaging.Client261\Imaging.Client261.csproj" />
    <ProjectReference Include="..\Common.Models\Common.Models.csproj" />
    <ProjectReference Include="..\Notifications.Events42\Notifications.Events42.csproj" />
    <ProjectReference Include="..\Imaging.Mappers93\Imaging.Mappers93.csproj" />
  </ItemGroup>
</Project>
