<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Integration.Api</RootNamespace>
    <AssemblyName>Integration.Api</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Client346\Admin.Client346.csproj" />
    <ProjectReference Include="..\Auth.Api143\Auth.Api143.csproj" />
    <ProjectReference Include="..\Auth.Processors\Auth.Processors.csproj" />
    <ProjectReference Include="..\Security.Client353\Security.Client353.csproj" />
    <ProjectReference Include="..\Workflow.Service\Workflow.Service.csproj" />
    <ProjectReference Include="..\Imaging.Shared\Imaging.Shared.csproj" />
    <ProjectReference Include="..\Portal.Core8\Portal.Core8.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Shared\GalaxyWorks.Shared.csproj" />
    <ProjectReference Include="..\Integration.Service\Integration.Service.csproj" />
    <ProjectReference Include="..\Documents.Service471\Documents.Service471.csproj" />
    <ProjectReference Include="..\Import.Client64\Import.Client64.csproj" />
    <ProjectReference Include="..\Security.Client137\Security.Client137.csproj" />
    <ProjectReference Include="..\Logging.Client405\Logging.Client405.csproj" />
    <ProjectReference Include="..\Admin.Mappers324\Admin.Mappers324.csproj" />
    <ProjectReference Include="..\Imaging.Validators108\Imaging.Validators108.csproj" />
    <ProjectReference Include="..\Integration.Handlers\Integration.Handlers.csproj" />
    <ProjectReference Include="..\Security.Handlers460\Security.Handlers460.csproj" />
    <ProjectReference Include="..\Security.Mappers\Security.Mappers.csproj" />
  </ItemGroup>
</Project>
