<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Security.Client137</RootNamespace>
    <AssemblyName>Security.Client137</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Events\Admin.Events.csproj" />
    <ProjectReference Include="..\Import.Client65\Import.Client65.csproj" />
    <ProjectReference Include="..\Admin.Data117\Admin.Data117.csproj" />
    <ProjectReference Include="..\Export.Core168\Export.Core168.csproj" />
    <ProjectReference Include="..\Portal.Validators\Portal.Validators.csproj" />
    <ProjectReference Include="..\Scheduling.Tests214\Scheduling.Tests214.csproj" />
    <ProjectReference Include="..\Utilities.Api\Utilities.Api.csproj" />
    <ProjectReference Include="..\Reporting.Client146\Reporting.Client146.csproj" />
    <ProjectReference Include="..\Scheduling.Web221\Scheduling.Web221.csproj" />
    <ProjectReference Include="..\Scheduling.Tests85\Scheduling.Tests85.csproj" />
    <ProjectReference Include="..\Auth.Validators\Auth.Validators.csproj" />
    <ProjectReference Include="..\Workflow.Tests27\Workflow.Tests27.csproj" />
    <ProjectReference Include="..\Admin.Processors35\Admin.Processors35.csproj" />
    <ProjectReference Include="..\Auth.Api143\Auth.Api143.csproj" />
    <ProjectReference Include="..\Export.Shared332\Export.Shared332.csproj" />
    <ProjectReference Include="..\Scheduling.Tests444\Scheduling.Tests444.csproj" />
  </ItemGroup>
</Project>
