<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Import.Client7</RootNamespace>
    <AssemblyName>Import.Client7</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Validators431\Admin.Validators431.csproj" />
    <ProjectReference Include="..\Admin.Api\Admin.Api.csproj" />
    <ProjectReference Include="..\DataAccess.Contracts404\DataAccess.Contracts404.csproj" />
    <ProjectReference Include="..\Workflow.Models\Workflow.Models.csproj" />
    <ProjectReference Include="..\DataAccess.Models\DataAccess.Models.csproj" />
    <ProjectReference Include="..\Admin.Client177\Admin.Client177.csproj" />
    <ProjectReference Include="..\Auth.Events78\Auth.Events78.csproj" />
    <ProjectReference Include="..\Admin.Models\Admin.Models.csproj" />
    <ProjectReference Include="..\Admin.Handlers61\Admin.Handlers61.csproj" />
    <ProjectReference Include="..\Portal.Contracts\Portal.Contracts.csproj" />
    <ProjectReference Include="..\Notifications.Handlers470\Notifications.Handlers470.csproj" />
    <ProjectReference Include="..\Imaging.Mappers275\Imaging.Mappers275.csproj" />
    <ProjectReference Include="..\Documents.Data492\Documents.Data492.csproj" />
    <ProjectReference Include="..\Export.Handlers\Export.Handlers.csproj" />
    <ProjectReference Include="..\Workflow.Api148\Workflow.Api148.csproj" />
    <ProjectReference Include="..\Utilities.Contracts\Utilities.Contracts.csproj" />
    <ProjectReference Include="..\Import.Contracts180\Import.Contracts180.csproj" />
  </ItemGroup>
</Project>
