<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Documents.Contracts</RootNamespace>
    <AssemblyName>Documents.Contracts</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Service247\Admin.Service247.csproj" />
    <ProjectReference Include="..\Documents.Data419\Documents.Data419.csproj" />
    <ProjectReference Include="..\Documents.Service471\Documents.Service471.csproj" />
    <ProjectReference Include="..\DataAccess.Api454\DataAccess.Api454.csproj" />
    <ProjectReference Include="..\Admin.Tests\Admin.Tests.csproj" />
    <ProjectReference Include="..\Security.Models284\Security.Models284.csproj" />
    <ProjectReference Include="..\Documents.Client\Documents.Client.csproj" />
    <ProjectReference Include="..\Auth.Processors411\Auth.Processors411.csproj" />
    <ProjectReference Include="..\Auth.Service\Auth.Service.csproj" />
    <ProjectReference Include="..\Security.Validators428\Security.Validators428.csproj" />
    <ProjectReference Include="..\Imaging.Contracts473\Imaging.Contracts473.csproj" />
    <ProjectReference Include="..\Security.Client137\Security.Client137.csproj" />
    <ProjectReference Include="..\Notifications.Service\Notifications.Service.csproj" />
    <ProjectReference Include="..\Logging.Tests\Logging.Tests.csproj" />
    <ProjectReference Include="..\Import.Contracts296\Import.Contracts296.csproj" />
    <ProjectReference Include="..\Admin.Service339\Admin.Service339.csproj" />
  </ItemGroup>
</Project>
