<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Notifications.Data348</RootNamespace>
    <AssemblyName>Notifications.Data348</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Data\Admin.Data.csproj" />
    <ProjectReference Include="..\Auth.Core2\Auth.Core2.csproj" />
    <ProjectReference Include="..\Auth.Handlers467\Auth.Handlers467.csproj" />
    <ProjectReference Include="..\BatchJobs.Tests\BatchJobs.Tests.csproj" />
    <ProjectReference Include="..\Import.Handlers354\Import.Handlers354.csproj" />
    <ProjectReference Include="..\Logging.Api316\Logging.Api316.csproj" />
    <ProjectReference Include="..\Logging.Web\Logging.Web.csproj" />
    <ProjectReference Include="..\Admin.Contracts\Admin.Contracts.csproj" />
    <ProjectReference Include="..\Imaging.Tests\Imaging.Tests.csproj" />
    <ProjectReference Include="..\Scheduling.Mappers\Scheduling.Mappers.csproj" />
    <ProjectReference Include="..\Imaging.Mappers93\Imaging.Mappers93.csproj" />
    <ProjectReference Include="..\Scheduling.Processors\Scheduling.Processors.csproj" />
    <ProjectReference Include="..\Documents.Web\Documents.Web.csproj" />
    <ProjectReference Include="..\Security.Api134\Security.Api134.csproj" />
    <ProjectReference Include="..\DataAccess.Shared189\DataAccess.Shared189.csproj" />
    <ProjectReference Include="..\Security.Events\Security.Events.csproj" />
    <ProjectReference Include="..\BatchJobs.Validators\BatchJobs.Validators.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Mappers\GalaxyWorks.Mappers.csproj" />
  </ItemGroup>
</Project>
