<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Export.Web</RootNamespace>
    <AssemblyName>Export.Web</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Handlers447\Admin.Handlers447.csproj" />
    <ProjectReference Include="..\Admin.Api\Admin.Api.csproj" />
    <ProjectReference Include="..\Admin.Web4\Admin.Web4.csproj" />
    <ProjectReference Include="..\Imaging.Validators\Imaging.Validators.csproj" />
    <ProjectReference Include="..\Common.Mappers\Common.Mappers.csproj" />
    <ProjectReference Include="..\Portal.Service378\Portal.Service378.csproj" />
    <ProjectReference Include="..\Logging.Web\Logging.Web.csproj" />
    <ProjectReference Include="..\Logging.Shared315\Logging.Shared315.csproj" />
    <ProjectReference Include="..\Integration.Events\Integration.Events.csproj" />
    <ProjectReference Include="..\Scheduling.Models\Scheduling.Models.csproj" />
    <ProjectReference Include="..\Notifications.Models466\Notifications.Models466.csproj" />
    <ProjectReference Include="..\Logging.Data29\Logging.Data29.csproj" />
    <ProjectReference Include="..\Documents.Data\Documents.Data.csproj" />
    <ProjectReference Include="..\Export.Validators\Export.Validators.csproj" />
    <ProjectReference Include="..\Notifications.Mappers110\Notifications.Mappers110.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Core\GalaxyWorks.Core.csproj" />
    <ProjectReference Include="..\Workflow.Web\Workflow.Web.csproj" />
  </ItemGroup>
</Project>
