<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Workflow.Validators201</RootNamespace>
    <AssemblyName>Workflow.Validators201</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Shared310\Admin.Shared310.csproj" />
    <ProjectReference Include="..\Auth.Events78\Auth.Events78.csproj" />
    <ProjectReference Include="..\Admin.Processors\Admin.Processors.csproj" />
    <ProjectReference Include="..\Export.Models461\Export.Models461.csproj" />
    <ProjectReference Include="..\Portal.Mappers233\Portal.Mappers233.csproj" />
    <ProjectReference Include="..\Utilities.Web40\Utilities.Web40.csproj" />
    <ProjectReference Include="..\DataAccess.Validators409\DataAccess.Validators409.csproj" />
    <ProjectReference Include="..\Scheduling.Web264\Scheduling.Web264.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Shared437\GalaxyWorks.Shared437.csproj" />
    <ProjectReference Include="..\Scheduling.Tests76\Scheduling.Tests76.csproj" />
    <ProjectReference Include="..\Portal.Client\Portal.Client.csproj" />
    <ProjectReference Include="..\Import.Shared\Import.Shared.csproj" />
    <ProjectReference Include="..\Scheduling.Events\Scheduling.Events.csproj" />
    <ProjectReference Include="..\Common.Client\Common.Client.csproj" />
    <ProjectReference Include="..\Import.Mappers\Import.Mappers.csproj" />
    <ProjectReference Include="..\Logging.Service160\Logging.Service160.csproj" />
    <ProjectReference Include="..\DataAccess.Mappers\DataAccess.Mappers.csproj" />
    <ProjectReference Include="..\Integration.Api\Integration.Api.csproj" />
  </ItemGroup>
</Project>
