<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Scheduling.Events128</RootNamespace>
    <AssemblyName>Scheduling.Events128</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Service247\Admin.Service247.csproj" />
    <ProjectReference Include="..\Admin.Shared310\Admin.Shared310.csproj" />
    <ProjectReference Include="..\Auth.Processors319\Auth.Processors319.csproj" />
    <ProjectReference Include="..\Reporting.Client146\Reporting.Client146.csproj" />
    <ProjectReference Include="..\Portal.Api352\Portal.Api352.csproj" />
    <ProjectReference Include="..\Admin.Validators431\Admin.Validators431.csproj" />
    <ProjectReference Include="..\Auth.Models236\Auth.Models236.csproj" />
    <ProjectReference Include="..\DataAccess.Core\DataAccess.Core.csproj" />
    <ProjectReference Include="..\Utilities.Mappers197\Utilities.Mappers197.csproj" />
    <ProjectReference Include="..\Integration.Contracts290\Integration.Contracts290.csproj" />
    <ProjectReference Include="..\Import.Service\Import.Service.csproj" />
    <ProjectReference Include="..\Portal.Data216\Portal.Data216.csproj" />
    <ProjectReference Include="..\DataAccess.Shared\DataAccess.Shared.csproj" />
    <ProjectReference Include="..\Import.Processors412\Import.Processors412.csproj" />
    <ProjectReference Include="..\Logging.Mappers\Logging.Mappers.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Web\GalaxyWorks.Web.csproj" />
    <ProjectReference Include="..\Scheduling.Api\Scheduling.Api.csproj" />
    <ProjectReference Include="..\Utilities.Web40\Utilities.Web40.csproj" />
  </ItemGroup>
</Project>
