<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Billing.Handlers122</RootNamespace>
    <AssemblyName>Billing.Handlers122</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Mappers206\Auth.Mappers206.csproj" />
    <ProjectReference Include="..\Admin.Tests10\Admin.Tests10.csproj" />
    <ProjectReference Include="..\Admin.Events\Admin.Events.csproj" />
    <ProjectReference Include="..\Import.Events493\Import.Events493.csproj" />
    <ProjectReference Include="..\Imaging.Shared115\Imaging.Shared115.csproj" />
    <ProjectReference Include="..\BatchJobs.Handlers\BatchJobs.Handlers.csproj" />
    <ProjectReference Include="..\Billing.Tests\Billing.Tests.csproj" />
    <ProjectReference Include="..\DataAccess.Models\DataAccess.Models.csproj" />
    <ProjectReference Include="..\Logging.Handlers368\Logging.Handlers368.csproj" />
    <ProjectReference Include="..\Export.Events\Export.Events.csproj" />
    <ProjectReference Include="..\Auth.Client271\Auth.Client271.csproj" />
    <ProjectReference Include="..\Logging.Events\Logging.Events.csproj" />
    <ProjectReference Include="..\Portal.Shared\Portal.Shared.csproj" />
    <ProjectReference Include="..\Documents.Tests171\Documents.Tests171.csproj" />
    <ProjectReference Include="..\Documents.Events\Documents.Events.csproj" />
    <ProjectReference Include="..\Documents.Api129\Documents.Api129.csproj" />
    <ProjectReference Include="..\Common.Handlers\Common.Handlers.csproj" />
    <ProjectReference Include="..\Workflow.Processors\Workflow.Processors.csproj" />
  </ItemGroup>
</Project>
