<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Utilities.Api234</RootNamespace>
    <AssemblyName>Utilities.Api234</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Events306\Admin.Events306.csproj" />
    <ProjectReference Include="..\Auth.Mappers\Auth.Mappers.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Tests445\GalaxyWorks.Tests445.csproj" />
    <ProjectReference Include="..\Reporting.Api\Reporting.Api.csproj" />
    <ProjectReference Include="..\Billing.Web\Billing.Web.csproj" />
    <ProjectReference Include="..\Auth.Models23\Auth.Models23.csproj" />
    <ProjectReference Include="..\Billing.Mappers225\Billing.Mappers225.csproj" />
    <ProjectReference Include="..\Imaging.Models\Imaging.Models.csproj" />
    <ProjectReference Include="..\Scheduling.Mappers\Scheduling.Mappers.csproj" />
    <ProjectReference Include="..\Notifications.Handlers\Notifications.Handlers.csproj" />
    <ProjectReference Include="..\Utilities.Data415\Utilities.Data415.csproj" />
    <ProjectReference Include="..\Export.Data\Export.Data.csproj" />
    <ProjectReference Include="..\Scheduling.Processors397\Scheduling.Processors397.csproj" />
    <ProjectReference Include="..\Notifications.Data348\Notifications.Data348.csproj" />
    <ProjectReference Include="..\Imaging.Core\Imaging.Core.csproj" />
    <ProjectReference Include="..\Import.Handlers167\Import.Handlers167.csproj" />
    <ProjectReference Include="..\DataAccess.Service\DataAccess.Service.csproj" />
  </ItemGroup>
</Project>
