<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Common.Api186</RootNamespace>
    <AssemblyName>Common.Api186</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Models236\Auth.Models236.csproj" />
    <ProjectReference Include="..\Scheduling.Tests76\Scheduling.Tests76.csproj" />
    <ProjectReference Include="..\Scheduling.Shared\Scheduling.Shared.csproj" />
    <ProjectReference Include="..\Portal.Shared\Portal.Shared.csproj" />
    <ProjectReference Include="..\Export.Processors361\Export.Processors361.csproj" />
    <ProjectReference Include="..\Billing.Mappers\Billing.Mappers.csproj" />
    <ProjectReference Include="..\Export.Processors\Export.Processors.csproj" />
    <ProjectReference Include="..\Notifications.Service475\Notifications.Service475.csproj" />
    <ProjectReference Include="..\Portal.Validators250\Portal.Validators250.csproj" />
    <ProjectReference Include="..\Documents.Events\Documents.Events.csproj" />
    <ProjectReference Include="..\Common.Mappers343\Common.Mappers343.csproj" />
    <ProjectReference Include="..\Auth.Api116\Auth.Api116.csproj" />
    <ProjectReference Include="..\Export.Mappers\Export.Mappers.csproj" />
    <ProjectReference Include="..\Imaging.Mappers275\Imaging.Mappers275.csproj" />
    <ProjectReference Include="..\Imaging.Mappers\Imaging.Mappers.csproj" />
    <ProjectReference Include="..\Security.Handlers\Security.Handlers.csproj" />
  </ItemGroup>
</Project>
