<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
    <RootNamespace>Import.Web</RootNamespace>
    <AssemblyName>Import.Web</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Events78\Auth.Events78.csproj" />
    <ProjectReference Include="..\Admin.Client346\Admin.Client346.csproj" />
    <ProjectReference Include="..\Admin.Handlers\Admin.Handlers.csproj" />
    <ProjectReference Include="..\Common.Data\Common.Data.csproj" />
    <ProjectReference Include="..\Scheduling.Shared39\Scheduling.Shared39.csproj" />
    <ProjectReference Include="..\Documents.Processors300\Documents.Processors300.csproj" />
    <ProjectReference Include="..\Security.Client353\Security.Client353.csproj" />
    <ProjectReference Include="..\Export.Mappers\Export.Mappers.csproj" />
    <ProjectReference Include="..\Common.Validators50\Common.Validators50.csproj" />
    <ProjectReference Include="..\Workflow.Shared298\Workflow.Shared298.csproj" />
    <ProjectReference Include="..\Billing.Mappers\Billing.Mappers.csproj" />
    <ProjectReference Include="..\DataAccess.Events\DataAccess.Events.csproj" />
    <ProjectReference Include="..\Import.Api272\Import.Api272.csproj" />
    <ProjectReference Include="..\Common.Service258\Common.Service258.csproj" />
    <ProjectReference Include="..\Common.Client53\Common.Client53.csproj" />
    <ProjectReference Include="..\Billing.Client182\Billing.Client182.csproj" />
    <ProjectReference Include="..\Imaging.Web\Imaging.Web.csproj" />
  </ItemGroup>
</Project>
