<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
    <RootNamespace>Utilities.Api</RootNamespace>
    <AssemblyName>Utilities.Api</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Data135\Auth.Data135.csproj" />
    <ProjectReference Include="..\Auth.Mappers178\Auth.Mappers178.csproj" />
    <ProjectReference Include="..\Security.Events\Security.Events.csproj" />
    <ProjectReference Include="..\Integration.Data175\Integration.Data175.csproj" />
    <ProjectReference Include="..\Admin.Models476\Admin.Models476.csproj" />
    <ProjectReference Include="..\Imaging.Shared338\Imaging.Shared338.csproj" />
    <ProjectReference Include="..\Scheduling.Data\Scheduling.Data.csproj" />
    <ProjectReference Include="..\Logging.Core\Logging.Core.csproj" />
    <ProjectReference Include="..\Scheduling.Events128\Scheduling.Events128.csproj" />
    <ProjectReference Include="..\Import.Service291\Import.Service291.csproj" />
    <ProjectReference Include="..\DataAccess.Client113\DataAccess.Client113.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data453\GalaxyWorks.Data453.csproj" />
    <ProjectReference Include="..\Documents.Data419\Documents.Data419.csproj" />
    <ProjectReference Include="..\Billing.Mappers\Billing.Mappers.csproj" />
    <ProjectReference Include="..\Billing.Tests\Billing.Tests.csproj" />
    <ProjectReference Include="..\DataAccess.Api294\DataAccess.Api294.csproj" />
    <ProjectReference Include="..\Security.Handlers460\Security.Handlers460.csproj" />
  </ItemGroup>
</Project>
