<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Scheduling.Processors80</RootNamespace>
    <AssemblyName>Scheduling.Processors80</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Models199\Admin.Models199.csproj" />
    <ProjectReference Include="..\Security.Api\Security.Api.csproj" />
    <ProjectReference Include="..\Common.Events367\Common.Events367.csproj" />
    <ProjectReference Include="..\Auth.Api143\Auth.Api143.csproj" />
    <ProjectReference Include="..\Imaging.Events303\Imaging.Events303.csproj" />
    <ProjectReference Include="..\Imaging.Mappers275\Imaging.Mappers275.csproj" />
    <ProjectReference Include="..\Billing.Models\Billing.Models.csproj" />
    <ProjectReference Include="..\Scheduling.Tests444\Scheduling.Tests444.csproj" />
    <ProjectReference Include="..\Admin.Service339\Admin.Service339.csproj" />
    <ProjectReference Include="..\BatchJobs.Core\BatchJobs.Core.csproj" />
    <ProjectReference Include="..\Scheduling.Web60\Scheduling.Web60.csproj" />
    <ProjectReference Include="..\Utilities.Tests\Utilities.Tests.csproj" />
    <ProjectReference Include="..\Reporting.Tests226\Reporting.Tests226.csproj" />
    <ProjectReference Include="..\Workflow.Events327\Workflow.Events327.csproj" />
    <ProjectReference Include="..\Auth.Api116\Auth.Api116.csproj" />
    <ProjectReference Include="..\Auth.Processors319\Auth.Processors319.csproj" />
  </ItemGroup>
</Project>
