<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Export.Events</RootNamespace>
    <AssemblyName>Export.Events</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Api143\Auth.Api143.csproj" />
    <ProjectReference Include="..\Admin.Service247\Admin.Service247.csproj" />
    <ProjectReference Include="..\Auth.Web\Auth.Web.csproj" />
    <ProjectReference Include="..\Auth.Models236\Auth.Models236.csproj" />
    <ProjectReference Include="..\DataAccess.Shared189\DataAccess.Shared189.csproj" />
    <ProjectReference Include="..\Portal.Api\Portal.Api.csproj" />
    <ProjectReference Include="..\Portal.Contracts181\Portal.Contracts181.csproj" />
    <ProjectReference Include="..\Imaging.Events303\Imaging.Events303.csproj" />
    <ProjectReference Include="..\Auth.Client249\Auth.Client249.csproj" />
    <ProjectReference Include="..\DataAccess.Client113\DataAccess.Client113.csproj" />
    <ProjectReference Include="..\Export.Models461\Export.Models461.csproj" />
    <ProjectReference Include="..\Common.Processors142\Common.Processors142.csproj" />
    <ProjectReference Include="..\Common.Tests350\Common.Tests350.csproj" />
    <ProjectReference Include="..\Import.Data100\Import.Data100.csproj" />
    <ProjectReference Include="..\Common.Api186\Common.Api186.csproj" />
    <ProjectReference Include="..\Security.Contracts\Security.Contracts.csproj" />
    <ProjectReference Include="..\Utilities.Web398\Utilities.Web398.csproj" />
  </ItemGroup>
</Project>
