<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Scheduling.Tests444</RootNamespace>
    <AssemblyName>Scheduling.Tests444</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Api\Auth.Api.csproj" />
    <ProjectReference Include="..\Admin.Mappers\Admin.Mappers.csproj" />
    <ProjectReference Include="..\Admin.Tests\Admin.Tests.csproj" />
    <ProjectReference Include="..\Integration.Events\Integration.Events.csproj" />
    <ProjectReference Include="..\Documents.Web\Documents.Web.csproj" />
    <ProjectReference Include="..\Workflow.Service463\Workflow.Service463.csproj" />
    <ProjectReference Include="..\Import.Api272\Import.Api272.csproj" />
    <ProjectReference Include="..\Integration.Api\Integration.Api.csproj" />
    <ProjectReference Include="..\Utilities.Data415\Utilities.Data415.csproj" />
    <ProjectReference Include="..\Export.Web229\Export.Web229.csproj" />
    <ProjectReference Include="..\Security.Client137\Security.Client137.csproj" />
    <ProjectReference Include="..\Documents.Api\Documents.Api.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Events77\GalaxyWorks.Events77.csproj" />
    <ProjectReference Include="..\DataAccess.Core\DataAccess.Core.csproj" />
    <ProjectReference Include="..\Portal.Mappers\Portal.Mappers.csproj" />
    <ProjectReference Include="..\Portal.Validators69\Portal.Validators69.csproj" />
    <ProjectReference Include="..\Security.Tests\Security.Tests.csproj" />
    <ProjectReference Include="..\Security.Models420\Security.Models420.csproj" />
  </ItemGroup>
</Project>
