<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Reporting.Validators</RootNamespace>
    <AssemblyName>Reporting.Validators</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Api143\Auth.Api143.csproj" />
    <ProjectReference Include="..\Portal.Core\Portal.Core.csproj" />
    <ProjectReference Include="..\Reporting.Processors326\Reporting.Processors326.csproj" />
    <ProjectReference Include="..\DataAccess.Validators409\DataAccess.Validators409.csproj" />
    <ProjectReference Include="..\DataAccess.Shared189\DataAccess.Shared189.csproj" />
    <ProjectReference Include="..\Export.Api\Export.Api.csproj" />
    <ProjectReference Include="..\Security.Validators428\Security.Validators428.csproj" />
    <ProjectReference Include="..\Notifications.Core166\Notifications.Core166.csproj" />
    <ProjectReference Include="..\Scheduling.Web264\Scheduling.Web264.csproj" />
    <ProjectReference Include="..\Integration.Api469\Integration.Api469.csproj" />
    <ProjectReference Include="..\Scheduling.Web221\Scheduling.Web221.csproj" />
    <ProjectReference Include="..\Export.Processors449\Export.Processors449.csproj" />
    <ProjectReference Include="..\Reporting.Processors495\Reporting.Processors495.csproj" />
    <ProjectReference Include="..\Integration.Processors241\Integration.Processors241.csproj" />
    <ProjectReference Include="..\Auth.Api\Auth.Api.csproj" />
    <ProjectReference Include="..\Documents.Contracts\Documents.Contracts.csproj" />
  </ItemGroup>
</Project>
