<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Billing.Models</RootNamespace>
    <AssemblyName>Billing.Models</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Handlers467\Auth.Handlers467.csproj" />
    <ProjectReference Include="..\Admin.Handlers447\Admin.Handlers447.csproj" />
    <ProjectReference Include="..\Common.Client269\Common.Client269.csproj" />
    <ProjectReference Include="..\Workflow.Handlers421\Workflow.Handlers421.csproj" />
    <ProjectReference Include="..\Billing.Client\Billing.Client.csproj" />
    <ProjectReference Include="..\Integration.Processors\Integration.Processors.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Validators\GalaxyWorks.Validators.csproj" />
    <ProjectReference Include="..\Notifications.Mappers55\Notifications.Mappers55.csproj" />
    <ProjectReference Include="..\Notifications.Data446\Notifications.Data446.csproj" />
    <ProjectReference Include="..\Utilities.Tests\Utilities.Tests.csproj" />
    <ProjectReference Include="..\Documents.Api\Documents.Api.csproj" />
    <ProjectReference Include="..\Portal.Service489\Portal.Service489.csproj" />
    <ProjectReference Include="..\Integration.Data\Integration.Data.csproj" />
    <ProjectReference Include="..\Notifications.Contracts\Notifications.Contracts.csproj" />
    <ProjectReference Include="..\Imaging.Handlers\Imaging.Handlers.csproj" />
    <ProjectReference Include="..\Integration.Contracts290\Integration.Contracts290.csproj" />
    <ProjectReference Include="..\Admin.Data408\Admin.Data408.csproj" />
  </ItemGroup>
</Project>
