<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Portal.Events139</RootNamespace>
    <AssemblyName>Portal.Events139</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Client177\Admin.Client177.csproj" />
    <ProjectReference Include="..\Admin.Handlers450\Admin.Handlers450.csproj" />
    <ProjectReference Include="..\Admin.Web46\Admin.Web46.csproj" />
    <ProjectReference Include="..\Billing.Mappers124\Billing.Mappers124.csproj" />
    <ProjectReference Include="..\Admin.Processors\Admin.Processors.csproj" />
    <ProjectReference Include="..\Reporting.Shared\Reporting.Shared.csproj" />
    <ProjectReference Include="..\Documents.Shared427\Documents.Shared427.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Handlers\GalaxyWorks.Handlers.csproj" />
    <ProjectReference Include="..\Common.Api213\Common.Api213.csproj" />
    <ProjectReference Include="..\Security.Models420\Security.Models420.csproj" />
    <ProjectReference Include="..\DataAccess.Api341\DataAccess.Api341.csproj" />
    <ProjectReference Include="..\Workflow.Shared298\Workflow.Shared298.csproj" />
    <ProjectReference Include="..\Integration.Service477\Integration.Service477.csproj" />
    <ProjectReference Include="..\Workflow.Handlers421\Workflow.Handlers421.csproj" />
    <ProjectReference Include="..\Imaging.Events303\Imaging.Events303.csproj" />
    <ProjectReference Include="..\Portal.Service378\Portal.Service378.csproj" />
    <ProjectReference Include="..\Integration.Validators\Integration.Validators.csproj" />
    <ProjectReference Include="..\Security.Shared155\Security.Shared155.csproj" />
  </ItemGroup>
</Project>
