<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>Scheduling.Handlers63</RootNamespace>
    <AssemblyName>Scheduling.Handlers63</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Service456\Admin.Service456.csproj" />
    <ProjectReference Include="..\Auth.Events\Auth.Events.csproj" />
    <ProjectReference Include="..\Workflow.Contracts434\Workflow.Contracts434.csproj" />
    <ProjectReference Include="..\Billing.Core191\Billing.Core191.csproj" />
    <ProjectReference Include="..\Imaging.Models184\Imaging.Models184.csproj" />
    <ProjectReference Include="..\DataAccess.Models\DataAccess.Models.csproj" />
    <ProjectReference Include="..\Auth.Mappers178\Auth.Mappers178.csproj" />
    <ProjectReference Include="..\Portal.Processors52\Portal.Processors52.csproj" />
    <ProjectReference Include="..\Portal.Web494\Portal.Web494.csproj" />
    <ProjectReference Include="..\Workflow.Contracts330\Workflow.Contracts330.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Validators\GalaxyWorks.Validators.csproj" />
    <ProjectReference Include="..\Utilities.Service358\Utilities.Service358.csproj" />
    <ProjectReference Include="..\Scheduling.Processors25\Scheduling.Processors25.csproj" />
    <ProjectReference Include="..\Imaging.Processors\Imaging.Processors.csproj" />
    <ProjectReference Include="..\Reporting.Tests226\Reporting.Tests226.csproj" />
    <ProjectReference Include="..\Scheduling.Handlers\Scheduling.Handlers.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data375\GalaxyWorks.Data375.csproj" />
  </ItemGroup>
</Project>
