<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Reporting.Client146</RootNamespace>
    <AssemblyName>Reporting.Client146</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Mappers\Auth.Mappers.csproj" />
    <ProjectReference Include="..\Documents.Client58\Documents.Client58.csproj" />
    <ProjectReference Include="..\Admin.Client177\Admin.Client177.csproj" />
    <ProjectReference Include="..\Scheduling.Api3\Scheduling.Api3.csproj" />
    <ProjectReference Include="..\Integration.Events301\Integration.Events301.csproj" />
    <ProjectReference Include="..\Billing.Validators\Billing.Validators.csproj" />
    <ProjectReference Include="..\DataAccess.Api341\DataAccess.Api341.csproj" />
    <ProjectReference Include="..\Import.Api179\Import.Api179.csproj" />
    <ProjectReference Include="..\Billing.Api497\Billing.Api497.csproj" />
    <ProjectReference Include="..\Auth.Client249\Auth.Client249.csproj" />
    <ProjectReference Include="..\Notifications.Web90\Notifications.Web90.csproj" />
    <ProjectReference Include="..\Auth.Data\Auth.Data.csproj" />
    <ProjectReference Include="..\Portal.Shared\Portal.Shared.csproj" />
    <ProjectReference Include="..\Billing.Processors\Billing.Processors.csproj" />
    <ProjectReference Include="..\Import.Handlers407\Import.Handlers407.csproj" />
    <ProjectReference Include="..\Auth.Validators\Auth.Validators.csproj" />
  </ItemGroup>
</Project>
