<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>BatchJobs.Processors</RootNamespace>
    <AssemblyName>BatchJobs.Processors</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Core2\Auth.Core2.csproj" />
    <ProjectReference Include="..\Auth.Handlers209\Auth.Handlers209.csproj" />
    <ProjectReference Include="..\Auth.Events78\Auth.Events78.csproj" />
    <ProjectReference Include="..\Notifications.Contracts\Notifications.Contracts.csproj" />
    <ProjectReference Include="..\Portal.Service378\Portal.Service378.csproj" />
    <ProjectReference Include="..\Integration.Core\Integration.Core.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Service\GalaxyWorks.Service.csproj" />
    <ProjectReference Include="..\Security.Mappers313\Security.Mappers313.csproj" />
    <ProjectReference Include="..\DataAccess.Data474\DataAccess.Data474.csproj" />
    <ProjectReference Include="..\Security.Service\Security.Service.csproj" />
    <ProjectReference Include="..\Utilities.Web398\Utilities.Web398.csproj" />
    <ProjectReference Include="..\Utilities.Handlers268\Utilities.Handlers268.csproj" />
    <ProjectReference Include="..\Security.Validators428\Security.Validators428.csproj" />
    <ProjectReference Include="..\Imaging.Handlers\Imaging.Handlers.csproj" />
    <ProjectReference Include="..\Security.Client349\Security.Client349.csproj" />
    <ProjectReference Include="..\Notifications.Events42\Notifications.Events42.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Web\GalaxyWorks.Web.csproj" />
    <ProjectReference Include="..\Common.Shared\Common.Shared.csproj" />
  </ItemGroup>
</Project>
