<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
    <RootNamespace>Common.Contracts279</RootNamespace>
    <AssemblyName>Common.Contracts279</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Handlers\Admin.Handlers.csproj" />
    <ProjectReference Include="..\Admin.Processors\Admin.Processors.csproj" />
    <ProjectReference Include="..\Admin.Data117\Admin.Data117.csproj" />
    <ProjectReference Include="..\Common.Events367\Common.Events367.csproj" />
    <ProjectReference Include="..\Portal.Validators227\Portal.Validators227.csproj" />
    <ProjectReference Include="..\Reporting.Events220\Reporting.Events220.csproj" />
    <ProjectReference Include="..\Imaging.Api\Imaging.Api.csproj" />
    <ProjectReference Include="..\Integration.Handlers17\Integration.Handlers17.csproj" />
    <ProjectReference Include="..\Admin.Events235\Admin.Events235.csproj" />
    <ProjectReference Include="..\Export.Api12\Export.Api12.csproj" />
    <ProjectReference Include="..\Integration.Handlers333\Integration.Handlers333.csproj" />
    <ProjectReference Include="..\Billing.Mappers124\Billing.Mappers124.csproj" />
    <ProjectReference Include="..\Utilities.Data\Utilities.Data.csproj" />
    <ProjectReference Include="..\Import.Events\Import.Events.csproj" />
    <ProjectReference Include="..\Documents.Shared487\Documents.Shared487.csproj" />
    <ProjectReference Include="..\Common.Core118\Common.Core118.csproj" />
    <ProjectReference Include="..\Scheduling.Models260\Scheduling.Models260.csproj" />
    <ProjectReference Include="..\Import.Service291\Import.Service291.csproj" />
  </ItemGroup>
</Project>
