<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Workflow.Service463</RootNamespace>
    <AssemblyName>Workflow.Service463</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Api143\Auth.Api143.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Core\GalaxyWorks.Core.csproj" />
    <ProjectReference Include="..\Logging.Events\Logging.Events.csproj" />
    <ProjectReference Include="..\Portal.Contracts170\Portal.Contracts170.csproj" />
    <ProjectReference Include="..\Portal.Validators69\Portal.Validators69.csproj" />
    <ProjectReference Include="..\Common.Shared\Common.Shared.csproj" />
    <ProjectReference Include="..\Portal.Service378\Portal.Service378.csproj" />
    <ProjectReference Include="..\Auth.Mappers208\Auth.Mappers208.csproj" />
    <ProjectReference Include="..\Billing.Mappers225\Billing.Mappers225.csproj" />
    <ProjectReference Include="..\Reporting.Client146\Reporting.Client146.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Service\GalaxyWorks.Service.csproj" />
    <ProjectReference Include="..\Import.Api272\Import.Api272.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Processors16\GalaxyWorks.Processors16.csproj" />
    <ProjectReference Include="..\BatchJobs.Contracts\BatchJobs.Contracts.csproj" />
    <ProjectReference Include="..\Notifications.Shared396\Notifications.Shared396.csproj" />
    <ProjectReference Include="..\Notifications.Shared\Notifications.Shared.csproj" />
  </ItemGroup>
</Project>
