<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
    <RootNamespace>Export.Web130</RootNamespace>
    <AssemblyName>Export.Web130</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Api143\Auth.Api143.csproj" />
    <ProjectReference Include="..\Auth.Client249\Auth.Client249.csproj" />
    <ProjectReference Include="..\Admin.Tests\Admin.Tests.csproj" />
    <ProjectReference Include="..\Import.Client7\Import.Client7.csproj" />
    <ProjectReference Include="..\Workflow.Contracts192\Workflow.Contracts192.csproj" />
    <ProjectReference Include="..\Export.Tests\Export.Tests.csproj" />
    <ProjectReference Include="..\Workflow.Web\Workflow.Web.csproj" />
    <ProjectReference Include="..\Workflow.Client351\Workflow.Client351.csproj" />
    <ProjectReference Include="..\Billing.Api9\Billing.Api9.csproj" />
    <ProjectReference Include="..\Reporting.Events317\Reporting.Events317.csproj" />
    <ProjectReference Include="..\Integration.Client\Integration.Client.csproj" />
    <ProjectReference Include="..\Utilities.Mappers\Utilities.Mappers.csproj" />
    <ProjectReference Include="..\Billing.Data\Billing.Data.csproj" />
    <ProjectReference Include="..\DataAccess.Models\DataAccess.Models.csproj" />
    <ProjectReference Include="..\Export.Models461\Export.Models461.csproj" />
    <ProjectReference Include="..\Scheduling.Web196\Scheduling.Web196.csproj" />
    <ProjectReference Include="..\Common.Models381\Common.Models381.csproj" />
    <ProjectReference Include="..\BatchJobs.Tests\BatchJobs.Tests.csproj" />
  </ItemGroup>
</Project>
