<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Logging.Service160</RootNamespace>
    <AssemblyName>Logging.Service160</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Events78\Auth.Events78.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data96\GalaxyWorks.Data96.csproj" />
    <ProjectReference Include="..\Scheduling.Core\Scheduling.Core.csproj" />
    <ProjectReference Include="..\Export.Tests\Export.Tests.csproj" />
    <ProjectReference Include="..\Logging.Data29\Logging.Data29.csproj" />
    <ProjectReference Include="..\Utilities.Web398\Utilities.Web398.csproj" />
    <ProjectReference Include="..\Documents.Tests106\Documents.Tests106.csproj" />
    <ProjectReference Include="..\Common.Events\Common.Events.csproj" />
    <ProjectReference Include="..\BatchJobs.Client109\BatchJobs.Client109.csproj" />
    <ProjectReference Include="..\Imaging.Validators108\Imaging.Validators108.csproj" />
    <ProjectReference Include="..\Utilities.Mappers\Utilities.Mappers.csproj" />
    <ProjectReference Include="..\Export.Client13\Export.Client13.csproj" />
    <ProjectReference Include="..\Documents.Api\Documents.Api.csproj" />
    <ProjectReference Include="..\Export.Web479\Export.Web479.csproj" />
    <ProjectReference Include="..\Reporting.Client422\Reporting.Client422.csproj" />
    <ProjectReference Include="..\Reporting.Mappers239\Reporting.Mappers239.csproj" />
  </ItemGroup>
</Project>
