<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>BatchJobs.Models329</RootNamespace>
    <AssemblyName>BatchJobs.Models329</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Handlers447\Admin.Handlers447.csproj" />
    <ProjectReference Include="..\Imaging.Contracts\Imaging.Contracts.csproj" />
    <ProjectReference Include="..\Import.Client\Import.Client.csproj" />
    <ProjectReference Include="..\Utilities.Mappers97\Utilities.Mappers97.csproj" />
    <ProjectReference Include="..\Utilities.Mappers\Utilities.Mappers.csproj" />
    <ProjectReference Include="..\Auth.Contracts402\Auth.Contracts402.csproj" />
    <ProjectReference Include="..\Portal.Client\Portal.Client.csproj" />
    <ProjectReference Include="..\Common.Shared297\Common.Shared297.csproj" />
    <ProjectReference Include="..\Common.Events\Common.Events.csproj" />
    <ProjectReference Include="..\Admin.Validators240\Admin.Validators240.csproj" />
    <ProjectReference Include="..\Admin.Web46\Admin.Web46.csproj" />
    <ProjectReference Include="..\Documents.Shared487\Documents.Shared487.csproj" />
    <ProjectReference Include="..\Workflow.Mappers370\Workflow.Mappers370.csproj" />
    <ProjectReference Include="..\Portal.Data\Portal.Data.csproj" />
    <ProjectReference Include="..\Logging.Mappers\Logging.Mappers.csproj" />
    <ProjectReference Include="..\Reporting.Processors495\Reporting.Processors495.csproj" />
  </ItemGroup>
</Project>
