<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Common.Service258</RootNamespace>
    <AssemblyName>Common.Service258</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Api255\Admin.Api255.csproj" />
    <ProjectReference Include="..\Auth.Api\Auth.Api.csproj" />
    <ProjectReference Include="..\Auth.Mappers206\Auth.Mappers206.csproj" />
    <ProjectReference Include="..\Workflow.Models\Workflow.Models.csproj" />
    <ProjectReference Include="..\Common.Web488\Common.Web488.csproj" />
    <ProjectReference Include="..\Import.Tests119\Import.Tests119.csproj" />
    <ProjectReference Include="..\Import.Processors\Import.Processors.csproj" />
    <ProjectReference Include="..\Portal.Contracts170\Portal.Contracts170.csproj" />
    <ProjectReference Include="..\DataAccess.Client113\DataAccess.Client113.csproj" />
    <ProjectReference Include="..\Export.Models262\Export.Models262.csproj" />
    <ProjectReference Include="..\Portal.Data266\Portal.Data266.csproj" />
    <ProjectReference Include="..\Billing.Processors259\Billing.Processors259.csproj" />
    <ProjectReference Include="..\Imaging.Models184\Imaging.Models184.csproj" />
    <ProjectReference Include="..\Notifications.Tests299\Notifications.Tests299.csproj" />
    <ProjectReference Include="..\Utilities.Mappers232\Utilities.Mappers232.csproj" />
    <ProjectReference Include="..\Portal.Service231\Portal.Service231.csproj" />
    <ProjectReference Include="..\Portal.Processors389\Portal.Processors389.csproj" />
    <ProjectReference Include="..\Scheduling.Contracts\Scheduling.Contracts.csproj" />
  </ItemGroup>
</Project>
