<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>Notifications.Handlers470</RootNamespace>
    <AssemblyName>Notifications.Handlers470</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Api255\Admin.Api255.csproj" />
    <ProjectReference Include="..\Utilities.Service358\Utilities.Service358.csproj" />
    <ProjectReference Include="..\Workflow.Client\Workflow.Client.csproj" />
    <ProjectReference Include="..\Export.Mappers237\Export.Mappers237.csproj" />
    <ProjectReference Include="..\Scheduling.Web221\Scheduling.Web221.csproj" />
    <ProjectReference Include="..\Scheduling.Validators\Scheduling.Validators.csproj" />
    <ProjectReference Include="..\Billing.Processors259\Billing.Processors259.csproj" />
    <ProjectReference Include="..\Export.Models461\Export.Models461.csproj" />
    <ProjectReference Include="..\Common.Client269\Common.Client269.csproj" />
    <ProjectReference Include="..\Imaging.Events416\Imaging.Events416.csproj" />
    <ProjectReference Include="..\DataAccess.Events283\DataAccess.Events283.csproj" />
    <ProjectReference Include="..\Import.Core\Import.Core.csproj" />
    <ProjectReference Include="..\Reporting.Events188\Reporting.Events188.csproj" />
    <ProjectReference Include="..\Admin.Mappers\Admin.Mappers.csproj" />
    <ProjectReference Include="..\Reporting.Api\Reporting.Api.csproj" />
    <ProjectReference Include="..\BatchJobs.Client\BatchJobs.Client.csproj" />
  </ItemGroup>
</Project>
