<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Notifications.Data446</RootNamespace>
    <AssemblyName>Notifications.Data446</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Contracts\Admin.Contracts.csproj" />
    <ProjectReference Include="..\Admin.Events235\Admin.Events235.csproj" />
    <ProjectReference Include="..\Logging.Contracts373\Logging.Contracts373.csproj" />
    <ProjectReference Include="..\Auth.Core\Auth.Core.csproj" />
    <ProjectReference Include="..\Reporting.Handlers\Reporting.Handlers.csproj" />
    <ProjectReference Include="..\Billing.Web\Billing.Web.csproj" />
    <ProjectReference Include="..\Import.Events493\Import.Events493.csproj" />
    <ProjectReference Include="..\Scheduling.Events\Scheduling.Events.csproj" />
    <ProjectReference Include="..\Export.Processors\Export.Processors.csproj" />
    <ProjectReference Include="..\Admin.Web4\Admin.Web4.csproj" />
    <ProjectReference Include="..\Integration.Handlers17\Integration.Handlers17.csproj" />
    <ProjectReference Include="..\Auth.Client249\Auth.Client249.csproj" />
    <ProjectReference Include="..\DataAccess.Client\DataAccess.Client.csproj" />
    <ProjectReference Include="..\Admin.Shared14\Admin.Shared14.csproj" />
    <ProjectReference Include="..\Notifications.Data406\Notifications.Data406.csproj" />
    <ProjectReference Include="..\Scheduling.Data54\Scheduling.Data54.csproj" />
    <ProjectReference Include="..\Notifications.Web\Notifications.Web.csproj" />
  </ItemGroup>
</Project>
