<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Scheduling.Client</RootNamespace>
    <AssemblyName>Scheduling.Client</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Handlers\Auth.Handlers.csproj" />
    <ProjectReference Include="..\Admin.Tests10\Admin.Tests10.csproj" />
    <ProjectReference Include="..\Documents.Shared427\Documents.Shared427.csproj" />
    <ProjectReference Include="..\Import.Events374\Import.Events374.csproj" />
    <ProjectReference Include="..\Logging.Client\Logging.Client.csproj" />
    <ProjectReference Include="..\Portal.Tests173\Portal.Tests173.csproj" />
    <ProjectReference Include="..\Export.Mappers\Export.Mappers.csproj" />
    <ProjectReference Include="..\Admin.Processors\Admin.Processors.csproj" />
    <ProjectReference Include="..\Workflow.Models\Workflow.Models.csproj" />
    <ProjectReference Include="..\DataAccess.Web\DataAccess.Web.csproj" />
    <ProjectReference Include="..\Workflow.Tests75\Workflow.Tests75.csproj" />
    <ProjectReference Include="..\Import.Processors472\Import.Processors472.csproj" />
    <ProjectReference Include="..\Utilities.Mappers197\Utilities.Mappers197.csproj" />
    <ProjectReference Include="..\Import.Service291\Import.Service291.csproj" />
    <ProjectReference Include="..\Export.Processors\Export.Processors.csproj" />
    <ProjectReference Include="..\Admin.Models\Admin.Models.csproj" />
    <ProjectReference Include="..\Auth.Mappers\Auth.Mappers.csproj" />
  </ItemGroup>
</Project>
