<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Scheduling.Service211</RootNamespace>
    <AssemblyName>Scheduling.Service211</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Service\Admin.Service.csproj" />
    <ProjectReference Include="..\Common.Api186\Common.Api186.csproj" />
    <ProjectReference Include="..\Documents.Core\Documents.Core.csproj" />
    <ProjectReference Include="..\Utilities.Processors440\Utilities.Processors440.csproj" />
    <ProjectReference Include="..\Reporting.Events220\Reporting.Events220.csproj" />
    <ProjectReference Include="..\Documents.Mappers\Documents.Mappers.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data375\GalaxyWorks.Data375.csproj" />
    <ProjectReference Include="..\Import.Events\Import.Events.csproj" />
    <ProjectReference Include="..\Security.Data278\Security.Data278.csproj" />
    <ProjectReference Include="..\Export.Core372\Export.Core372.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data224\GalaxyWorks.Data224.csproj" />
    <ProjectReference Include="..\Billing.Contracts\Billing.Contracts.csproj" />
    <ProjectReference Include="..\DataAccess.Handlers\DataAccess.Handlers.csproj" />
    <ProjectReference Include="..\Export.Processors449\Export.Processors449.csproj" />
    <ProjectReference Include="..\Common.Service\Common.Service.csproj" />
    <ProjectReference Include="..\Logging.Tests\Logging.Tests.csproj" />
  </ItemGroup>
</Project>
