<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Import.Core</RootNamespace>
    <AssemblyName>Import.Core</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Validators240\Admin.Validators240.csproj" />
    <ProjectReference Include="..\Admin.Handlers61\Admin.Handlers61.csproj" />
    <ProjectReference Include="..\Admin.Client\Admin.Client.csproj" />
    <ProjectReference Include="..\Common.Tests\Common.Tests.csproj" />
    <ProjectReference Include="..\Scheduling.Mappers48\Scheduling.Mappers48.csproj" />
    <ProjectReference Include="..\Documents.Shared\Documents.Shared.csproj" />
    <ProjectReference Include="..\Security.Api320\Security.Api320.csproj" />
    <ProjectReference Include="..\Admin.Events\Admin.Events.csproj" />
    <ProjectReference Include="..\Auth.Mappers28\Auth.Mappers28.csproj" />
    <ProjectReference Include="..\Imaging.Client331\Imaging.Client331.csproj" />
    <ProjectReference Include="..\DataAccess.Client113\DataAccess.Client113.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Contracts\GalaxyWorks.Contracts.csproj" />
    <ProjectReference Include="..\Workflow.Processors\Workflow.Processors.csproj" />
    <ProjectReference Include="..\Documents.Client\Documents.Client.csproj" />
    <ProjectReference Include="..\Export.Client414\Export.Client414.csproj" />
    <ProjectReference Include="..\Import.Handlers167\Import.Handlers167.csproj" />
    <ProjectReference Include="..\Import.Events493\Import.Events493.csproj" />
    <ProjectReference Include="..\Admin.Shared\Admin.Shared.csproj" />
  </ItemGroup>
</Project>
