<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
    <RootNamespace>Documents.Service471</RootNamespace>
    <AssemblyName>Documents.Service471</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Mappers206\Auth.Mappers206.csproj" />
    <ProjectReference Include="..\Admin.Models199\Admin.Models199.csproj" />
    <ProjectReference Include="..\Admin.Data408\Admin.Data408.csproj" />
    <ProjectReference Include="..\Logging.Service\Logging.Service.csproj" />
    <ProjectReference Include="..\Security.Client137\Security.Client137.csproj" />
    <ProjectReference Include="..\Scheduling.Events128\Scheduling.Events128.csproj" />
    <ProjectReference Include="..\Integration.Client\Integration.Client.csproj" />
    <ProjectReference Include="..\Security.Web376\Security.Web376.csproj" />
    <ProjectReference Include="..\Workflow.Processors\Workflow.Processors.csproj" />
    <ProjectReference Include="..\Documents.Shared452\Documents.Shared452.csproj" />
    <ProjectReference Include="..\Notifications.Tests195\Notifications.Tests195.csproj" />
    <ProjectReference Include="..\Documents.Service215\Documents.Service215.csproj" />
    <ProjectReference Include="..\Import.Contracts183\Import.Contracts183.csproj" />
    <ProjectReference Include="..\Logging.Data\Logging.Data.csproj" />
    <ProjectReference Include="..\DataAccess.Api454\DataAccess.Api454.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Contracts485\GalaxyWorks.Contracts485.csproj" />
    <ProjectReference Include="..\Integration.Handlers\Integration.Handlers.csproj" />
    <ProjectReference Include="..\Workflow.Data340\Workflow.Data340.csproj" />
  </ItemGroup>
</Project>
