<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Security.Processors246</RootNamespace>
    <AssemblyName>Security.Processors246</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Contracts120\Admin.Contracts120.csproj" />
    <ProjectReference Include="..\Admin.Validators\Admin.Validators.csproj" />
    <ProjectReference Include="..\Admin.Web4\Admin.Web4.csproj" />
    <ProjectReference Include="..\Billing.Validators174\Billing.Validators174.csproj" />
    <ProjectReference Include="..\Notifications.Mappers\Notifications.Mappers.csproj" />
    <ProjectReference Include="..\Reporting.Service207\Reporting.Service207.csproj" />
    <ProjectReference Include="..\Portal.Api123\Portal.Api123.csproj" />
    <ProjectReference Include="..\Import.Shared\Import.Shared.csproj" />
    <ProjectReference Include="..\Admin.Handlers\Admin.Handlers.csproj" />
    <ProjectReference Include="..\Imaging.Models\Imaging.Models.csproj" />
    <ProjectReference Include="..\Auth.Mappers206\Auth.Mappers206.csproj" />
    <ProjectReference Include="..\Utilities.Models\Utilities.Models.csproj" />
    <ProjectReference Include="..\Auth.Client271\Auth.Client271.csproj" />
    <ProjectReference Include="..\Imaging.Validators\Imaging.Validators.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data224\GalaxyWorks.Data224.csproj" />
    <ProjectReference Include="..\Import.Processors\Import.Processors.csproj" />
    <ProjectReference Include="..\Integration.Service401\Integration.Service401.csproj" />
    <ProjectReference Include="..\Documents.Contracts\Documents.Contracts.csproj" />
  </ItemGroup>
</Project>
