<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Integration.Handlers17</RootNamespace>
    <AssemblyName>Integration.Handlers17</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Data135\Auth.Data135.csproj" />
    <ProjectReference Include="..\Security.Api\Security.Api.csproj" />
    <ProjectReference Include="..\Utilities.Handlers\Utilities.Handlers.csproj" />
    <ProjectReference Include="..\Auth.Events5\Auth.Events5.csproj" />
    <ProjectReference Include="..\DataAccess.Handlers\DataAccess.Handlers.csproj" />
    <ProjectReference Include="..\BatchJobs.Data176\BatchJobs.Data176.csproj" />
    <ProjectReference Include="..\Logging.Handlers368\Logging.Handlers368.csproj" />
    <ProjectReference Include="..\Export.Web130\Export.Web130.csproj" />
    <ProjectReference Include="..\Export.Service\Export.Service.csproj" />
    <ProjectReference Include="..\DataAccess.Tests286\DataAccess.Tests286.csproj" />
    <ProjectReference Include="..\Notifications.Service165\Notifications.Service165.csproj" />
    <ProjectReference Include="..\Admin.Handlers\Admin.Handlers.csproj" />
    <ProjectReference Include="..\Workflow.Validators201\Workflow.Validators201.csproj" />
    <ProjectReference Include="..\Common.Service\Common.Service.csproj" />
    <ProjectReference Include="..\Integration.Data\Integration.Data.csproj" />
    <ProjectReference Include="..\Export.Models\Export.Models.csproj" />
  </ItemGroup>
</Project>
