<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Billing.Contracts</RootNamespace>
    <AssemblyName>Billing.Contracts</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Contracts\Admin.Contracts.csproj" />
    <ProjectReference Include="..\Auth.Mappers\Auth.Mappers.csproj" />
    <ProjectReference Include="..\Admin.Api255\Admin.Api255.csproj" />
    <ProjectReference Include="..\Notifications.Handlers33\Notifications.Handlers33.csproj" />
    <ProjectReference Include="..\BatchJobs.Events\BatchJobs.Events.csproj" />
    <ProjectReference Include="..\Utilities.Mappers97\Utilities.Mappers97.csproj" />
    <ProjectReference Include="..\Security.Contracts238\Security.Contracts238.csproj" />
    <ProjectReference Include="..\Imaging.Core204\Imaging.Core204.csproj" />
    <ProjectReference Include="..\Integration.Mappers\Integration.Mappers.csproj" />
    <ProjectReference Include="..\BatchJobs.Processors\BatchJobs.Processors.csproj" />
    <ProjectReference Include="..\Billing.Shared384\Billing.Shared384.csproj" />
    <ProjectReference Include="..\Reporting.Data\Reporting.Data.csproj" />
    <ProjectReference Include="..\Admin.Shared14\Admin.Shared14.csproj" />
    <ProjectReference Include="..\Utilities.Events\Utilities.Events.csproj" />
    <ProjectReference Include="..\BatchJobs.Processors410\BatchJobs.Processors410.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Mappers\GalaxyWorks.Mappers.csproj" />
    <ProjectReference Include="..\Security.Validators428\Security.Validators428.csproj" />
    <ProjectReference Include="..\Auth.Events78\Auth.Events78.csproj" />
  </ItemGroup>
</Project>
