<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Integration.Tests45</RootNamespace>
    <AssemblyName>Integration.Tests45</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Service364\Admin.Service364.csproj" />
    <ProjectReference Include="..\Auth.Processors400\Auth.Processors400.csproj" />
    <ProjectReference Include="..\Admin.Shared310\Admin.Shared310.csproj" />
    <ProjectReference Include="..\Export.Contracts\Export.Contracts.csproj" />
    <ProjectReference Include="..\Documents.Service215\Documents.Service215.csproj" />
    <ProjectReference Include="..\Portal.Api\Portal.Api.csproj" />
    <ProjectReference Include="..\Portal.Tests\Portal.Tests.csproj" />
    <ProjectReference Include="..\Admin.Tests\Admin.Tests.csproj" />
    <ProjectReference Include="..\Reporting.Api\Reporting.Api.csproj" />
    <ProjectReference Include="..\DataAccess.Tests\DataAccess.Tests.csproj" />
    <ProjectReference Include="..\Common.Events\Common.Events.csproj" />
    <ProjectReference Include="..\Common.Api\Common.Api.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Models219\GalaxyWorks.Models219.csproj" />
    <ProjectReference Include="..\Common.Validators430\Common.Validators430.csproj" />
    <ProjectReference Include="..\Documents.Data490\Documents.Data490.csproj" />
    <ProjectReference Include="..\DataAccess.Contracts\DataAccess.Contracts.csproj" />
    <ProjectReference Include="..\Admin.Contracts120\Admin.Contracts120.csproj" />
  </ItemGroup>
</Project>
