<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>DataAccess.Client113</RootNamespace>
    <AssemblyName>DataAccess.Client113</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Validators\Admin.Validators.csproj" />
    <ProjectReference Include="..\Auth.Client249\Auth.Client249.csproj" />
    <ProjectReference Include="..\Admin.Handlers447\Admin.Handlers447.csproj" />
    <ProjectReference Include="..\Notifications.Web90\Notifications.Web90.csproj" />
    <ProjectReference Include="..\Auth.Client\Auth.Client.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data224\GalaxyWorks.Data224.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data96\GalaxyWorks.Data96.csproj" />
    <ProjectReference Include="..\Auth.Core\Auth.Core.csproj" />
    <ProjectReference Include="..\Integration.Handlers333\Integration.Handlers333.csproj" />
    <ProjectReference Include="..\Integration.Handlers17\Integration.Handlers17.csproj" />
    <ProjectReference Include="..\Export.Client414\Export.Client414.csproj" />
    <ProjectReference Include="..\Security.Validators428\Security.Validators428.csproj" />
    <ProjectReference Include="..\Auth.Contracts\Auth.Contracts.csproj" />
    <ProjectReference Include="..\Import.Api272\Import.Api272.csproj" />
    <ProjectReference Include="..\Imaging.Client\Imaging.Client.csproj" />
    <ProjectReference Include="..\Integration.Mappers242\Integration.Mappers242.csproj" />
    <ProjectReference Include="..\Scheduling.Client\Scheduling.Client.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Events\GalaxyWorks.Events.csproj" />
  </ItemGroup>
</Project>
