<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Reporting.Contracts371</RootNamespace>
    <AssemblyName>Reporting.Contracts371</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Client38\Auth.Client38.csproj" />
    <ProjectReference Include="..\Auth.Handlers281\Auth.Handlers281.csproj" />
    <ProjectReference Include="..\Admin.Handlers\Admin.Handlers.csproj" />
    <ProjectReference Include="..\Export.Handlers202\Export.Handlers202.csproj" />
    <ProjectReference Include="..\Security.Mappers\Security.Mappers.csproj" />
    <ProjectReference Include="..\Auth.Data\Auth.Data.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Validators355\GalaxyWorks.Validators355.csproj" />
    <ProjectReference Include="..\Auth.Models236\Auth.Models236.csproj" />
    <ProjectReference Include="..\Import.Handlers354\Import.Handlers354.csproj" />
    <ProjectReference Include="..\Imaging.Shared\Imaging.Shared.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Shared437\GalaxyWorks.Shared437.csproj" />
    <ProjectReference Include="..\Documents.Processors133\Documents.Processors133.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Contracts392\GalaxyWorks.Contracts392.csproj" />
    <ProjectReference Include="..\BatchJobs.Processors\BatchJobs.Processors.csproj" />
    <ProjectReference Include="..\Billing.Validators305\Billing.Validators305.csproj" />
    <ProjectReference Include="..\Common.Handlers\Common.Handlers.csproj" />
    <ProjectReference Include="..\Documents.Processors300\Documents.Processors300.csproj" />
    <ProjectReference Include="..\Export.Processors449\Export.Processors449.csproj" />
  </ItemGroup>
</Project>
