<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Notifications.Handlers112</RootNamespace>
    <AssemblyName>Notifications.Handlers112</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Handlers\Admin.Handlers.csproj" />
    <ProjectReference Include="..\Admin.Api255\Admin.Api255.csproj" />
    <ProjectReference Include="..\Portal.Events139\Portal.Events139.csproj" />
    <ProjectReference Include="..\Admin.Shared363\Admin.Shared363.csproj" />
    <ProjectReference Include="..\Notifications.Shared\Notifications.Shared.csproj" />
    <ProjectReference Include="..\Billing.Handlers101\Billing.Handlers101.csproj" />
    <ProjectReference Include="..\Admin.Handlers61\Admin.Handlers61.csproj" />
    <ProjectReference Include="..\Documents.Client\Documents.Client.csproj" />
    <ProjectReference Include="..\Scheduling.Core\Scheduling.Core.csproj" />
    <ProjectReference Include="..\Billing.Api9\Billing.Api9.csproj" />
    <ProjectReference Include="..\Integration.Processors71\Integration.Processors71.csproj" />
    <ProjectReference Include="..\Auth.Data\Auth.Data.csproj" />
    <ProjectReference Include="..\Scheduling.Mappers\Scheduling.Mappers.csproj" />
    <ProjectReference Include="..\Workflow.Handlers\Workflow.Handlers.csproj" />
    <ProjectReference Include="..\Common.Events367\Common.Events367.csproj" />
    <ProjectReference Include="..\Import.Processors\Import.Processors.csproj" />
    <ProjectReference Include="..\Common.Web\Common.Web.csproj" />
  </ItemGroup>
</Project>
