<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Utilities.Models</RootNamespace>
    <AssemblyName>Utilities.Models</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Handlers\Auth.Handlers.csproj" />
    <ProjectReference Include="..\Auth.Mappers28\Auth.Mappers28.csproj" />
    <ProjectReference Include="..\Admin.Client346\Admin.Client346.csproj" />
    <ProjectReference Include="..\Export.Data344\Export.Data344.csproj" />
    <ProjectReference Include="..\Documents.Processors133\Documents.Processors133.csproj" />
    <ProjectReference Include="..\Scheduling.Models\Scheduling.Models.csproj" />
    <ProjectReference Include="..\Auth.Mappers206\Auth.Mappers206.csproj" />
    <ProjectReference Include="..\Auth.Events5\Auth.Events5.csproj" />
    <ProjectReference Include="..\Export.Core372\Export.Core372.csproj" />
    <ProjectReference Include="..\Documents.Web164\Documents.Web164.csproj" />
    <ProjectReference Include="..\Documents.Core\Documents.Core.csproj" />
    <ProjectReference Include="..\Auth.Handlers281\Auth.Handlers281.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Processors\GalaxyWorks.Processors.csproj" />
    <ProjectReference Include="..\Import.Core\Import.Core.csproj" />
    <ProjectReference Include="..\Imaging.Shared338\Imaging.Shared338.csproj" />
    <ProjectReference Include="..\Notifications.Core166\Notifications.Core166.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Handlers385\GalaxyWorks.Handlers385.csproj" />
    <ProjectReference Include="..\Auth.Processors411\Auth.Processors411.csproj" />
  </ItemGroup>
</Project>
