<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Reporting.Mappers</RootNamespace>
    <AssemblyName>Reporting.Mappers</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Core121\Admin.Core121.csproj" />
    <ProjectReference Include="..\Auth.Handlers\Auth.Handlers.csproj" />
    <ProjectReference Include="..\Import.Service15\Import.Service15.csproj" />
    <ProjectReference Include="..\Utilities.Tests\Utilities.Tests.csproj" />
    <ProjectReference Include="..\Documents.Tests106\Documents.Tests106.csproj" />
    <ProjectReference Include="..\Security.Models136\Security.Models136.csproj" />
    <ProjectReference Include="..\Notifications.Mappers55\Notifications.Mappers55.csproj" />
    <ProjectReference Include="..\Utilities.Events\Utilities.Events.csproj" />
    <ProjectReference Include="..\Common.Api213\Common.Api213.csproj" />
    <ProjectReference Include="..\DataAccess.Api454\DataAccess.Api454.csproj" />
    <ProjectReference Include="..\Admin.Client177\Admin.Client177.csproj" />
    <ProjectReference Include="..\Logging.Tests292\Logging.Tests292.csproj" />
    <ProjectReference Include="..\Notifications.Mappers110\Notifications.Mappers110.csproj" />
    <ProjectReference Include="..\Workflow.Data340\Workflow.Data340.csproj" />
    <ProjectReference Include="..\Utilities.Handlers462\Utilities.Handlers462.csproj" />
    <ProjectReference Include="..\Billing.Core34\Billing.Core34.csproj" />
    <ProjectReference Include="..\Reporting.Processors495\Reporting.Processors495.csproj" />
  </ItemGroup>
</Project>
