<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>GalaxyWorks.Contracts485</RootNamespace>
    <AssemblyName>GalaxyWorks.Contracts485</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Handlers281\Auth.Handlers281.csproj" />
    <ProjectReference Include="..\Logging.Contracts74\Logging.Contracts74.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Contracts\GalaxyWorks.Contracts.csproj" />
    <ProjectReference Include="..\Security.Web230\Security.Web230.csproj" />
    <ProjectReference Include="..\Workflow.Processors\Workflow.Processors.csproj" />
    <ProjectReference Include="..\Utilities.Service358\Utilities.Service358.csproj" />
    <ProjectReference Include="..\Security.Tests\Security.Tests.csproj" />
    <ProjectReference Include="..\Admin.Mappers\Admin.Mappers.csproj" />
    <ProjectReference Include="..\Import.Contracts296\Import.Contracts296.csproj" />
    <ProjectReference Include="..\Logging.Events\Logging.Events.csproj" />
    <ProjectReference Include="..\Logging.Models436\Logging.Models436.csproj" />
    <ProjectReference Include="..\Imaging.Shared322\Imaging.Shared322.csproj" />
    <ProjectReference Include="..\BatchJobs.Core\BatchJobs.Core.csproj" />
    <ProjectReference Include="..\Scheduling.Shared\Scheduling.Shared.csproj" />
    <ProjectReference Include="..\Admin.Web154\Admin.Web154.csproj" />
    <ProjectReference Include="..\Import.Processors412\Import.Processors412.csproj" />
  </ItemGroup>
</Project>
