<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Export.Api12</RootNamespace>
    <AssemblyName>Export.Api12</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Client38\Auth.Client38.csproj" />
    <ProjectReference Include="..\Portal.Handlers26\Portal.Handlers26.csproj" />
    <ProjectReference Include="..\Integration.Tests\Integration.Tests.csproj" />
    <ProjectReference Include="..\Import.Api314\Import.Api314.csproj" />
    <ProjectReference Include="..\Export.Service\Export.Service.csproj" />
    <ProjectReference Include="..\Export.Shared\Export.Shared.csproj" />
    <ProjectReference Include="..\Portal.Api123\Portal.Api123.csproj" />
    <ProjectReference Include="..\Security.Api134\Security.Api134.csproj" />
    <ProjectReference Include="..\Workflow.Models\Workflow.Models.csproj" />
    <ProjectReference Include="..\Integration.Api\Integration.Api.csproj" />
    <ProjectReference Include="..\Logging.Service382\Logging.Service382.csproj" />
    <ProjectReference Include="..\Import.Client7\Import.Client7.csproj" />
    <ProjectReference Include="..\Export.Models461\Export.Models461.csproj" />
    <ProjectReference Include="..\Portal.Shared\Portal.Shared.csproj" />
    <ProjectReference Include="..\Integration.Handlers333\Integration.Handlers333.csproj" />
    <ProjectReference Include="..\Reporting.Core\Reporting.Core.csproj" />
  </ItemGroup>
</Project>
