<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Workflow.Api433</RootNamespace>
    <AssemblyName>Workflow.Api433</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Web46\Admin.Web46.csproj" />
    <ProjectReference Include="..\Admin.Handlers61\Admin.Handlers61.csproj" />
    <ProjectReference Include="..\Admin.Mappers\Admin.Mappers.csproj" />
    <ProjectReference Include="..\Export.Core372\Export.Core372.csproj" />
    <ProjectReference Include="..\Billing.Models\Billing.Models.csproj" />
    <ProjectReference Include="..\Security.Core\Security.Core.csproj" />
    <ProjectReference Include="..\Imaging.Models459\Imaging.Models459.csproj" />
    <ProjectReference Include="..\Security.Handlers162\Security.Handlers162.csproj" />
    <ProjectReference Include="..\Utilities.Api66\Utilities.Api66.csproj" />
    <ProjectReference Include="..\Imaging.Contracts473\Imaging.Contracts473.csproj" />
    <ProjectReference Include="..\Common.Web488\Common.Web488.csproj" />
    <ProjectReference Include="..\Integration.Service147\Integration.Service147.csproj" />
    <ProjectReference Include="..\Scheduling.Core\Scheduling.Core.csproj" />
    <ProjectReference Include="..\DataAccess.Api454\DataAccess.Api454.csproj" />
    <ProjectReference Include="..\Security.Service383\Security.Service383.csproj" />
    <ProjectReference Include="..\Common.Processors142\Common.Processors142.csproj" />
    <ProjectReference Include="..\Billing.Core191\Billing.Core191.csproj" />
    <ProjectReference Include="..\BatchJobs.Client\BatchJobs.Client.csproj" />
  </ItemGroup>
</Project>
