<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Security.Events288</RootNamespace>
    <AssemblyName>Security.Events288</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Tests10\Admin.Tests10.csproj" />
    <ProjectReference Include="..\Scheduling.Tests\Scheduling.Tests.csproj" />
    <ProjectReference Include="..\Export.Api\Export.Api.csproj" />
    <ProjectReference Include="..\BatchJobs.Processors500\BatchJobs.Processors500.csproj" />
    <ProjectReference Include="..\DataAccess.Service464\DataAccess.Service464.csproj" />
    <ProjectReference Include="..\Admin.Contracts\Admin.Contracts.csproj" />
    <ProjectReference Include="..\Imaging.Mappers93\Imaging.Mappers93.csproj" />
    <ProjectReference Include="..\Notifications.Contracts\Notifications.Contracts.csproj" />
    <ProjectReference Include="..\Scheduling.Processors397\Scheduling.Processors397.csproj" />
    <ProjectReference Include="..\Import.Models457\Import.Models457.csproj" />
    <ProjectReference Include="..\Common.Mappers343\Common.Mappers343.csproj" />
    <ProjectReference Include="..\Documents.Service215\Documents.Service215.csproj" />
    <ProjectReference Include="..\Admin.Validators431\Admin.Validators431.csproj" />
    <ProjectReference Include="..\Security.Tests\Security.Tests.csproj" />
    <ProjectReference Include="..\Notifications.Data\Notifications.Data.csproj" />
    <ProjectReference Include="..\Integration.Events301\Integration.Events301.csproj" />
  </ItemGroup>
</Project>
