<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Portal.Data</RootNamespace>
    <AssemblyName>Portal.Data</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Service456\Admin.Service456.csproj" />
    <ProjectReference Include="..\Auth.Mappers28\Auth.Mappers28.csproj" />
    <ProjectReference Include="..\Documents.Web\Documents.Web.csproj" />
    <ProjectReference Include="..\Import.Processors\Import.Processors.csproj" />
    <ProjectReference Include="..\Logging.Handlers285\Logging.Handlers285.csproj" />
    <ProjectReference Include="..\Imaging.Tests\Imaging.Tests.csproj" />
    <ProjectReference Include="..\Import.Data\Import.Data.csproj" />
    <ProjectReference Include="..\Billing.Handlers\Billing.Handlers.csproj" />
    <ProjectReference Include="..\Common.Models\Common.Models.csproj" />
    <ProjectReference Include="..\Documents.Data492\Documents.Data492.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Contracts485\GalaxyWorks.Contracts485.csproj" />
    <ProjectReference Include="..\Security.Validators\Security.Validators.csproj" />
    <ProjectReference Include="..\Workflow.Mappers\Workflow.Mappers.csproj" />
    <ProjectReference Include="..\Portal.Validators\Portal.Validators.csproj" />
    <ProjectReference Include="..\Imaging.Mappers\Imaging.Mappers.csproj" />
    <ProjectReference Include="..\Admin.Client\Admin.Client.csproj" />
    <ProjectReference Include="..\Imaging.Client331\Imaging.Client331.csproj" />
  </ItemGroup>
</Project>
