<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Reporting.Web105</RootNamespace>
    <AssemblyName>Reporting.Web105</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Contracts402\Auth.Contracts402.csproj" />
    <ProjectReference Include="..\Admin.Service364\Admin.Service364.csproj" />
    <ProjectReference Include="..\Utilities.Web\Utilities.Web.csproj" />
    <ProjectReference Include="..\BatchJobs.Handlers443\BatchJobs.Handlers443.csproj" />
    <ProjectReference Include="..\Workflow.Service463\Workflow.Service463.csproj" />
    <ProjectReference Include="..\Common.Data126\Common.Data126.csproj" />
    <ProjectReference Include="..\Scheduling.Web\Scheduling.Web.csproj" />
    <ProjectReference Include="..\DataAccess.Models\DataAccess.Models.csproj" />
    <ProjectReference Include="..\BatchJobs.Handlers\BatchJobs.Handlers.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Client\GalaxyWorks.Client.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Core309\GalaxyWorks.Core309.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Handlers\GalaxyWorks.Handlers.csproj" />
    <ProjectReference Include="..\Scheduling.Handlers\Scheduling.Handlers.csproj" />
    <ProjectReference Include="..\Admin.Web154\Admin.Web154.csproj" />
    <ProjectReference Include="..\Security.Handlers\Security.Handlers.csproj" />
    <ProjectReference Include="..\Workflow.Shared298\Workflow.Shared298.csproj" />
    <ProjectReference Include="..\Export.Web210\Export.Web210.csproj" />
  </ItemGroup>
</Project>
