<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Reporting.Handlers</RootNamespace>
    <AssemblyName>Reporting.Handlers</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Contracts\Admin.Contracts.csproj" />
    <ProjectReference Include="..\Admin.Service339\Admin.Service339.csproj" />
    <ProjectReference Include="..\Admin.Data408\Admin.Data408.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Tests\GalaxyWorks.Tests.csproj" />
    <ProjectReference Include="..\Notifications.Shared\Notifications.Shared.csproj" />
    <ProjectReference Include="..\Reporting.Mappers\Reporting.Mappers.csproj" />
    <ProjectReference Include="..\Workflow.Service\Workflow.Service.csproj" />
    <ProjectReference Include="..\Billing.Processors103\Billing.Processors103.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data263\GalaxyWorks.Data263.csproj" />
    <ProjectReference Include="..\Notifications.Mappers110\Notifications.Mappers110.csproj" />
    <ProjectReference Include="..\Export.Core168\Export.Core168.csproj" />
    <ProjectReference Include="..\Reporting.Tests226\Reporting.Tests226.csproj" />
    <ProjectReference Include="..\Admin.Handlers61\Admin.Handlers61.csproj" />
    <ProjectReference Include="..\Integration.Validators369\Integration.Validators369.csproj" />
    <ProjectReference Include="..\Common.Validators\Common.Validators.csproj" />
    <ProjectReference Include="..\Export.Tests62\Export.Tests62.csproj" />
    <ProjectReference Include="..\Billing.Validators305\Billing.Validators305.csproj" />
    <ProjectReference Include="..\Admin.Web154\Admin.Web154.csproj" />
  </ItemGroup>
</Project>
