<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Common.Processors245</RootNamespace>
    <AssemblyName>Common.Processors245</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Data\Admin.Data.csproj" />
    <ProjectReference Include="..\Admin.Validators431\Admin.Validators431.csproj" />
    <ProjectReference Include="..\Admin.Mappers324\Admin.Mappers324.csproj" />
    <ProjectReference Include="..\Security.Models284\Security.Models284.csproj" />
    <ProjectReference Include="..\Auth.Api143\Auth.Api143.csproj" />
    <ProjectReference Include="..\Integration.Client\Integration.Client.csproj" />
    <ProjectReference Include="..\Import.Web\Import.Web.csproj" />
    <ProjectReference Include="..\Security.Client349\Security.Client349.csproj" />
    <ProjectReference Include="..\Imaging.Web\Imaging.Web.csproj" />
    <ProjectReference Include="..\Import.Processors472\Import.Processors472.csproj" />
    <ProjectReference Include="..\Documents.Validators\Documents.Validators.csproj" />
    <ProjectReference Include="..\BatchJobs.Contracts\BatchJobs.Contracts.csproj" />
    <ProjectReference Include="..\Auth.Processors\Auth.Processors.csproj" />
    <ProjectReference Include="..\Admin.Events235\Admin.Events235.csproj" />
    <ProjectReference Include="..\Scheduling.Processors80\Scheduling.Processors80.csproj" />
    <ProjectReference Include="..\Import.Api179\Import.Api179.csproj" />
    <ProjectReference Include="..\Imaging.Events303\Imaging.Events303.csproj" />
  </ItemGroup>
</Project>
