<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Security.Core</RootNamespace>
    <AssemblyName>Security.Core</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Events306\Admin.Events306.csproj" />
    <ProjectReference Include="..\Auth.Mappers28\Auth.Mappers28.csproj" />
    <ProjectReference Include="..\Export.Data344\Export.Data344.csproj" />
    <ProjectReference Include="..\Common.Data\Common.Data.csproj" />
    <ProjectReference Include="..\Documents.Data68\Documents.Data68.csproj" />
    <ProjectReference Include="..\Scheduling.Models342\Scheduling.Models342.csproj" />
    <ProjectReference Include="..\Billing.Tests194\Billing.Tests194.csproj" />
    <ProjectReference Include="..\Billing.Api497\Billing.Api497.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Models219\GalaxyWorks.Models219.csproj" />
    <ProjectReference Include="..\Export.Core386\Export.Core386.csproj" />
    <ProjectReference Include="..\Auth.Client\Auth.Client.csproj" />
    <ProjectReference Include="..\Auth.Processors400\Auth.Processors400.csproj" />
    <ProjectReference Include="..\Utilities.Api234\Utilities.Api234.csproj" />
    <ProjectReference Include="..\Documents.Api251\Documents.Api251.csproj" />
    <ProjectReference Include="..\Auth.Validators\Auth.Validators.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data453\GalaxyWorks.Data453.csproj" />
    <ProjectReference Include="..\DataAccess.Models\DataAccess.Models.csproj" />
  </ItemGroup>
</Project>
