<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Documents.Shared334</RootNamespace>
    <AssemblyName>Documents.Shared334</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Web154\Admin.Web154.csproj" />
    <ProjectReference Include="..\Portal.Handlers\Portal.Handlers.csproj" />
    <ProjectReference Include="..\Security.Client353\Security.Client353.csproj" />
    <ProjectReference Include="..\Utilities.Web\Utilities.Web.csproj" />
    <ProjectReference Include="..\Portal.Processors\Portal.Processors.csproj" />
    <ProjectReference Include="..\Billing.Validators\Billing.Validators.csproj" />
    <ProjectReference Include="..\Utilities.Contracts24\Utilities.Contracts24.csproj" />
    <ProjectReference Include="..\Security.Api\Security.Api.csproj" />
    <ProjectReference Include="..\Security.Mappers\Security.Mappers.csproj" />
    <ProjectReference Include="..\Scheduling.Events\Scheduling.Events.csproj" />
    <ProjectReference Include="..\Common.Processors142\Common.Processors142.csproj" />
    <ProjectReference Include="..\Common.Mappers\Common.Mappers.csproj" />
    <ProjectReference Include="..\Utilities.Processors91\Utilities.Processors91.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Shared437\GalaxyWorks.Shared437.csproj" />
    <ProjectReference Include="..\Import.Contracts183\Import.Contracts183.csproj" />
    <ProjectReference Include="..\Auth.Core2\Auth.Core2.csproj" />
  </ItemGroup>
</Project>
