<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Scheduling.Web196</RootNamespace>
    <AssemblyName>Scheduling.Web196</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Data465\Admin.Data465.csproj" />
    <ProjectReference Include="..\Documents.Web164\Documents.Web164.csproj" />
    <ProjectReference Include="..\Notifications.Tests195\Notifications.Tests195.csproj" />
    <ProjectReference Include="..\Reporting.Tests226\Reporting.Tests226.csproj" />
    <ProjectReference Include="..\Import.Processors412\Import.Processors412.csproj" />
    <ProjectReference Include="..\Logging.Data29\Logging.Data29.csproj" />
    <ProjectReference Include="..\Portal.Core8\Portal.Core8.csproj" />
    <ProjectReference Include="..\Utilities.Api234\Utilities.Api234.csproj" />
    <ProjectReference Include="..\Admin.Mappers\Admin.Mappers.csproj" />
    <ProjectReference Include="..\Portal.Data216\Portal.Data216.csproj" />
    <ProjectReference Include="..\Billing.Models\Billing.Models.csproj" />
    <ProjectReference Include="..\Imaging.Shared322\Imaging.Shared322.csproj" />
    <ProjectReference Include="..\Utilities.Processors\Utilities.Processors.csproj" />
    <ProjectReference Include="..\Export.Api\Export.Api.csproj" />
    <ProjectReference Include="..\Portal.Shared\Portal.Shared.csproj" />
    <ProjectReference Include="..\DataAccess.Contracts\DataAccess.Contracts.csproj" />
  </ItemGroup>
</Project>
