<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Integration.Mappers</RootNamespace>
    <AssemblyName>Integration.Mappers</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Service\Admin.Service.csproj" />
    <ProjectReference Include="..\Notifications.Service\Notifications.Service.csproj" />
    <ProjectReference Include="..\Import.Shared\Import.Shared.csproj" />
    <ProjectReference Include="..\Utilities.Events\Utilities.Events.csproj" />
    <ProjectReference Include="..\Notifications.Api\Notifications.Api.csproj" />
    <ProjectReference Include="..\Logging.Contracts\Logging.Contracts.csproj" />
    <ProjectReference Include="..\Reporting.Processors495\Reporting.Processors495.csproj" />
    <ProjectReference Include="..\Auth.Contracts\Auth.Contracts.csproj" />
    <ProjectReference Include="..\Import.Contracts296\Import.Contracts296.csproj" />
    <ProjectReference Include="..\Security.Contracts\Security.Contracts.csproj" />
    <ProjectReference Include="..\Security.Processors295\Security.Processors295.csproj" />
    <ProjectReference Include="..\Admin.Service456\Admin.Service456.csproj" />
    <ProjectReference Include="..\Documents.Shared334\Documents.Shared334.csproj" />
    <ProjectReference Include="..\Notifications.Handlers\Notifications.Handlers.csproj" />
    <ProjectReference Include="..\Notifications.Mappers55\Notifications.Mappers55.csproj" />
    <ProjectReference Include="..\Imaging.Web172\Imaging.Web172.csproj" />
  </ItemGroup>
</Project>
