<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>Notifications.Handlers33</RootNamespace>
    <AssemblyName>Notifications.Handlers33</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Shared14\Admin.Shared14.csproj" />
    <ProjectReference Include="..\Admin.Shared363\Admin.Shared363.csproj" />
    <ProjectReference Include="..\Admin.Shared310\Admin.Shared310.csproj" />
    <ProjectReference Include="..\DataAccess.Processors\DataAccess.Processors.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Contracts485\GalaxyWorks.Contracts485.csproj" />
    <ProjectReference Include="..\Reporting.Events220\Reporting.Events220.csproj" />
    <ProjectReference Include="..\Imaging.Service\Imaging.Service.csproj" />
    <ProjectReference Include="..\Scheduling.Events128\Scheduling.Events128.csproj" />
    <ProjectReference Include="..\Scheduling.Tests\Scheduling.Tests.csproj" />
    <ProjectReference Include="..\Common.Service\Common.Service.csproj" />
    <ProjectReference Include="..\Scheduling.Processors25\Scheduling.Processors25.csproj" />
    <ProjectReference Include="..\Documents.Models\Documents.Models.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data453\GalaxyWorks.Data453.csproj" />
    <ProjectReference Include="..\Notifications.Models\Notifications.Models.csproj" />
    <ProjectReference Include="..\Security.Handlers\Security.Handlers.csproj" />
    <ProjectReference Include="..\Logging.Handlers285\Logging.Handlers285.csproj" />
    <ProjectReference Include="..\Admin.Contracts120\Admin.Contracts120.csproj" />
    <ProjectReference Include="..\Auth.Validators\Auth.Validators.csproj" />
  </ItemGroup>
</Project>
