<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Scheduling.Tests85</RootNamespace>
    <AssemblyName>Scheduling.Tests85</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Data\Auth.Data.csproj" />
    <ProjectReference Include="..\Admin.Data117\Admin.Data117.csproj" />
    <ProjectReference Include="..\Common.Api\Common.Api.csproj" />
    <ProjectReference Include="..\Scheduling.Models342\Scheduling.Models342.csproj" />
    <ProjectReference Include="..\Integration.Service\Integration.Service.csproj" />
    <ProjectReference Include="..\Scheduling.Processors335\Scheduling.Processors335.csproj" />
    <ProjectReference Include="..\Security.Shared365\Security.Shared365.csproj" />
    <ProjectReference Include="..\Import.Mappers56\Import.Mappers56.csproj" />
    <ProjectReference Include="..\Common.Web488\Common.Web488.csproj" />
    <ProjectReference Include="..\Workflow.Api433\Workflow.Api433.csproj" />
    <ProjectReference Include="..\Scheduling.Core\Scheduling.Core.csproj" />
    <ProjectReference Include="..\Portal.Api99\Portal.Api99.csproj" />
    <ProjectReference Include="..\DataAccess.Shared486\DataAccess.Shared486.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Client366\GalaxyWorks.Client366.csproj" />
    <ProjectReference Include="..\Documents.Validators102\Documents.Validators102.csproj" />
    <ProjectReference Include="..\DataAccess.Data474\DataAccess.Data474.csproj" />
    <ProjectReference Include="..\Scheduling.Web196\Scheduling.Web196.csproj" />
  </ItemGroup>
</Project>
