<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Documents.Api439</RootNamespace>
    <AssemblyName>Documents.Api439</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Service\Admin.Service.csproj" />
    <ProjectReference Include="..\Auth.Client271\Auth.Client271.csproj" />
    <ProjectReference Include="..\Security.Api320\Security.Api320.csproj" />
    <ProjectReference Include="..\Billing.Mappers198\Billing.Mappers198.csproj" />
    <ProjectReference Include="..\Utilities.Validators\Utilities.Validators.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Mappers\GalaxyWorks.Mappers.csproj" />
    <ProjectReference Include="..\Scheduling.Tests76\Scheduling.Tests76.csproj" />
    <ProjectReference Include="..\Portal.Data266\Portal.Data266.csproj" />
    <ProjectReference Include="..\Security.Shared\Security.Shared.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Api390\GalaxyWorks.Api390.csproj" />
    <ProjectReference Include="..\Documents.Tests106\Documents.Tests106.csproj" />
    <ProjectReference Include="..\Security.Contracts72\Security.Contracts72.csproj" />
    <ProjectReference Include="..\Billing.Tests\Billing.Tests.csproj" />
    <ProjectReference Include="..\BatchJobs.Handlers443\BatchJobs.Handlers443.csproj" />
    <ProjectReference Include="..\Security.Events\Security.Events.csproj" />
    <ProjectReference Include="..\Notifications.Events42\Notifications.Events42.csproj" />
    <ProjectReference Include="..\Notifications.Data446\Notifications.Data446.csproj" />
  </ItemGroup>
</Project>
