<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Integration.Validators369</RootNamespace>
    <AssemblyName>Integration.Validators369</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Shared310\Admin.Shared310.csproj" />
    <ProjectReference Include="..\Workflow.Contracts434\Workflow.Contracts434.csproj" />
    <ProjectReference Include="..\Documents.Tests458\Documents.Tests458.csproj" />
    <ProjectReference Include="..\BatchJobs.Client\BatchJobs.Client.csproj" />
    <ProjectReference Include="..\Common.Client\Common.Client.csproj" />
    <ProjectReference Include="..\Portal.Validators227\Portal.Validators227.csproj" />
    <ProjectReference Include="..\Auth.Core2\Auth.Core2.csproj" />
    <ProjectReference Include="..\Integration.Events\Integration.Events.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data224\GalaxyWorks.Data224.csproj" />
    <ProjectReference Include="..\Workflow.Contracts330\Workflow.Contracts330.csproj" />
    <ProjectReference Include="..\Reporting.Events317\Reporting.Events317.csproj" />
    <ProjectReference Include="..\Imaging.Web172\Imaging.Web172.csproj" />
    <ProjectReference Include="..\Export.Tests\Export.Tests.csproj" />
    <ProjectReference Include="..\Reporting.Tests\Reporting.Tests.csproj" />
    <ProjectReference Include="..\Reporting.Handlers347\Reporting.Handlers347.csproj" />
    <ProjectReference Include="..\Reporting.Validators\Reporting.Validators.csproj" />
  </ItemGroup>
</Project>
