<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Billing.Core191</RootNamespace>
    <AssemblyName>Billing.Core191</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Core\Auth.Core.csproj" />
    <ProjectReference Include="..\Auth.Contracts\Auth.Contracts.csproj" />
    <ProjectReference Include="..\Security.Validators217\Security.Validators217.csproj" />
    <ProjectReference Include="..\Import.Shared\Import.Shared.csproj" />
    <ProjectReference Include="..\Reporting.Events220\Reporting.Events220.csproj" />
    <ProjectReference Include="..\Documents.Models\Documents.Models.csproj" />
    <ProjectReference Include="..\Logging.Shared\Logging.Shared.csproj" />
    <ProjectReference Include="..\Admin.Service364\Admin.Service364.csproj" />
    <ProjectReference Include="..\DataAccess.Client82\DataAccess.Client82.csproj" />
    <ProjectReference Include="..\Billing.Client\Billing.Client.csproj" />
    <ProjectReference Include="..\Portal.Mappers\Portal.Mappers.csproj" />
    <ProjectReference Include="..\Admin.Contracts\Admin.Contracts.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data375\GalaxyWorks.Data375.csproj" />
    <ProjectReference Include="..\DataAccess.Api307\DataAccess.Api307.csproj" />
    <ProjectReference Include="..\Security.Contracts238\Security.Contracts238.csproj" />
    <ProjectReference Include="..\Workflow.Web377\Workflow.Web377.csproj" />
    <ProjectReference Include="..\DataAccess.Api454\DataAccess.Api454.csproj" />
  </ItemGroup>
</Project>
