<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
    <RootNamespace>Documents.Web164</RootNamespace>
    <AssemblyName>Documents.Web164</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Api116\Auth.Api116.csproj" />
    <ProjectReference Include="..\Admin.Validators431\Admin.Validators431.csproj" />
    <ProjectReference Include="..\Admin.Validators240\Admin.Validators240.csproj" />
    <ProjectReference Include="..\Common.Shared95\Common.Shared95.csproj" />
    <ProjectReference Include="..\Admin.Service456\Admin.Service456.csproj" />
    <ProjectReference Include="..\Notifications.Data446\Notifications.Data446.csproj" />
    <ProjectReference Include="..\Security.Contracts72\Security.Contracts72.csproj" />
    <ProjectReference Include="..\Utilities.Mappers197\Utilities.Mappers197.csproj" />
    <ProjectReference Include="..\Portal.Validators250\Portal.Validators250.csproj" />
    <ProjectReference Include="..\Scheduling.Models\Scheduling.Models.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data96\GalaxyWorks.Data96.csproj" />
    <ProjectReference Include="..\Common.Processors142\Common.Processors142.csproj" />
    <ProjectReference Include="..\Documents.Api\Documents.Api.csproj" />
    <ProjectReference Include="..\Billing.Contracts\Billing.Contracts.csproj" />
    <ProjectReference Include="..\Billing.Service432\Billing.Service432.csproj" />
    <ProjectReference Include="..\Auth.Api143\Auth.Api143.csproj" />
    <ProjectReference Include="..\Common.Api57\Common.Api57.csproj" />
    <ProjectReference Include="..\Billing.Client182\Billing.Client182.csproj" />
  </ItemGroup>
</Project>
