<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Portal.Data266</RootNamespace>
    <AssemblyName>Portal.Data266</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Handlers209\Auth.Handlers209.csproj" />
    <ProjectReference Include="..\Auth.Client249\Auth.Client249.csproj" />
    <ProjectReference Include="..\Auth.Api143\Auth.Api143.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data\GalaxyWorks.Data.csproj" />
    <ProjectReference Include="..\Auth.Contracts\Auth.Contracts.csproj" />
    <ProjectReference Include="..\Import.Api\Import.Api.csproj" />
    <ProjectReference Include="..\Documents.Api156\Documents.Api156.csproj" />
    <ProjectReference Include="..\Admin.Validators431\Admin.Validators431.csproj" />
    <ProjectReference Include="..\Import.Api314\Import.Api314.csproj" />
    <ProjectReference Include="..\Documents.Api439\Documents.Api439.csproj" />
    <ProjectReference Include="..\Import.Web\Import.Web.csproj" />
    <ProjectReference Include="..\Admin.Core121\Admin.Core121.csproj" />
    <ProjectReference Include="..\Imaging.Events\Imaging.Events.csproj" />
    <ProjectReference Include="..\Admin.Web4\Admin.Web4.csproj" />
    <ProjectReference Include="..\Billing.Core34\Billing.Core34.csproj" />
    <ProjectReference Include="..\Utilities.Processors\Utilities.Processors.csproj" />
    <ProjectReference Include="..\Notifications.Service475\Notifications.Service475.csproj" />
  </ItemGroup>
</Project>
