<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Integration.Processors71</RootNamespace>
    <AssemblyName>Integration.Processors71</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Models199\Admin.Models199.csproj" />
    <ProjectReference Include="..\Admin.Service456\Admin.Service456.csproj" />
    <ProjectReference Include="..\Common.Mappers343\Common.Mappers343.csproj" />
    <ProjectReference Include="..\Workflow.Client\Workflow.Client.csproj" />
    <ProjectReference Include="..\Import.Events493\Import.Events493.csproj" />
    <ProjectReference Include="..\Portal.Service\Portal.Service.csproj" />
    <ProjectReference Include="..\Portal.Contracts\Portal.Contracts.csproj" />
    <ProjectReference Include="..\Admin.Events235\Admin.Events235.csproj" />
    <ProjectReference Include="..\BatchJobs.Core\BatchJobs.Core.csproj" />
    <ProjectReference Include="..\Documents.Shared487\Documents.Shared487.csproj" />
    <ProjectReference Include="..\Common.Processors142\Common.Processors142.csproj" />
    <ProjectReference Include="..\Security.Data\Security.Data.csproj" />
    <ProjectReference Include="..\Import.Client\Import.Client.csproj" />
    <ProjectReference Include="..\Documents.Tests171\Documents.Tests171.csproj" />
    <ProjectReference Include="..\Logging.Service160\Logging.Service160.csproj" />
    <ProjectReference Include="..\Auth.Processors411\Auth.Processors411.csproj" />
  </ItemGroup>
</Project>
