<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>DataAccess.Handlers482</RootNamespace>
    <AssemblyName>DataAccess.Handlers482</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Handlers\Admin.Handlers.csproj" />
    <ProjectReference Include="..\Admin.Service\Admin.Service.csproj" />
    <ProjectReference Include="..\Scheduling.Web60\Scheduling.Web60.csproj" />
    <ProjectReference Include="..\Common.Validators50\Common.Validators50.csproj" />
    <ProjectReference Include="..\Portal.Service378\Portal.Service378.csproj" />
    <ProjectReference Include="..\Export.Events163\Export.Events163.csproj" />
    <ProjectReference Include="..\Export.Service30\Export.Service30.csproj" />
    <ProjectReference Include="..\Portal.Validators69\Portal.Validators69.csproj" />
    <ProjectReference Include="..\Security.Shared448\Security.Shared448.csproj" />
    <ProjectReference Include="..\Imaging.Mappers\Imaging.Mappers.csproj" />
    <ProjectReference Include="..\DataAccess.Tests282\DataAccess.Tests282.csproj" />
    <ProjectReference Include="..\Admin.Models\Admin.Models.csproj" />
    <ProjectReference Include="..\Admin.Client\Admin.Client.csproj" />
    <ProjectReference Include="..\Import.Api179\Import.Api179.csproj" />
    <ProjectReference Include="..\Logging.Models379\Logging.Models379.csproj" />
    <ProjectReference Include="..\Integration.Service147\Integration.Service147.csproj" />
    <ProjectReference Include="..\Imaging.Models\Imaging.Models.csproj" />
  </ItemGroup>
</Project>
