<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Billing.Mappers124</RootNamespace>
    <AssemblyName>Billing.Mappers124</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Shared14\Admin.Shared14.csproj" />
    <ProjectReference Include="..\Admin.Mappers324\Admin.Mappers324.csproj" />
    <ProjectReference Include="..\Auth.Contracts395\Auth.Contracts395.csproj" />
    <ProjectReference Include="..\Scheduling.Web264\Scheduling.Web264.csproj" />
    <ProjectReference Include="..\Billing.Processors103\Billing.Processors103.csproj" />
    <ProjectReference Include="..\Admin.Service\Admin.Service.csproj" />
    <ProjectReference Include="..\DataAccess.Handlers482\DataAccess.Handlers482.csproj" />
    <ProjectReference Include="..\Integration.Validators369\Integration.Validators369.csproj" />
    <ProjectReference Include="..\Auth.Contracts\Auth.Contracts.csproj" />
    <ProjectReference Include="..\Notifications.Handlers\Notifications.Handlers.csproj" />
    <ProjectReference Include="..\Integration.Shared\Integration.Shared.csproj" />
    <ProjectReference Include="..\Notifications.Web90\Notifications.Web90.csproj" />
    <ProjectReference Include="..\Common.Events\Common.Events.csproj" />
    <ProjectReference Include="..\BatchJobs.Models329\BatchJobs.Models329.csproj" />
    <ProjectReference Include="..\BatchJobs.Client109\BatchJobs.Client109.csproj" />
    <ProjectReference Include="..\Import.Events493\Import.Events493.csproj" />
    <ProjectReference Include="..\Auth.Core2\Auth.Core2.csproj" />
    <ProjectReference Include="..\Common.Client\Common.Client.csproj" />
  </ItemGroup>
</Project>
