<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Workflow.Models253</RootNamespace>
    <AssemblyName>Workflow.Models253</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Models23\Auth.Models23.csproj" />
    <ProjectReference Include="..\Common.Api186\Common.Api186.csproj" />
    <ProjectReference Include="..\Common.Processors142\Common.Processors142.csproj" />
    <ProjectReference Include="..\Import.Service\Import.Service.csproj" />
    <ProjectReference Include="..\Import.Tests\Import.Tests.csproj" />
    <ProjectReference Include="..\Import.Web\Import.Web.csproj" />
    <ProjectReference Include="..\Integration.Events\Integration.Events.csproj" />
    <ProjectReference Include="..\Notifications.Data446\Notifications.Data446.csproj" />
    <ProjectReference Include="..\Security.Models284\Security.Models284.csproj" />
    <ProjectReference Include="..\Admin.Data408\Admin.Data408.csproj" />
    <ProjectReference Include="..\Portal.Service\Portal.Service.csproj" />
    <ProjectReference Include="..\Security.Shared365\Security.Shared365.csproj" />
    <ProjectReference Include="..\Security.Models\Security.Models.csproj" />
    <ProjectReference Include="..\Common.Validators50\Common.Validators50.csproj" />
    <ProjectReference Include="..\Integration.Handlers244\Integration.Handlers244.csproj" />
    <ProjectReference Include="..\Scheduling.Processors\Scheduling.Processors.csproj" />
  </ItemGroup>
</Project>
