<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Notifications.Api144</RootNamespace>
    <AssemblyName>Notifications.Api144</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Validators\Admin.Validators.csproj" />
    <ProjectReference Include="..\Portal.Service378\Portal.Service378.csproj" />
    <ProjectReference Include="..\Billing.Mappers198\Billing.Mappers198.csproj" />
    <ProjectReference Include="..\Billing.Mappers225\Billing.Mappers225.csproj" />
    <ProjectReference Include="..\BatchJobs.Web\BatchJobs.Web.csproj" />
    <ProjectReference Include="..\Security.Service\Security.Service.csproj" />
    <ProjectReference Include="..\Integration.Processors248\Integration.Processors248.csproj" />
    <ProjectReference Include="..\Auth.Data135\Auth.Data135.csproj" />
    <ProjectReference Include="..\Documents.Shared\Documents.Shared.csproj" />
    <ProjectReference Include="..\Scheduling.Processors80\Scheduling.Processors80.csproj" />
    <ProjectReference Include="..\Portal.Handlers26\Portal.Handlers26.csproj" />
    <ProjectReference Include="..\Import.Processors\Import.Processors.csproj" />
    <ProjectReference Include="..\Workflow.Service\Workflow.Service.csproj" />
    <ProjectReference Include="..\Security.Shared448\Security.Shared448.csproj" />
    <ProjectReference Include="..\Auth.Processors411\Auth.Processors411.csproj" />
    <ProjectReference Include="..\Portal.Api352\Portal.Api352.csproj" />
  </ItemGroup>
</Project>
