<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Workflow.Client351</RootNamespace>
    <AssemblyName>Workflow.Client351</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Events5\Auth.Events5.csproj" />
    <ProjectReference Include="..\Auth.Models23\Auth.Models23.csproj" />
    <ProjectReference Include="..\BatchJobs.Validators\BatchJobs.Validators.csproj" />
    <ProjectReference Include="..\Auth.Validators\Auth.Validators.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Core\GalaxyWorks.Core.csproj" />
    <ProjectReference Include="..\Admin.Validators\Admin.Validators.csproj" />
    <ProjectReference Include="..\Workflow.Api433\Workflow.Api433.csproj" />
    <ProjectReference Include="..\Security.Tests223\Security.Tests223.csproj" />
    <ProjectReference Include="..\BatchJobs.Data\BatchJobs.Data.csproj" />
    <ProjectReference Include="..\Admin.Web154\Admin.Web154.csproj" />
    <ProjectReference Include="..\Auth.Mappers206\Auth.Mappers206.csproj" />
    <ProjectReference Include="..\Import.Client\Import.Client.csproj" />
    <ProjectReference Include="..\Security.Web230\Security.Web230.csproj" />
    <ProjectReference Include="..\Billing.Tests194\Billing.Tests194.csproj" />
    <ProjectReference Include="..\Import.Models\Import.Models.csproj" />
    <ProjectReference Include="..\Admin.Data\Admin.Data.csproj" />
    <ProjectReference Include="..\Admin.Service456\Admin.Service456.csproj" />
  </ItemGroup>
</Project>
