<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>GalaxyWorks.Api390</RootNamespace>
    <AssemblyName>GalaxyWorks.Api390</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Validators37\Admin.Validators37.csproj" />
    <ProjectReference Include="..\Scheduling.Events\Scheduling.Events.csproj" />
    <ProjectReference Include="..\Auth.Api116\Auth.Api116.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Contracts485\GalaxyWorks.Contracts485.csproj" />
    <ProjectReference Include="..\Common.Mappers190\Common.Mappers190.csproj" />
    <ProjectReference Include="..\Documents.Tests458\Documents.Tests458.csproj" />
    <ProjectReference Include="..\Documents.Core357\Documents.Core357.csproj" />
    <ProjectReference Include="..\Notifications.Service165\Notifications.Service165.csproj" />
    <ProjectReference Include="..\Documents.Api\Documents.Api.csproj" />
    <ProjectReference Include="..\Portal.Contracts170\Portal.Contracts170.csproj" />
    <ProjectReference Include="..\Security.Web376\Security.Web376.csproj" />
    <ProjectReference Include="..\Admin.Api255\Admin.Api255.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Tests\GalaxyWorks.Tests.csproj" />
    <ProjectReference Include="..\Portal.Core8\Portal.Core8.csproj" />
    <ProjectReference Include="..\Security.Models18\Security.Models18.csproj" />
    <ProjectReference Include="..\Common.Client\Common.Client.csproj" />
  </ItemGroup>
</Project>
