<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Documents.Processors300</RootNamespace>
    <AssemblyName>Documents.Processors300</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Contracts402\Auth.Contracts402.csproj" />
    <ProjectReference Include="..\Admin.Service339\Admin.Service339.csproj" />
    <ProjectReference Include="..\Auth.Processors319\Auth.Processors319.csproj" />
    <ProjectReference Include="..\Common.Tests350\Common.Tests350.csproj" />
    <ProjectReference Include="..\Notifications.Models\Notifications.Models.csproj" />
    <ProjectReference Include="..\Reporting.Processors\Reporting.Processors.csproj" />
    <ProjectReference Include="..\Reporting.Shared\Reporting.Shared.csproj" />
    <ProjectReference Include="..\Common.Events367\Common.Events367.csproj" />
    <ProjectReference Include="..\Admin.Api255\Admin.Api255.csproj" />
    <ProjectReference Include="..\Export.Events163\Export.Events163.csproj" />
    <ProjectReference Include="..\Imaging.Contracts473\Imaging.Contracts473.csproj" />
    <ProjectReference Include="..\Logging.Contracts373\Logging.Contracts373.csproj" />
    <ProjectReference Include="..\Security.Processors246\Security.Processors246.csproj" />
    <ProjectReference Include="..\Security.Service383\Security.Service383.csproj" />
    <ProjectReference Include="..\DataAccess.Shared189\DataAccess.Shared189.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Tests445\GalaxyWorks.Tests445.csproj" />
    <ProjectReference Include="..\DataAccess.Tests282\DataAccess.Tests282.csproj" />
    <ProjectReference Include="..\Billing.Data\Billing.Data.csproj" />
  </ItemGroup>
</Project>
