<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>Billing.Processors</RootNamespace>
    <AssemblyName>Billing.Processors</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Models\Admin.Models.csproj" />
    <ProjectReference Include="..\Admin.Core\Admin.Core.csproj" />
    <ProjectReference Include="..\Admin.Client177\Admin.Client177.csproj" />
    <ProjectReference Include="..\Documents.Shared\Documents.Shared.csproj" />
    <ProjectReference Include="..\Notifications.Web90\Notifications.Web90.csproj" />
    <ProjectReference Include="..\Auth.Client\Auth.Client.csproj" />
    <ProjectReference Include="..\Import.Models457\Import.Models457.csproj" />
    <ProjectReference Include="..\Logging.Contracts373\Logging.Contracts373.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Api390\GalaxyWorks.Api390.csproj" />
    <ProjectReference Include="..\Logging.Contracts\Logging.Contracts.csproj" />
    <ProjectReference Include="..\Security.Client137\Security.Client137.csproj" />
    <ProjectReference Include="..\BatchJobs.Core\BatchJobs.Core.csproj" />
    <ProjectReference Include="..\Common.Processors\Common.Processors.csproj" />
    <ProjectReference Include="..\Common.Tests350\Common.Tests350.csproj" />
    <ProjectReference Include="..\Imaging.Service\Imaging.Service.csproj" />
    <ProjectReference Include="..\Portal.Models413\Portal.Models413.csproj" />
    <ProjectReference Include="..\BatchJobs.Api\BatchJobs.Api.csproj" />
    <ProjectReference Include="..\Export.Processors361\Export.Processors361.csproj" />
  </ItemGroup>
</Project>
