<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Common.Validators50</RootNamespace>
    <AssemblyName>Common.Validators50</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Web46\Admin.Web46.csproj" />
    <ProjectReference Include="..\Logging.Service382\Logging.Service382.csproj" />
    <ProjectReference Include="..\Admin.Api\Admin.Api.csproj" />
    <ProjectReference Include="..\Utilities.Api\Utilities.Api.csproj" />
    <ProjectReference Include="..\Portal.Tests173\Portal.Tests173.csproj" />
    <ProjectReference Include="..\Admin.Handlers450\Admin.Handlers450.csproj" />
    <ProjectReference Include="..\Utilities.Processors91\Utilities.Processors91.csproj" />
    <ProjectReference Include="..\Auth.Client249\Auth.Client249.csproj" />
    <ProjectReference Include="..\Auth.Handlers\Auth.Handlers.csproj" />
    <ProjectReference Include="..\Scheduling.Events128\Scheduling.Events128.csproj" />
    <ProjectReference Include="..\Import.Client64\Import.Client64.csproj" />
    <ProjectReference Include="..\DataAccess.Processors\DataAccess.Processors.csproj" />
    <ProjectReference Include="..\Security.Validators217\Security.Validators217.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Handlers478\GalaxyWorks.Handlers478.csproj" />
    <ProjectReference Include="..\Import.Data193\Import.Data193.csproj" />
    <ProjectReference Include="..\Export.Api12\Export.Api12.csproj" />
  </ItemGroup>
</Project>
