<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Export.Client</RootNamespace>
    <AssemblyName>Export.Client</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Service247\Admin.Service247.csproj" />
    <ProjectReference Include="..\Auth.Data\Auth.Data.csproj" />
    <ProjectReference Include="..\Admin.Processors\Admin.Processors.csproj" />
    <ProjectReference Include="..\Admin.Validators336\Admin.Validators336.csproj" />
    <ProjectReference Include="..\Reporting.Client422\Reporting.Client422.csproj" />
    <ProjectReference Include="..\Utilities.Web\Utilities.Web.csproj" />
    <ProjectReference Include="..\Imaging.Tests328\Imaging.Tests328.csproj" />
    <ProjectReference Include="..\Documents.Web164\Documents.Web164.csproj" />
    <ProjectReference Include="..\Portal.Processors389\Portal.Processors389.csproj" />
    <ProjectReference Include="..\Import.Service429\Import.Service429.csproj" />
    <ProjectReference Include="..\Scheduling.Api\Scheduling.Api.csproj" />
    <ProjectReference Include="..\Common.Shared\Common.Shared.csproj" />
    <ProjectReference Include="..\Integration.Tests86\Integration.Tests86.csproj" />
    <ProjectReference Include="..\Integration.Events\Integration.Events.csproj" />
    <ProjectReference Include="..\Auth.Shared325\Auth.Shared325.csproj" />
    <ProjectReference Include="..\BatchJobs.Service\BatchJobs.Service.csproj" />
    <ProjectReference Include="..\Scheduling.Mappers442\Scheduling.Mappers442.csproj" />
    <ProjectReference Include="..\Portal.Processors52\Portal.Processors52.csproj" />
  </ItemGroup>
</Project>
