<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Imaging.Models459</RootNamespace>
    <AssemblyName>Imaging.Models459</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Models476\Admin.Models476.csproj" />
    <ProjectReference Include="..\Auth.Handlers\Auth.Handlers.csproj" />
    <ProjectReference Include="..\Scheduling.Mappers48\Scheduling.Mappers48.csproj" />
    <ProjectReference Include="..\Import.Models457\Import.Models457.csproj" />
    <ProjectReference Include="..\Admin.Models199\Admin.Models199.csproj" />
    <ProjectReference Include="..\Common.Service258\Common.Service258.csproj" />
    <ProjectReference Include="..\Portal.Api51\Portal.Api51.csproj" />
    <ProjectReference Include="..\Billing.Core\Billing.Core.csproj" />
    <ProjectReference Include="..\Import.Client\Import.Client.csproj" />
    <ProjectReference Include="..\Billing.Handlers101\Billing.Handlers101.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Processors\GalaxyWorks.Processors.csproj" />
    <ProjectReference Include="..\Documents.Shared452\Documents.Shared452.csproj" />
    <ProjectReference Include="..\Common.Core118\Common.Core118.csproj" />
    <ProjectReference Include="..\Admin.Validators37\Admin.Validators37.csproj" />
    <ProjectReference Include="..\Documents.Shared334\Documents.Shared334.csproj" />
    <ProjectReference Include="..\Auth.Mappers206\Auth.Mappers206.csproj" />
    <ProjectReference Include="..\Scheduling.Tests76\Scheduling.Tests76.csproj" />
  </ItemGroup>
</Project>
