<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Common.Shared297</RootNamespace>
    <AssemblyName>Common.Shared297</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Events\Auth.Events.csproj" />
    <ProjectReference Include="..\Auth.Processors319\Auth.Processors319.csproj" />
    <ProjectReference Include="..\Admin.Data\Admin.Data.csproj" />
    <ProjectReference Include="..\Imaging.Contracts473\Imaging.Contracts473.csproj" />
    <ProjectReference Include="..\Admin.Shared\Admin.Shared.csproj" />
    <ProjectReference Include="..\Imaging.Events416\Imaging.Events416.csproj" />
    <ProjectReference Include="..\Reporting.Core\Reporting.Core.csproj" />
    <ProjectReference Include="..\Import.Tests\Import.Tests.csproj" />
    <ProjectReference Include="..\Common.Models381\Common.Models381.csproj" />
    <ProjectReference Include="..\Imaging.Contracts\Imaging.Contracts.csproj" />
    <ProjectReference Include="..\Integration.Processors321\Integration.Processors321.csproj" />
    <ProjectReference Include="..\Auth.Shared\Auth.Shared.csproj" />
    <ProjectReference Include="..\Portal.Service489\Portal.Service489.csproj" />
    <ProjectReference Include="..\Integration.Processors71\Integration.Processors71.csproj" />
    <ProjectReference Include="..\Imaging.Models184\Imaging.Models184.csproj" />
    <ProjectReference Include="..\Admin.Models476\Admin.Models476.csproj" />
    <ProjectReference Include="..\Security.Service\Security.Service.csproj" />
    <ProjectReference Include="..\Reporting.Events188\Reporting.Events188.csproj" />
  </ItemGroup>
</Project>
