<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Logging.Service382</RootNamespace>
    <AssemblyName>Logging.Service382</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Client346\Admin.Client346.csproj" />
    <ProjectReference Include="..\Portal.Validators69\Portal.Validators69.csproj" />
    <ProjectReference Include="..\DataAccess.Processors\DataAccess.Processors.csproj" />
    <ProjectReference Include="..\Logging.Contracts373\Logging.Contracts373.csproj" />
    <ProjectReference Include="..\Notifications.Shared396\Notifications.Shared396.csproj" />
    <ProjectReference Include="..\Auth.Processors411\Auth.Processors411.csproj" />
    <ProjectReference Include="..\Documents.Shared\Documents.Shared.csproj" />
    <ProjectReference Include="..\Security.Contracts238\Security.Contracts238.csproj" />
    <ProjectReference Include="..\Import.Service265\Import.Service265.csproj" />
    <ProjectReference Include="..\Auth.Client271\Auth.Client271.csproj" />
    <ProjectReference Include="..\Export.Processors468\Export.Processors468.csproj" />
    <ProjectReference Include="..\Logging.Handlers455\Logging.Handlers455.csproj" />
    <ProjectReference Include="..\Scheduling.Processors80\Scheduling.Processors80.csproj" />
    <ProjectReference Include="..\Scheduling.Handlers63\Scheduling.Handlers63.csproj" />
    <ProjectReference Include="..\Import.Data193\Import.Data193.csproj" />
    <ProjectReference Include="..\Utilities.Shared\Utilities.Shared.csproj" />
  </ItemGroup>
</Project>
