<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>Logging.Validators</RootNamespace>
    <AssemblyName>Logging.Validators</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Service456\Admin.Service456.csproj" />
    <ProjectReference Include="..\Integration.Events\Integration.Events.csproj" />
    <ProjectReference Include="..\Documents.Tests\Documents.Tests.csproj" />
    <ProjectReference Include="..\Import.Service\Import.Service.csproj" />
    <ProjectReference Include="..\Reporting.Contracts371\Reporting.Contracts371.csproj" />
    <ProjectReference Include="..\Notifications.Core\Notifications.Core.csproj" />
    <ProjectReference Include="..\Documents.Data\Documents.Data.csproj" />
    <ProjectReference Include="..\DataAccess.Data\DataAccess.Data.csproj" />
    <ProjectReference Include="..\Admin.Service\Admin.Service.csproj" />
    <ProjectReference Include="..\Import.Api272\Import.Api272.csproj" />
    <ProjectReference Include="..\Logging.Events\Logging.Events.csproj" />
    <ProjectReference Include="..\Scheduling.Processors335\Scheduling.Processors335.csproj" />
    <ProjectReference Include="..\Integration.Contracts290\Integration.Contracts290.csproj" />
    <ProjectReference Include="..\Security.Api134\Security.Api134.csproj" />
    <ProjectReference Include="..\Admin.Models\Admin.Models.csproj" />
    <ProjectReference Include="..\Import.Contracts180\Import.Contracts180.csproj" />
  </ItemGroup>
</Project>
