<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Scheduling.Shared</RootNamespace>
    <AssemblyName>Scheduling.Shared</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Validators\Admin.Validators.csproj" />
    <ProjectReference Include="..\Auth.Processors319\Auth.Processors319.csproj" />
    <ProjectReference Include="..\Integration.Events\Integration.Events.csproj" />
    <ProjectReference Include="..\Import.Service429\Import.Service429.csproj" />
    <ProjectReference Include="..\Admin.Contracts\Admin.Contracts.csproj" />
    <ProjectReference Include="..\Common.Events\Common.Events.csproj" />
    <ProjectReference Include="..\Documents.Shared452\Documents.Shared452.csproj" />
    <ProjectReference Include="..\Portal.Web158\Portal.Web158.csproj" />
    <ProjectReference Include="..\Notifications.Data348\Notifications.Data348.csproj" />
    <ProjectReference Include="..\Import.Shared\Import.Shared.csproj" />
    <ProjectReference Include="..\Import.Service496\Import.Service496.csproj" />
    <ProjectReference Include="..\Common.Validators430\Common.Validators430.csproj" />
    <ProjectReference Include="..\Documents.Tests171\Documents.Tests171.csproj" />
    <ProjectReference Include="..\Common.Events280\Common.Events280.csproj" />
    <ProjectReference Include="..\Workflow.Client\Workflow.Client.csproj" />
    <ProjectReference Include="..\Auth.Contracts402\Auth.Contracts402.csproj" />
    <ProjectReference Include="..\Utilities.Models41\Utilities.Models41.csproj" />
  </ItemGroup>
</Project>
