<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Export.Client13</RootNamespace>
    <AssemblyName>Export.Client13</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Web4\Admin.Web4.csproj" />
    <ProjectReference Include="..\Admin.Handlers447\Admin.Handlers447.csproj" />
    <ProjectReference Include="..\Auth.Mappers208\Auth.Mappers208.csproj" />
    <ProjectReference Include="..\Security.Shared155\Security.Shared155.csproj" />
    <ProjectReference Include="..\Imaging.Service\Imaging.Service.csproj" />
    <ProjectReference Include="..\DataAccess.Shared486\DataAccess.Shared486.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Client\GalaxyWorks.Client.csproj" />
    <ProjectReference Include="..\DataAccess.Contracts\DataAccess.Contracts.csproj" />
    <ProjectReference Include="..\Auth.Client271\Auth.Client271.csproj" />
    <ProjectReference Include="..\Security.Shared\Security.Shared.csproj" />
    <ProjectReference Include="..\Imaging.Events416\Imaging.Events416.csproj" />
    <ProjectReference Include="..\Reporting.Events\Reporting.Events.csproj" />
    <ProjectReference Include="..\Integration.Validators\Integration.Validators.csproj" />
    <ProjectReference Include="..\Utilities.Data415\Utilities.Data415.csproj" />
    <ProjectReference Include="..\Admin.Core121\Admin.Core121.csproj" />
    <ProjectReference Include="..\Common.Models\Common.Models.csproj" />
    <ProjectReference Include="..\Imaging.Data\Imaging.Data.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Service293\GalaxyWorks.Service293.csproj" />
  </ItemGroup>
</Project>
