<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Logging.Mappers157</RootNamespace>
    <AssemblyName>Logging.Mappers157</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Web154\Admin.Web154.csproj" />
    <ProjectReference Include="..\Admin.Shared363\Admin.Shared363.csproj" />
    <ProjectReference Include="..\Export.Data6\Export.Data6.csproj" />
    <ProjectReference Include="..\BatchJobs.Web\BatchJobs.Web.csproj" />
    <ProjectReference Include="..\Workflow.Contracts\Workflow.Contracts.csproj" />
    <ProjectReference Include="..\Common.Web488\Common.Web488.csproj" />
    <ProjectReference Include="..\Integration.Service147\Integration.Service147.csproj" />
    <ProjectReference Include="..\Common.Mappers190\Common.Mappers190.csproj" />
    <ProjectReference Include="..\Integration.Tests\Integration.Tests.csproj" />
    <ProjectReference Include="..\Integration.Web\Integration.Web.csproj" />
    <ProjectReference Include="..\Scheduling.Web19\Scheduling.Web19.csproj" />
    <ProjectReference Include="..\Imaging.Tests328\Imaging.Tests328.csproj" />
    <ProjectReference Include="..\Notifications.Models\Notifications.Models.csproj" />
    <ProjectReference Include="..\Imaging.Client\Imaging.Client.csproj" />
    <ProjectReference Include="..\Logging.Contracts74\Logging.Contracts74.csproj" />
    <ProjectReference Include="..\Import.Models457\Import.Models457.csproj" />
    <ProjectReference Include="..\Workflow.Core\Workflow.Core.csproj" />
  </ItemGroup>
</Project>
