<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Billing.Processors103</RootNamespace>
    <AssemblyName>Billing.Processors103</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Client249\Auth.Client249.csproj" />
    <ProjectReference Include="..\Admin.Data408\Admin.Data408.csproj" />
    <ProjectReference Include="..\Admin.Data117\Admin.Data117.csproj" />
    <ProjectReference Include="..\Common.Api57\Common.Api57.csproj" />
    <ProjectReference Include="..\Notifications.Data406\Notifications.Data406.csproj" />
    <ProjectReference Include="..\Logging.Validators\Logging.Validators.csproj" />
    <ProjectReference Include="..\Security.Core243\Security.Core243.csproj" />
    <ProjectReference Include="..\Reporting.Contracts371\Reporting.Contracts371.csproj" />
    <ProjectReference Include="..\Documents.Web\Documents.Web.csproj" />
    <ProjectReference Include="..\Common.Core169\Common.Core169.csproj" />
    <ProjectReference Include="..\Reporting.Mappers\Reporting.Mappers.csproj" />
    <ProjectReference Include="..\Security.Contracts238\Security.Contracts238.csproj" />
    <ProjectReference Include="..\Import.Service15\Import.Service15.csproj" />
    <ProjectReference Include="..\Portal.Mappers\Portal.Mappers.csproj" />
    <ProjectReference Include="..\Notifications.Client\Notifications.Client.csproj" />
    <ProjectReference Include="..\Billing.Validators\Billing.Validators.csproj" />
    <ProjectReference Include="..\Integration.Tests45\Integration.Tests45.csproj" />
    <ProjectReference Include="..\Utilities.Mappers232\Utilities.Mappers232.csproj" />
  </ItemGroup>
</Project>
