<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>BatchJobs.Data176</RootNamespace>
    <AssemblyName>BatchJobs.Data176</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Handlers450\Admin.Handlers450.csproj" />
    <ProjectReference Include="..\Admin.Api\Admin.Api.csproj" />
    <ProjectReference Include="..\Admin.Validators240\Admin.Validators240.csproj" />
    <ProjectReference Include="..\Scheduling.Core218\Scheduling.Core218.csproj" />
    <ProjectReference Include="..\BatchJobs.Contracts399\BatchJobs.Contracts399.csproj" />
    <ProjectReference Include="..\Auth.Events5\Auth.Events5.csproj" />
    <ProjectReference Include="..\Imaging.Models184\Imaging.Models184.csproj" />
    <ProjectReference Include="..\Utilities.Web\Utilities.Web.csproj" />
    <ProjectReference Include="..\Admin.Data\Admin.Data.csproj" />
    <ProjectReference Include="..\BatchJobs.Client267\BatchJobs.Client267.csproj" />
    <ProjectReference Include="..\Notifications.Mappers110\Notifications.Mappers110.csproj" />
    <ProjectReference Include="..\Documents.Data484\Documents.Data484.csproj" />
    <ProjectReference Include="..\Import.Mappers\Import.Mappers.csproj" />
    <ProjectReference Include="..\Documents.Shared452\Documents.Shared452.csproj" />
    <ProjectReference Include="..\Logging.Models379\Logging.Models379.csproj" />
    <ProjectReference Include="..\Common.Client269\Common.Client269.csproj" />
    <ProjectReference Include="..\DataAccess.Client82\DataAccess.Client82.csproj" />
    <ProjectReference Include="..\Utilities.Core\Utilities.Core.csproj" />
  </ItemGroup>
</Project>
