<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Import.Service496</RootNamespace>
    <AssemblyName>Import.Service496</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Processors319\Auth.Processors319.csproj" />
    <ProjectReference Include="..\Admin.Contracts120\Admin.Contracts120.csproj" />
    <ProjectReference Include="..\Auth.Events78\Auth.Events78.csproj" />
    <ProjectReference Include="..\Documents.Service215\Documents.Service215.csproj" />
    <ProjectReference Include="..\BatchJobs.Events435\BatchJobs.Events435.csproj" />
    <ProjectReference Include="..\Portal.Web158\Portal.Web158.csproj" />
    <ProjectReference Include="..\Scheduling.Service211\Scheduling.Service211.csproj" />
    <ProjectReference Include="..\Export.Data150\Export.Data150.csproj" />
    <ProjectReference Include="..\Scheduling.Mappers48\Scheduling.Mappers48.csproj" />
    <ProjectReference Include="..\Integration.Validators\Integration.Validators.csproj" />
    <ProjectReference Include="..\Notifications.Models466\Notifications.Models466.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Core309\GalaxyWorks.Core309.csproj" />
    <ProjectReference Include="..\Imaging.Contracts473\Imaging.Contracts473.csproj" />
    <ProjectReference Include="..\Admin.Data117\Admin.Data117.csproj" />
    <ProjectReference Include="..\Scheduling.Data54\Scheduling.Data54.csproj" />
    <ProjectReference Include="..\Billing.Client182\Billing.Client182.csproj" />
    <ProjectReference Include="..\Auth.Service\Auth.Service.csproj" />
    <ProjectReference Include="..\DataAccess.Contracts\DataAccess.Contracts.csproj" />
  </ItemGroup>
</Project>
