<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
    <RootNamespace>Export.Processors468</RootNamespace>
    <AssemblyName>Export.Processors468</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Models236\Auth.Models236.csproj" />
    <ProjectReference Include="..\Export.Web210\Export.Web210.csproj" />
    <ProjectReference Include="..\Utilities.Service\Utilities.Service.csproj" />
    <ProjectReference Include="..\Workflow.Processors\Workflow.Processors.csproj" />
    <ProjectReference Include="..\BatchJobs.Processors410\BatchJobs.Processors410.csproj" />
    <ProjectReference Include="..\Logging.Processors\Logging.Processors.csproj" />
    <ProjectReference Include="..\BatchJobs.Handlers443\BatchJobs.Handlers443.csproj" />
    <ProjectReference Include="..\Common.Data21\Common.Data21.csproj" />
    <ProjectReference Include="..\Common.Events280\Common.Events280.csproj" />
    <ProjectReference Include="..\Billing.Processors103\Billing.Processors103.csproj" />
    <ProjectReference Include="..\Logging.Models436\Logging.Models436.csproj" />
    <ProjectReference Include="..\Imaging.Tests328\Imaging.Tests328.csproj" />
    <ProjectReference Include="..\Workflow.Client47\Workflow.Client47.csproj" />
    <ProjectReference Include="..\Documents.Mappers\Documents.Mappers.csproj" />
    <ProjectReference Include="..\Documents.Data492\Documents.Data492.csproj" />
    <ProjectReference Include="..\DataAccess.Processors\DataAccess.Processors.csproj" />
  </ItemGroup>
</Project>
