<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>Workflow.Mappers</RootNamespace>
    <AssemblyName>Workflow.Mappers</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Handlers447\Admin.Handlers447.csproj" />
    <ProjectReference Include="..\Admin.Data465\Admin.Data465.csproj" />
    <ProjectReference Include="..\Portal.Events139\Portal.Events139.csproj" />
    <ProjectReference Include="..\Portal.Web494\Portal.Web494.csproj" />
    <ProjectReference Include="..\Billing.Client73\Billing.Client73.csproj" />
    <ProjectReference Include="..\Workflow.Client\Workflow.Client.csproj" />
    <ProjectReference Include="..\Export.Service30\Export.Service30.csproj" />
    <ProjectReference Include="..\Billing.Processors\Billing.Processors.csproj" />
    <ProjectReference Include="..\Security.Client\Security.Client.csproj" />
    <ProjectReference Include="..\Import.Processors412\Import.Processors412.csproj" />
    <ProjectReference Include="..\Reporting.Processors326\Reporting.Processors326.csproj" />
    <ProjectReference Include="..\DataAccess.Web200\DataAccess.Web200.csproj" />
    <ProjectReference Include="..\Logging.Client405\Logging.Client405.csproj" />
    <ProjectReference Include="..\Import.Data\Import.Data.csproj" />
    <ProjectReference Include="..\Utilities.Processors91\Utilities.Processors91.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Tests445\GalaxyWorks.Tests445.csproj" />
    <ProjectReference Include="..\Scheduling.Processors80\Scheduling.Processors80.csproj" />
  </ItemGroup>
</Project>
