<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>Import.Service</RootNamespace>
    <AssemblyName>Import.Service</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Shared363\Admin.Shared363.csproj" />
    <ProjectReference Include="..\Auth.Models23\Auth.Models23.csproj" />
    <ProjectReference Include="..\Auth.Client38\Auth.Client38.csproj" />
    <ProjectReference Include="..\Notifications.Validators252\Notifications.Validators252.csproj" />
    <ProjectReference Include="..\Admin.Models199\Admin.Models199.csproj" />
    <ProjectReference Include="..\Import.Contracts296\Import.Contracts296.csproj" />
    <ProjectReference Include="..\Documents.Service471\Documents.Service471.csproj" />
    <ProjectReference Include="..\Workflow.Validators201\Workflow.Validators201.csproj" />
    <ProjectReference Include="..\Admin.Handlers450\Admin.Handlers450.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Models219\GalaxyWorks.Models219.csproj" />
    <ProjectReference Include="..\BatchJobs.Events435\BatchJobs.Events435.csproj" />
    <ProjectReference Include="..\BatchJobs.Mappers\BatchJobs.Mappers.csproj" />
    <ProjectReference Include="..\Admin.Web4\Admin.Web4.csproj" />
    <ProjectReference Include="..\Common.Processors142\Common.Processors142.csproj" />
    <ProjectReference Include="..\BatchJobs.Contracts\BatchJobs.Contracts.csproj" />
    <ProjectReference Include="..\Common.Client269\Common.Client269.csproj" />
    <ProjectReference Include="..\Imaging.Events303\Imaging.Events303.csproj" />
    <ProjectReference Include="..\Export.Tests\Export.Tests.csproj" />
  </ItemGroup>
</Project>
