<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>Notifications.Mappers</RootNamespace>
    <AssemblyName>Notifications.Mappers</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Service247\Admin.Service247.csproj" />
    <ProjectReference Include="..\Integration.Service\Integration.Service.csproj" />
    <ProjectReference Include="..\Imaging.Client261\Imaging.Client261.csproj" />
    <ProjectReference Include="..\Documents.Data490\Documents.Data490.csproj" />
    <ProjectReference Include="..\Admin.Data\Admin.Data.csproj" />
    <ProjectReference Include="..\Common.Processors\Common.Processors.csproj" />
    <ProjectReference Include="..\Portal.Contracts181\Portal.Contracts181.csproj" />
    <ProjectReference Include="..\Documents.Shared487\Documents.Shared487.csproj" />
    <ProjectReference Include="..\Portal.Service231\Portal.Service231.csproj" />
    <ProjectReference Include="..\Integration.Mappers242\Integration.Mappers242.csproj" />
    <ProjectReference Include="..\Import.Contracts180\Import.Contracts180.csproj" />
    <ProjectReference Include="..\Security.Validators217\Security.Validators217.csproj" />
    <ProjectReference Include="..\Auth.Data135\Auth.Data135.csproj" />
    <ProjectReference Include="..\Documents.Data492\Documents.Data492.csproj" />
    <ProjectReference Include="..\Reporting.Shared\Reporting.Shared.csproj" />
    <ProjectReference Include="..\Imaging.Mappers\Imaging.Mappers.csproj" />
  </ItemGroup>
</Project>
