<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Utilities.Web40</RootNamespace>
    <AssemblyName>Utilities.Web40</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Handlers450\Admin.Handlers450.csproj" />
    <ProjectReference Include="..\Admin.Models476\Admin.Models476.csproj" />
    <ProjectReference Include="..\Export.Models\Export.Models.csproj" />
    <ProjectReference Include="..\Security.Core\Security.Core.csproj" />
    <ProjectReference Include="..\Export.Events276\Export.Events276.csproj" />
    <ProjectReference Include="..\Logging.Mappers\Logging.Mappers.csproj" />
    <ProjectReference Include="..\DataAccess.Handlers482\DataAccess.Handlers482.csproj" />
    <ProjectReference Include="..\Security.Data\Security.Data.csproj" />
    <ProjectReference Include="..\Auth.Contracts395\Auth.Contracts395.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Processors\GalaxyWorks.Processors.csproj" />
    <ProjectReference Include="..\Utilities.Tests\Utilities.Tests.csproj" />
    <ProjectReference Include="..\Scheduling.Web\Scheduling.Web.csproj" />
    <ProjectReference Include="..\Logging.Handlers\Logging.Handlers.csproj" />
    <ProjectReference Include="..\Security.Processors\Security.Processors.csproj" />
    <ProjectReference Include="..\Scheduling.Web264\Scheduling.Web264.csproj" />
    <ProjectReference Include="..\Integration.Handlers244\Integration.Handlers244.csproj" />
    <ProjectReference Include="..\Integration.Validators369\Integration.Validators369.csproj" />
  </ItemGroup>
</Project>
