<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Common.Core118</RootNamespace>
    <AssemblyName>Common.Core118</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Models23\Auth.Models23.csproj" />
    <ProjectReference Include="..\Auth.Api143\Auth.Api143.csproj" />
    <ProjectReference Include="..\Auth.Handlers467\Auth.Handlers467.csproj" />
    <ProjectReference Include="..\Auth.Client\Auth.Client.csproj" />
    <ProjectReference Include="..\Integration.Shared83\Integration.Shared83.csproj" />
    <ProjectReference Include="..\Portal.Data266\Portal.Data266.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Service293\GalaxyWorks.Service293.csproj" />
    <ProjectReference Include="..\Scheduling.Mappers442\Scheduling.Mappers442.csproj" />
    <ProjectReference Include="..\Common.Data126\Common.Data126.csproj" />
    <ProjectReference Include="..\Imaging.Events\Imaging.Events.csproj" />
    <ProjectReference Include="..\Documents.Tests106\Documents.Tests106.csproj" />
    <ProjectReference Include="..\Notifications.Events42\Notifications.Events42.csproj" />
    <ProjectReference Include="..\Common.Mappers\Common.Mappers.csproj" />
    <ProjectReference Include="..\Export.Tests\Export.Tests.csproj" />
    <ProjectReference Include="..\Billing.Core191\Billing.Core191.csproj" />
    <ProjectReference Include="..\Billing.Client73\Billing.Client73.csproj" />
    <ProjectReference Include="..\Security.Contracts499\Security.Contracts499.csproj" />
    <ProjectReference Include="..\Portal.Events151\Portal.Events151.csproj" />
  </ItemGroup>
</Project>
