<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Reporting.Tests</RootNamespace>
    <AssemblyName>Reporting.Tests</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Handlers61\Admin.Handlers61.csproj" />
    <ProjectReference Include="..\Documents.Api156\Documents.Api156.csproj" />
    <ProjectReference Include="..\Reporting.Contracts371\Reporting.Contracts371.csproj" />
    <ProjectReference Include="..\Import.Client356\Import.Client356.csproj" />
    <ProjectReference Include="..\Security.Events288\Security.Events288.csproj" />
    <ProjectReference Include="..\BatchJobs.Processors\BatchJobs.Processors.csproj" />
    <ProjectReference Include="..\Common.Mappers343\Common.Mappers343.csproj" />
    <ProjectReference Include="..\BatchJobs.Tests270\BatchJobs.Tests270.csproj" />
    <ProjectReference Include="..\Scheduling.Events\Scheduling.Events.csproj" />
    <ProjectReference Include="..\Security.Client\Security.Client.csproj" />
    <ProjectReference Include="..\Reporting.Mappers\Reporting.Mappers.csproj" />
    <ProjectReference Include="..\Admin.Service339\Admin.Service339.csproj" />
    <ProjectReference Include="..\Scheduling.Events128\Scheduling.Events128.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data224\GalaxyWorks.Data224.csproj" />
    <ProjectReference Include="..\Utilities.Shared114\Utilities.Shared114.csproj" />
    <ProjectReference Include="..\BatchJobs.Api212\BatchJobs.Api212.csproj" />
  </ItemGroup>
</Project>
