<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>Logging.Events289</RootNamespace>
    <AssemblyName>Logging.Events289</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Data408\Admin.Data408.csproj" />
    <ProjectReference Include="..\Admin.Tests\Admin.Tests.csproj" />
    <ProjectReference Include="..\Portal.Service378\Portal.Service378.csproj" />
    <ProjectReference Include="..\Portal.Tests173\Portal.Tests173.csproj" />
    <ProjectReference Include="..\Common.Events367\Common.Events367.csproj" />
    <ProjectReference Include="..\Reporting.Events\Reporting.Events.csproj" />
    <ProjectReference Include="..\Admin.Data465\Admin.Data465.csproj" />
    <ProjectReference Include="..\Admin.Events235\Admin.Events235.csproj" />
    <ProjectReference Include="..\Reporting.Processors495\Reporting.Processors495.csproj" />
    <ProjectReference Include="..\Security.Validators\Security.Validators.csproj" />
    <ProjectReference Include="..\Scheduling.Tests76\Scheduling.Tests76.csproj" />
    <ProjectReference Include="..\Import.Mappers\Import.Mappers.csproj" />
    <ProjectReference Include="..\Import.Api179\Import.Api179.csproj" />
    <ProjectReference Include="..\Common.Data126\Common.Data126.csproj" />
    <ProjectReference Include="..\Security.Service\Security.Service.csproj" />
    <ProjectReference Include="..\Integration.Events301\Integration.Events301.csproj" />
    <ProjectReference Include="..\Admin.Validators431\Admin.Validators431.csproj" />
  </ItemGroup>
</Project>
