<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>Imaging.Models</RootNamespace>
    <AssemblyName>Imaging.Models</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Client346\Admin.Client346.csproj" />
    <ProjectReference Include="..\Admin.Processors\Admin.Processors.csproj" />
    <ProjectReference Include="..\Admin.Validators240\Admin.Validators240.csproj" />
    <ProjectReference Include="..\DataAccess.Core\DataAccess.Core.csproj" />
    <ProjectReference Include="..\Reporting.Contracts371\Reporting.Contracts371.csproj" />
    <ProjectReference Include="..\Notifications.Api144\Notifications.Api144.csproj" />
    <ProjectReference Include="..\Workflow.Models\Workflow.Models.csproj" />
    <ProjectReference Include="..\Notifications.Models277\Notifications.Models277.csproj" />
    <ProjectReference Include="..\Auth.Mappers\Auth.Mappers.csproj" />
    <ProjectReference Include="..\Notifications.Core\Notifications.Core.csproj" />
    <ProjectReference Include="..\Logging.Service160\Logging.Service160.csproj" />
    <ProjectReference Include="..\DataAccess.Contracts\DataAccess.Contracts.csproj" />
    <ProjectReference Include="..\Portal.Contracts170\Portal.Contracts170.csproj" />
    <ProjectReference Include="..\Logging.Api316\Logging.Api316.csproj" />
    <ProjectReference Include="..\Integration.Handlers\Integration.Handlers.csproj" />
    <ProjectReference Include="..\Scheduling.Tests214\Scheduling.Tests214.csproj" />
    <ProjectReference Include="..\Workflow.Contracts\Workflow.Contracts.csproj" />
    <ProjectReference Include="..\Imaging.Api\Imaging.Api.csproj" />
  </ItemGroup>
</Project>
