<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>DataAccess.Core</RootNamespace>
    <AssemblyName>DataAccess.Core</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Data117\Admin.Data117.csproj" />
    <ProjectReference Include="..\Export.Web479\Export.Web479.csproj" />
    <ProjectReference Include="..\BatchJobs.Processors500\BatchJobs.Processors500.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Events\GalaxyWorks.Events.csproj" />
    <ProjectReference Include="..\DataAccess.Events283\DataAccess.Events283.csproj" />
    <ProjectReference Include="..\Utilities.Core\Utilities.Core.csproj" />
    <ProjectReference Include="..\Common.Processors\Common.Processors.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Models\GalaxyWorks.Models.csproj" />
    <ProjectReference Include="..\Scheduling.Tests444\Scheduling.Tests444.csproj" />
    <ProjectReference Include="..\Security.Mappers313\Security.Mappers313.csproj" />
    <ProjectReference Include="..\Reporting.Client\Reporting.Client.csproj" />
    <ProjectReference Include="..\Documents.Service215\Documents.Service215.csproj" />
    <ProjectReference Include="..\Integration.Core\Integration.Core.csproj" />
    <ProjectReference Include="..\Scheduling.Handlers\Scheduling.Handlers.csproj" />
    <ProjectReference Include="..\Reporting.Web345\Reporting.Web345.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Events77\GalaxyWorks.Events77.csproj" />
  </ItemGroup>
</Project>
