<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Export.Processors111</RootNamespace>
    <AssemblyName>Export.Processors111</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Data\Auth.Data.csproj" />
    <ProjectReference Include="..\Admin.Handlers450\Admin.Handlers450.csproj" />
    <ProjectReference Include="..\Admin.Web\Admin.Web.csproj" />
    <ProjectReference Include="..\Notifications.Client257\Notifications.Client257.csproj" />
    <ProjectReference Include="..\Auth.Handlers467\Auth.Handlers467.csproj" />
    <ProjectReference Include="..\Common.Models381\Common.Models381.csproj" />
    <ProjectReference Include="..\Common.Api\Common.Api.csproj" />
    <ProjectReference Include="..\Export.Web229\Export.Web229.csproj" />
    <ProjectReference Include="..\Reporting.Handlers347\Reporting.Handlers347.csproj" />
    <ProjectReference Include="..\Admin.Validators431\Admin.Validators431.csproj" />
    <ProjectReference Include="..\Reporting.Api287\Reporting.Api287.csproj" />
    <ProjectReference Include="..\Security.Models284\Security.Models284.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Mappers318\GalaxyWorks.Mappers318.csproj" />
    <ProjectReference Include="..\Imaging.Tests\Imaging.Tests.csproj" />
    <ProjectReference Include="..\Import.Api314\Import.Api314.csproj" />
    <ProjectReference Include="..\Workflow.Mappers\Workflow.Mappers.csproj" />
    <ProjectReference Include="..\Notifications.Tests195\Notifications.Tests195.csproj" />
    <ProjectReference Include="..\Export.Core372\Export.Core372.csproj" />
  </ItemGroup>
</Project>
