<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>Reporting.Web</RootNamespace>
    <AssemblyName>Reporting.Web</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Validators336\Admin.Validators336.csproj" />
    <ProjectReference Include="..\Admin.Contracts\Admin.Contracts.csproj" />
    <ProjectReference Include="..\Auth.Client38\Auth.Client38.csproj" />
    <ProjectReference Include="..\Logging.Models379\Logging.Models379.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Core\GalaxyWorks.Core.csproj" />
    <ProjectReference Include="..\Integration.Service477\Integration.Service477.csproj" />
    <ProjectReference Include="..\Notifications.Data348\Notifications.Data348.csproj" />
    <ProjectReference Include="..\Reporting.Validators\Reporting.Validators.csproj" />
    <ProjectReference Include="..\Import.Handlers167\Import.Handlers167.csproj" />
    <ProjectReference Include="..\Notifications.Handlers470\Notifications.Handlers470.csproj" />
    <ProjectReference Include="..\Utilities.Processors\Utilities.Processors.csproj" />
    <ProjectReference Include="..\DataAccess.Tests282\DataAccess.Tests282.csproj" />
    <ProjectReference Include="..\Common.Validators\Common.Validators.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Events77\GalaxyWorks.Events77.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Tests\GalaxyWorks.Tests.csproj" />
    <ProjectReference Include="..\Security.Processors246\Security.Processors246.csproj" />
    <ProjectReference Include="..\Integration.Handlers244\Integration.Handlers244.csproj" />
    <ProjectReference Include="..\Admin.Events235\Admin.Events235.csproj" />
  </ItemGroup>
</Project>
