<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Export.Tests</RootNamespace>
    <AssemblyName>Export.Tests</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Client271\Auth.Client271.csproj" />
    <ProjectReference Include="..\Common.Data21\Common.Data21.csproj" />
    <ProjectReference Include="..\Scheduling.Client187\Scheduling.Client187.csproj" />
    <ProjectReference Include="..\Utilities.Handlers\Utilities.Handlers.csproj" />
    <ProjectReference Include="..\Export.Models\Export.Models.csproj" />
    <ProjectReference Include="..\Security.Api\Security.Api.csproj" />
    <ProjectReference Include="..\Workflow.Processors\Workflow.Processors.csproj" />
    <ProjectReference Include="..\Common.Mappers343\Common.Mappers343.csproj" />
    <ProjectReference Include="..\Admin.Web\Admin.Web.csproj" />
    <ProjectReference Include="..\Import.Tests\Import.Tests.csproj" />
    <ProjectReference Include="..\Imaging.Mappers93\Imaging.Mappers93.csproj" />
    <ProjectReference Include="..\Auth.Processors319\Auth.Processors319.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data453\GalaxyWorks.Data453.csproj" />
    <ProjectReference Include="..\Scheduling.Web60\Scheduling.Web60.csproj" />
    <ProjectReference Include="..\Documents.Service\Documents.Service.csproj" />
    <ProjectReference Include="..\Scheduling.Contracts\Scheduling.Contracts.csproj" />
  </ItemGroup>
</Project>
