<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>DataAccess.Api</RootNamespace>
    <AssemblyName>DataAccess.Api</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Data408\Admin.Data408.csproj" />
    <ProjectReference Include="..\Export.Validators152\Export.Validators152.csproj" />
    <ProjectReference Include="..\Common.Service\Common.Service.csproj" />
    <ProjectReference Include="..\Import.Service291\Import.Service291.csproj" />
    <ProjectReference Include="..\Auth.Shared325\Auth.Shared325.csproj" />
    <ProjectReference Include="..\Workflow.Client351\Workflow.Client351.csproj" />
    <ProjectReference Include="..\Admin.Web4\Admin.Web4.csproj" />
    <ProjectReference Include="..\Workflow.Api\Workflow.Api.csproj" />
    <ProjectReference Include="..\Imaging.Client261\Imaging.Client261.csproj" />
    <ProjectReference Include="..\DataAccess.Tests286\DataAccess.Tests286.csproj" />
    <ProjectReference Include="..\Integration.Data\Integration.Data.csproj" />
    <ProjectReference Include="..\Auth.Contracts395\Auth.Contracts395.csproj" />
    <ProjectReference Include="..\Portal.Service231\Portal.Service231.csproj" />
    <ProjectReference Include="..\Billing.Mappers\Billing.Mappers.csproj" />
    <ProjectReference Include="..\DataAccess.Api307\DataAccess.Api307.csproj" />
    <ProjectReference Include="..\Admin.Shared310\Admin.Shared310.csproj" />
  </ItemGroup>
</Project>
