<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Scheduling.Processors335</RootNamespace>
    <AssemblyName>Scheduling.Processors335</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Models199\Admin.Models199.csproj" />
    <ProjectReference Include="..\Common.Validators50\Common.Validators50.csproj" />
    <ProjectReference Include="..\Auth.Contracts402\Auth.Contracts402.csproj" />
    <ProjectReference Include="..\Common.Processors245\Common.Processors245.csproj" />
    <ProjectReference Include="..\Logging.Validators\Logging.Validators.csproj" />
    <ProjectReference Include="..\Import.Tests\Import.Tests.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data375\GalaxyWorks.Data375.csproj" />
    <ProjectReference Include="..\Scheduling.Processors397\Scheduling.Processors397.csproj" />
    <ProjectReference Include="..\Security.Models420\Security.Models420.csproj" />
    <ProjectReference Include="..\Security.Service383\Security.Service383.csproj" />
    <ProjectReference Include="..\Admin.Handlers61\Admin.Handlers61.csproj" />
    <ProjectReference Include="..\Security.Core\Security.Core.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Contracts392\GalaxyWorks.Contracts392.csproj" />
    <ProjectReference Include="..\Billing.Mappers198\Billing.Mappers198.csproj" />
    <ProjectReference Include="..\Common.Core169\Common.Core169.csproj" />
    <ProjectReference Include="..\Export.Data6\Export.Data6.csproj" />
  </ItemGroup>
</Project>
