<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Utilities.Contracts32</RootNamespace>
    <AssemblyName>Utilities.Contracts32</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Client\Admin.Client.csproj" />
    <ProjectReference Include="..\Export.Service\Export.Service.csproj" />
    <ProjectReference Include="..\Import.Contracts296\Import.Contracts296.csproj" />
    <ProjectReference Include="..\Scheduling.Contracts425\Scheduling.Contracts425.csproj" />
    <ProjectReference Include="..\Billing.Mappers198\Billing.Mappers198.csproj" />
    <ProjectReference Include="..\Export.Validators\Export.Validators.csproj" />
    <ProjectReference Include="..\Admin.Contracts120\Admin.Contracts120.csproj" />
    <ProjectReference Include="..\Import.Events493\Import.Events493.csproj" />
    <ProjectReference Include="..\Portal.Validators\Portal.Validators.csproj" />
    <ProjectReference Include="..\Billing.Core191\Billing.Core191.csproj" />
    <ProjectReference Include="..\Portal.Processors389\Portal.Processors389.csproj" />
    <ProjectReference Include="..\Import.Mappers\Import.Mappers.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Contracts392\GalaxyWorks.Contracts392.csproj" />
    <ProjectReference Include="..\Imaging.Service\Imaging.Service.csproj" />
    <ProjectReference Include="..\Notifications.Shared380\Notifications.Shared380.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data224\GalaxyWorks.Data224.csproj" />
  </ItemGroup>
</Project>
