<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>Import.Api272</RootNamespace>
    <AssemblyName>Import.Api272</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Client346\Admin.Client346.csproj" />
    <ProjectReference Include="..\Admin.Handlers\Admin.Handlers.csproj" />
    <ProjectReference Include="..\BatchJobs.Models304\BatchJobs.Models304.csproj" />
    <ProjectReference Include="..\Portal.Tests323\Portal.Tests323.csproj" />
    <ProjectReference Include="..\Security.Client137\Security.Client137.csproj" />
    <ProjectReference Include="..\BatchJobs.Service\BatchJobs.Service.csproj" />
    <ProjectReference Include="..\Export.Web479\Export.Web479.csproj" />
    <ProjectReference Include="..\Notifications.Validators\Notifications.Validators.csproj" />
    <ProjectReference Include="..\Portal.Web\Portal.Web.csproj" />
    <ProjectReference Include="..\BatchJobs.Client267\BatchJobs.Client267.csproj" />
    <ProjectReference Include="..\Common.Data126\Common.Data126.csproj" />
    <ProjectReference Include="..\Import.Tests\Import.Tests.csproj" />
    <ProjectReference Include="..\Notifications.Web308\Notifications.Web308.csproj" />
    <ProjectReference Include="..\Import.Contracts296\Import.Contracts296.csproj" />
    <ProjectReference Include="..\Workflow.Handlers\Workflow.Handlers.csproj" />
    <ProjectReference Include="..\Security.Validators\Security.Validators.csproj" />
    <ProjectReference Include="..\Export.Data150\Export.Data150.csproj" />
  </ItemGroup>
</Project>
