<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>DataAccess.Mappers</RootNamespace>
    <AssemblyName>DataAccess.Mappers</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Validators431\Admin.Validators431.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Contracts94\GalaxyWorks.Contracts94.csproj" />
    <ProjectReference Include="..\Admin.Core121\Admin.Core121.csproj" />
    <ProjectReference Include="..\DataAccess.Models\DataAccess.Models.csproj" />
    <ProjectReference Include="..\Common.Api57\Common.Api57.csproj" />
    <ProjectReference Include="..\Scheduling.Handlers\Scheduling.Handlers.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Models219\GalaxyWorks.Models219.csproj" />
    <ProjectReference Include="..\Admin.Data408\Admin.Data408.csproj" />
    <ProjectReference Include="..\Auth.Models23\Auth.Models23.csproj" />
    <ProjectReference Include="..\Logging.Processors\Logging.Processors.csproj" />
    <ProjectReference Include="..\DataAccess.Data36\DataAccess.Data36.csproj" />
    <ProjectReference Include="..\Imaging.Models184\Imaging.Models184.csproj" />
    <ProjectReference Include="..\Export.Tests62\Export.Tests62.csproj" />
    <ProjectReference Include="..\Documents.Processors\Documents.Processors.csproj" />
    <ProjectReference Include="..\Billing.Core34\Billing.Core34.csproj" />
    <ProjectReference Include="..\Imaging.Web\Imaging.Web.csproj" />
  </ItemGroup>
</Project>
