<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>BatchJobs.Tests270</RootNamespace>
    <AssemblyName>BatchJobs.Tests270</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Events235\Admin.Events235.csproj" />
    <ProjectReference Include="..\Imaging.Service\Imaging.Service.csproj" />
    <ProjectReference Include="..\Import.Contracts131\Import.Contracts131.csproj" />
    <ProjectReference Include="..\BatchJobs.Mappers362\BatchJobs.Mappers362.csproj" />
    <ProjectReference Include="..\Billing.Core34\Billing.Core34.csproj" />
    <ProjectReference Include="..\Common.Models381\Common.Models381.csproj" />
    <ProjectReference Include="..\Admin.Web\Admin.Web.csproj" />
    <ProjectReference Include="..\Billing.Client\Billing.Client.csproj" />
    <ProjectReference Include="..\Reporting.Web345\Reporting.Web345.csproj" />
    <ProjectReference Include="..\Utilities.Data415\Utilities.Data415.csproj" />
    <ProjectReference Include="..\Admin.Shared14\Admin.Shared14.csproj" />
    <ProjectReference Include="..\Integration.Handlers244\Integration.Handlers244.csproj" />
    <ProjectReference Include="..\Billing.Mappers124\Billing.Mappers124.csproj" />
    <ProjectReference Include="..\Utilities.Handlers\Utilities.Handlers.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Handlers84\GalaxyWorks.Handlers84.csproj" />
    <ProjectReference Include="..\Scheduling.Web221\Scheduling.Web221.csproj" />
  </ItemGroup>
</Project>
