<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>DataAccess.Client82</RootNamespace>
    <AssemblyName>DataAccess.Client82</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Data117\Admin.Data117.csproj" />
    <ProjectReference Include="..\Admin.Web46\Admin.Web46.csproj" />
    <ProjectReference Include="..\Import.Client356\Import.Client356.csproj" />
    <ProjectReference Include="..\Common.Api57\Common.Api57.csproj" />
    <ProjectReference Include="..\DataAccess.Contracts\DataAccess.Contracts.csproj" />
    <ProjectReference Include="..\Portal.Processors\Portal.Processors.csproj" />
    <ProjectReference Include="..\Common.Processors142\Common.Processors142.csproj" />
    <ProjectReference Include="..\Utilities.Models\Utilities.Models.csproj" />
    <ProjectReference Include="..\Admin.Data\Admin.Data.csproj" />
    <ProjectReference Include="..\Reporting.Events\Reporting.Events.csproj" />
    <ProjectReference Include="..\Admin.Shared363\Admin.Shared363.csproj" />
    <ProjectReference Include="..\Notifications.Web308\Notifications.Web308.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data375\GalaxyWorks.Data375.csproj" />
    <ProjectReference Include="..\Workflow.Service463\Workflow.Service463.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Contracts392\GalaxyWorks.Contracts392.csproj" />
    <ProjectReference Include="..\BatchJobs.Models329\BatchJobs.Models329.csproj" />
    <ProjectReference Include="..\Admin.Web154\Admin.Web154.csproj" />
  </ItemGroup>
</Project>
