<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Notifications.Service165</RootNamespace>
    <AssemblyName>Notifications.Service165</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Processors\Auth.Processors.csproj" />
    <ProjectReference Include="..\Notifications.Processors\Notifications.Processors.csproj" />
    <ProjectReference Include="..\Workflow.Api433\Workflow.Api433.csproj" />
    <ProjectReference Include="..\Common.Shared95\Common.Shared95.csproj" />
    <ProjectReference Include="..\Workflow.Processors\Workflow.Processors.csproj" />
    <ProjectReference Include="..\Reporting.Events483\Reporting.Events483.csproj" />
    <ProjectReference Include="..\Auth.Validators87\Auth.Validators87.csproj" />
    <ProjectReference Include="..\Billing.Validators174\Billing.Validators174.csproj" />
    <ProjectReference Include="..\Billing.Contracts\Billing.Contracts.csproj" />
    <ProjectReference Include="..\Import.Contracts\Import.Contracts.csproj" />
    <ProjectReference Include="..\Admin.Data117\Admin.Data117.csproj" />
    <ProjectReference Include="..\Admin.Service364\Admin.Service364.csproj" />
    <ProjectReference Include="..\Admin.Client346\Admin.Client346.csproj" />
    <ProjectReference Include="..\Auth.Handlers467\Auth.Handlers467.csproj" />
    <ProjectReference Include="..\Export.Events\Export.Events.csproj" />
    <ProjectReference Include="..\Export.Models262\Export.Models262.csproj" />
  </ItemGroup>
</Project>
