<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Logging.Client405</RootNamespace>
    <AssemblyName>Logging.Client405</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Handlers467\Auth.Handlers467.csproj" />
    <ProjectReference Include="..\Admin.Shared310\Admin.Shared310.csproj" />
    <ProjectReference Include="..\Admin.Validators336\Admin.Validators336.csproj" />
    <ProjectReference Include="..\Billing.Mappers225\Billing.Mappers225.csproj" />
    <ProjectReference Include="..\Documents.Validators102\Documents.Validators102.csproj" />
    <ProjectReference Include="..\Auth.Events78\Auth.Events78.csproj" />
    <ProjectReference Include="..\Common.Validators\Common.Validators.csproj" />
    <ProjectReference Include="..\Common.Core169\Common.Core169.csproj" />
    <ProjectReference Include="..\Security.Web\Security.Web.csproj" />
    <ProjectReference Include="..\BatchJobs.Models329\BatchJobs.Models329.csproj" />
    <ProjectReference Include="..\Auth.Handlers209\Auth.Handlers209.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Tests\GalaxyWorks.Tests.csproj" />
    <ProjectReference Include="..\Security.Processors246\Security.Processors246.csproj" />
    <ProjectReference Include="..\DataAccess.Validators88\DataAccess.Validators88.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data224\GalaxyWorks.Data224.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Tests445\GalaxyWorks.Tests445.csproj" />
    <ProjectReference Include="..\Admin.Data117\Admin.Data117.csproj" />
    <ProjectReference Include="..\Export.Web229\Export.Web229.csproj" />
  </ItemGroup>
</Project>
