<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Notifications.Api</RootNamespace>
    <AssemblyName>Notifications.Api</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Validators\Admin.Validators.csproj" />
    <ProjectReference Include="..\Security.Events\Security.Events.csproj" />
    <ProjectReference Include="..\Common.Core417\Common.Core417.csproj" />
    <ProjectReference Include="..\Security.Shared\Security.Shared.csproj" />
    <ProjectReference Include="..\Notifications.Events\Notifications.Events.csproj" />
    <ProjectReference Include="..\Security.Processors295\Security.Processors295.csproj" />
    <ProjectReference Include="..\Reporting.Web345\Reporting.Web345.csproj" />
    <ProjectReference Include="..\Logging.Validators359\Logging.Validators359.csproj" />
    <ProjectReference Include="..\Workflow.Events\Workflow.Events.csproj" />
    <ProjectReference Include="..\Logging.Data29\Logging.Data29.csproj" />
    <ProjectReference Include="..\Import.Client64\Import.Client64.csproj" />
    <ProjectReference Include="..\Admin.Models476\Admin.Models476.csproj" />
    <ProjectReference Include="..\Utilities.Web398\Utilities.Web398.csproj" />
    <ProjectReference Include="..\Export.Validators\Export.Validators.csproj" />
    <ProjectReference Include="..\Scheduling.Mappers442\Scheduling.Mappers442.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Api390\GalaxyWorks.Api390.csproj" />
  </ItemGroup>
</Project>
