<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Export.Api49</RootNamespace>
    <AssemblyName>Export.Api49</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Validators240\Admin.Validators240.csproj" />
    <ProjectReference Include="..\Admin.Data408\Admin.Data408.csproj" />
    <ProjectReference Include="..\Import.Models457\Import.Models457.csproj" />
    <ProjectReference Include="..\DataAccess.Api454\DataAccess.Api454.csproj" />
    <ProjectReference Include="..\Imaging.Shared338\Imaging.Shared338.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Models219\GalaxyWorks.Models219.csproj" />
    <ProjectReference Include="..\Import.Service291\Import.Service291.csproj" />
    <ProjectReference Include="..\Security.Processors\Security.Processors.csproj" />
    <ProjectReference Include="..\Admin.Shared363\Admin.Shared363.csproj" />
    <ProjectReference Include="..\Documents.Processors300\Documents.Processors300.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data153\GalaxyWorks.Data153.csproj" />
    <ProjectReference Include="..\Admin.Shared310\Admin.Shared310.csproj" />
    <ProjectReference Include="..\Admin.Models476\Admin.Models476.csproj" />
    <ProjectReference Include="..\Import.Data\Import.Data.csproj" />
    <ProjectReference Include="..\Documents.Data\Documents.Data.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Shared437\GalaxyWorks.Shared437.csproj" />
    <ProjectReference Include="..\Export.Web\Export.Web.csproj" />
  </ItemGroup>
</Project>
