<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Common.Mappers343</RootNamespace>
    <AssemblyName>Common.Mappers343</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Processors35\Admin.Processors35.csproj" />
    <ProjectReference Include="..\Admin.Models\Admin.Models.csproj" />
    <ProjectReference Include="..\Auth.Handlers209\Auth.Handlers209.csproj" />
    <ProjectReference Include="..\Notifications.Handlers\Notifications.Handlers.csproj" />
    <ProjectReference Include="..\Auth.Client271\Auth.Client271.csproj" />
    <ProjectReference Include="..\Utilities.Api66\Utilities.Api66.csproj" />
    <ProjectReference Include="..\Portal.Validators227\Portal.Validators227.csproj" />
    <ProjectReference Include="..\Portal.Events151\Portal.Events151.csproj" />
    <ProjectReference Include="..\DataAccess.Events283\DataAccess.Events283.csproj" />
    <ProjectReference Include="..\Common.Core417\Common.Core417.csproj" />
    <ProjectReference Include="..\Billing.Shared\Billing.Shared.csproj" />
    <ProjectReference Include="..\Billing.Client22\Billing.Client22.csproj" />
    <ProjectReference Include="..\Auth.Api\Auth.Api.csproj" />
    <ProjectReference Include="..\Billing.Api\Billing.Api.csproj" />
    <ProjectReference Include="..\Admin.Events306\Admin.Events306.csproj" />
    <ProjectReference Include="..\Common.Shared\Common.Shared.csproj" />
    <ProjectReference Include="..\DataAccess.Web\DataAccess.Web.csproj" />
    <ProjectReference Include="..\Common.Handlers\Common.Handlers.csproj" />
  </ItemGroup>
</Project>
