<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Export.Models262</RootNamespace>
    <AssemblyName>Export.Models262</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Processors35\Admin.Processors35.csproj" />
    <ProjectReference Include="..\Admin.Core\Admin.Core.csproj" />
    <ProjectReference Include="..\Auth.Shared\Auth.Shared.csproj" />
    <ProjectReference Include="..\Common.Events\Common.Events.csproj" />
    <ProjectReference Include="..\DataAccess.Validators88\DataAccess.Validators88.csproj" />
    <ProjectReference Include="..\Utilities.Service358\Utilities.Service358.csproj" />
    <ProjectReference Include="..\Portal.Web\Portal.Web.csproj" />
    <ProjectReference Include="..\Portal.Events\Portal.Events.csproj" />
    <ProjectReference Include="..\Workflow.Tests222\Workflow.Tests222.csproj" />
    <ProjectReference Include="..\Documents.Service\Documents.Service.csproj" />
    <ProjectReference Include="..\Logging.Mappers\Logging.Mappers.csproj" />
    <ProjectReference Include="..\Common.Data126\Common.Data126.csproj" />
    <ProjectReference Include="..\Documents.Api129\Documents.Api129.csproj" />
    <ProjectReference Include="..\Admin.Service456\Admin.Service456.csproj" />
    <ProjectReference Include="..\DataAccess.Handlers482\DataAccess.Handlers482.csproj" />
    <ProjectReference Include="..\Documents.Validators102\Documents.Validators102.csproj" />
    <ProjectReference Include="..\Utilities.Contracts24\Utilities.Contracts24.csproj" />
  </ItemGroup>
</Project>
