<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Notifications.Events42</RootNamespace>
    <AssemblyName>Notifications.Events42</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Handlers281\Auth.Handlers281.csproj" />
    <ProjectReference Include="..\Admin.Validators37\Admin.Validators37.csproj" />
    <ProjectReference Include="..\Workflow.Core\Workflow.Core.csproj" />
    <ProjectReference Include="..\Admin.Service364\Admin.Service364.csproj" />
    <ProjectReference Include="..\Scheduling.Web221\Scheduling.Web221.csproj" />
    <ProjectReference Include="..\Admin.Handlers61\Admin.Handlers61.csproj" />
    <ProjectReference Include="..\Integration.Service\Integration.Service.csproj" />
    <ProjectReference Include="..\Billing.Shared\Billing.Shared.csproj" />
    <ProjectReference Include="..\Notifications.Handlers\Notifications.Handlers.csproj" />
    <ProjectReference Include="..\Notifications.Client257\Notifications.Client257.csproj" />
    <ProjectReference Include="..\Scheduling.Web196\Scheduling.Web196.csproj" />
    <ProjectReference Include="..\Portal.Validators250\Portal.Validators250.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Events77\GalaxyWorks.Events77.csproj" />
    <ProjectReference Include="..\Portal.Processors\Portal.Processors.csproj" />
    <ProjectReference Include="..\Common.Processors245\Common.Processors245.csproj" />
    <ProjectReference Include="..\Scheduling.Models441\Scheduling.Models441.csproj" />
    <ProjectReference Include="..\Scheduling.Processors80\Scheduling.Processors80.csproj" />
  </ItemGroup>
</Project>
