<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Portal.Service</RootNamespace>
    <AssemblyName>Portal.Service</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Events5\Auth.Events5.csproj" />
    <ProjectReference Include="..\Admin.Shared14\Admin.Shared14.csproj" />
    <ProjectReference Include="..\Auth.Mappers206\Auth.Mappers206.csproj" />
    <ProjectReference Include="..\Integration.Service477\Integration.Service477.csproj" />
    <ProjectReference Include="..\Import.Client\Import.Client.csproj" />
    <ProjectReference Include="..\Portal.Client\Portal.Client.csproj" />
    <ProjectReference Include="..\Admin.Core\Admin.Core.csproj" />
    <ProjectReference Include="..\Imaging.Mappers\Imaging.Mappers.csproj" />
    <ProjectReference Include="..\Security.Models18\Security.Models18.csproj" />
    <ProjectReference Include="..\Integration.Validators369\Integration.Validators369.csproj" />
    <ProjectReference Include="..\Auth.Client249\Auth.Client249.csproj" />
    <ProjectReference Include="..\Workflow.Validators\Workflow.Validators.csproj" />
    <ProjectReference Include="..\Common.Shared\Common.Shared.csproj" />
    <ProjectReference Include="..\Documents.Core357\Documents.Core357.csproj" />
    <ProjectReference Include="..\Workflow.Client351\Workflow.Client351.csproj" />
    <ProjectReference Include="..\Security.Service383\Security.Service383.csproj" />
    <ProjectReference Include="..\Logging.Core159\Logging.Core159.csproj" />
    <ProjectReference Include="..\Logging.Contracts\Logging.Contracts.csproj" />
  </ItemGroup>
</Project>
