<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>GalaxyWorks.Client366</RootNamespace>
    <AssemblyName>GalaxyWorks.Client366</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Service339\Admin.Service339.csproj" />
    <ProjectReference Include="..\Common.Handlers\Common.Handlers.csproj" />
    <ProjectReference Include="..\Portal.Data266\Portal.Data266.csproj" />
    <ProjectReference Include="..\DataAccess.Client82\DataAccess.Client82.csproj" />
    <ProjectReference Include="..\Logging.Validators\Logging.Validators.csproj" />
    <ProjectReference Include="..\Reporting.Shared\Reporting.Shared.csproj" />
    <ProjectReference Include="..\Imaging.Shared322\Imaging.Shared322.csproj" />
    <ProjectReference Include="..\Security.Contracts499\Security.Contracts499.csproj" />
    <ProjectReference Include="..\DataAccess.Api98\DataAccess.Api98.csproj" />
    <ProjectReference Include="..\DataAccess.Events\DataAccess.Events.csproj" />
    <ProjectReference Include="..\Logging.Handlers\Logging.Handlers.csproj" />
    <ProjectReference Include="..\Import.Data\Import.Data.csproj" />
    <ProjectReference Include="..\Workflow.Client\Workflow.Client.csproj" />
    <ProjectReference Include="..\Auth.Validators\Auth.Validators.csproj" />
    <ProjectReference Include="..\Notifications.Api144\Notifications.Api144.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data96\GalaxyWorks.Data96.csproj" />
  </ItemGroup>
</Project>
