<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Notifications.Shared380</RootNamespace>
    <AssemblyName>Notifications.Shared380</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Mappers\Auth.Mappers.csproj" />
    <ProjectReference Include="..\Auth.Contracts395\Auth.Contracts395.csproj" />
    <ProjectReference Include="..\Admin.Validators37\Admin.Validators37.csproj" />
    <ProjectReference Include="..\Security.Contracts499\Security.Contracts499.csproj" />
    <ProjectReference Include="..\Imaging.Shared115\Imaging.Shared115.csproj" />
    <ProjectReference Include="..\Export.Processors\Export.Processors.csproj" />
    <ProjectReference Include="..\Common.Client\Common.Client.csproj" />
    <ProjectReference Include="..\Workflow.Api148\Workflow.Api148.csproj" />
    <ProjectReference Include="..\Security.Client349\Security.Client349.csproj" />
    <ProjectReference Include="..\Security.Shared448\Security.Shared448.csproj" />
    <ProjectReference Include="..\Billing.Mappers124\Billing.Mappers124.csproj" />
    <ProjectReference Include="..\Export.Models461\Export.Models461.csproj" />
    <ProjectReference Include="..\Admin.Data408\Admin.Data408.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data\GalaxyWorks.Data.csproj" />
    <ProjectReference Include="..\Scheduling.Client187\Scheduling.Client187.csproj" />
    <ProjectReference Include="..\Utilities.Api234\Utilities.Api234.csproj" />
    <ProjectReference Include="..\Scheduling.Shared\Scheduling.Shared.csproj" />
    <ProjectReference Include="..\Billing.Tests194\Billing.Tests194.csproj" />
  </ItemGroup>
</Project>
