<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Billing.Processors259</RootNamespace>
    <AssemblyName>Billing.Processors259</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Models\Auth.Models.csproj" />
    <ProjectReference Include="..\Auth.Data135\Auth.Data135.csproj" />
    <ProjectReference Include="..\Security.Api134\Security.Api134.csproj" />
    <ProjectReference Include="..\Scheduling.Mappers\Scheduling.Mappers.csproj" />
    <ProjectReference Include="..\Auth.Client249\Auth.Client249.csproj" />
    <ProjectReference Include="..\Documents.Tests171\Documents.Tests171.csproj" />
    <ProjectReference Include="..\Admin.Web154\Admin.Web154.csproj" />
    <ProjectReference Include="..\Reporting.Client146\Reporting.Client146.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Tests445\GalaxyWorks.Tests445.csproj" />
    <ProjectReference Include="..\DataAccess.Validators409\DataAccess.Validators409.csproj" />
    <ProjectReference Include="..\Utilities.Client\Utilities.Client.csproj" />
    <ProjectReference Include="..\Billing.Api\Billing.Api.csproj" />
    <ProjectReference Include="..\Documents.Service215\Documents.Service215.csproj" />
    <ProjectReference Include="..\BatchJobs.Api501\BatchJobs.Api501.csproj" />
    <ProjectReference Include="..\Portal.Validators69\Portal.Validators69.csproj" />
    <ProjectReference Include="..\Import.Service\Import.Service.csproj" />
    <ProjectReference Include="..\BatchJobs.Tests\BatchJobs.Tests.csproj" />
  </ItemGroup>
</Project>
