<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Integration.Service147</RootNamespace>
    <AssemblyName>Integration.Service147</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Shared363\Admin.Shared363.csproj" />
    <ProjectReference Include="..\Auth.Contracts402\Auth.Contracts402.csproj" />
    <ProjectReference Include="..\Auth.Contracts395\Auth.Contracts395.csproj" />
    <ProjectReference Include="..\Documents.Core\Documents.Core.csproj" />
    <ProjectReference Include="..\Portal.Events\Portal.Events.csproj" />
    <ProjectReference Include="..\Admin.Contracts\Admin.Contracts.csproj" />
    <ProjectReference Include="..\Notifications.Web308\Notifications.Web308.csproj" />
    <ProjectReference Include="..\DataAccess.Shared189\DataAccess.Shared189.csproj" />
    <ProjectReference Include="..\Portal.Models413\Portal.Models413.csproj" />
    <ProjectReference Include="..\Admin.Shared14\Admin.Shared14.csproj" />
    <ProjectReference Include="..\Workflow.Api\Workflow.Api.csproj" />
    <ProjectReference Include="..\Import.Client64\Import.Client64.csproj" />
    <ProjectReference Include="..\Workflow.Handlers\Workflow.Handlers.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Contracts392\GalaxyWorks.Contracts392.csproj" />
    <ProjectReference Include="..\Documents.Shared\Documents.Shared.csproj" />
    <ProjectReference Include="..\Auth.Handlers\Auth.Handlers.csproj" />
    <ProjectReference Include="..\Common.Api186\Common.Api186.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Service\GalaxyWorks.Service.csproj" />
  </ItemGroup>
</Project>
