<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>DataAccess.Service464</RootNamespace>
    <AssemblyName>DataAccess.Service464</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Validators431\Admin.Validators431.csproj" />
    <ProjectReference Include="..\Auth.Core140\Auth.Core140.csproj" />
    <ProjectReference Include="..\Auth.Mappers208\Auth.Mappers208.csproj" />
    <ProjectReference Include="..\Portal.Events139\Portal.Events139.csproj" />
    <ProjectReference Include="..\Portal.Api352\Portal.Api352.csproj" />
    <ProjectReference Include="..\Integration.Processors\Integration.Processors.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Contracts392\GalaxyWorks.Contracts392.csproj" />
    <ProjectReference Include="..\Portal.Processors52\Portal.Processors52.csproj" />
    <ProjectReference Include="..\Common.Shared\Common.Shared.csproj" />
    <ProjectReference Include="..\BatchJobs.Api501\BatchJobs.Api501.csproj" />
    <ProjectReference Include="..\Common.Data81\Common.Data81.csproj" />
    <ProjectReference Include="..\Reporting.Events\Reporting.Events.csproj" />
    <ProjectReference Include="..\Utilities.Tests\Utilities.Tests.csproj" />
    <ProjectReference Include="..\Workflow.Tests75\Workflow.Tests75.csproj" />
    <ProjectReference Include="..\Import.Service15\Import.Service15.csproj" />
    <ProjectReference Include="..\Export.Validators\Export.Validators.csproj" />
    <ProjectReference Include="..\Common.Core417\Common.Core417.csproj" />
    <ProjectReference Include="..\Import.Client\Import.Client.csproj" />
  </ItemGroup>
</Project>
