<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Scheduling.Shared39</RootNamespace>
    <AssemblyName>Scheduling.Shared39</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Web4\Admin.Web4.csproj" />
    <ProjectReference Include="..\Admin.Service456\Admin.Service456.csproj" />
    <ProjectReference Include="..\Auth.Contracts395\Auth.Contracts395.csproj" />
    <ProjectReference Include="..\Workflow.Contracts434\Workflow.Contracts434.csproj" />
    <ProjectReference Include="..\Integration.Processors248\Integration.Processors248.csproj" />
    <ProjectReference Include="..\Scheduling.Mappers442\Scheduling.Mappers442.csproj" />
    <ProjectReference Include="..\Security.Contracts238\Security.Contracts238.csproj" />
    <ProjectReference Include="..\Logging.Client405\Logging.Client405.csproj" />
    <ProjectReference Include="..\Scheduling.Core218\Scheduling.Core218.csproj" />
    <ProjectReference Include="..\Documents.Core357\Documents.Core357.csproj" />
    <ProjectReference Include="..\Export.Client13\Export.Client13.csproj" />
    <ProjectReference Include="..\Scheduling.Web60\Scheduling.Web60.csproj" />
    <ProjectReference Include="..\Portal.Tests\Portal.Tests.csproj" />
    <ProjectReference Include="..\Portal.Contracts181\Portal.Contracts181.csproj" />
    <ProjectReference Include="..\Scheduling.Mappers48\Scheduling.Mappers48.csproj" />
    <ProjectReference Include="..\Imaging.Client\Imaging.Client.csproj" />
    <ProjectReference Include="..\Common.Mappers190\Common.Mappers190.csproj" />
    <ProjectReference Include="..\Scheduling.Client187\Scheduling.Client187.csproj" />
  </ItemGroup>
</Project>
