<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Documents.Api156</RootNamespace>
    <AssemblyName>Documents.Api156</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Shared\Admin.Shared.csproj" />
    <ProjectReference Include="..\Admin.Validators\Admin.Validators.csproj" />
    <ProjectReference Include="..\Scheduling.Tests85\Scheduling.Tests85.csproj" />
    <ProjectReference Include="..\Admin.Validators240\Admin.Validators240.csproj" />
    <ProjectReference Include="..\Integration.Data175\Integration.Data175.csproj" />
    <ProjectReference Include="..\Import.Tests119\Import.Tests119.csproj" />
    <ProjectReference Include="..\Imaging.Web172\Imaging.Web172.csproj" />
    <ProjectReference Include="..\Common.Web488\Common.Web488.csproj" />
    <ProjectReference Include="..\Security.Mappers313\Security.Mappers313.csproj" />
    <ProjectReference Include="..\Export.Service205\Export.Service205.csproj" />
    <ProjectReference Include="..\Reporting.Processors326\Reporting.Processors326.csproj" />
    <ProjectReference Include="..\Workflow.Tests222\Workflow.Tests222.csproj" />
    <ProjectReference Include="..\Common.Shared95\Common.Shared95.csproj" />
    <ProjectReference Include="..\Utilities.Contracts32\Utilities.Contracts32.csproj" />
    <ProjectReference Include="..\DataAccess.Tests\DataAccess.Tests.csproj" />
    <ProjectReference Include="..\Portal.Service\Portal.Service.csproj" />
    <ProjectReference Include="..\Import.Mappers\Import.Mappers.csproj" />
  </ItemGroup>
</Project>
