<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Notifications.Validators252</RootNamespace>
    <AssemblyName>Notifications.Validators252</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Models\Admin.Models.csproj" />
    <ProjectReference Include="..\Admin.Contracts\Admin.Contracts.csproj" />
    <ProjectReference Include="..\Admin.Handlers450\Admin.Handlers450.csproj" />
    <ProjectReference Include="..\Security.Shared\Security.Shared.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data375\GalaxyWorks.Data375.csproj" />
    <ProjectReference Include="..\Scheduling.Contracts\Scheduling.Contracts.csproj" />
    <ProjectReference Include="..\Workflow.Client\Workflow.Client.csproj" />
    <ProjectReference Include="..\Reporting.Api\Reporting.Api.csproj" />
    <ProjectReference Include="..\Reporting.Events483\Reporting.Events483.csproj" />
    <ProjectReference Include="..\Utilities.Handlers268\Utilities.Handlers268.csproj" />
    <ProjectReference Include="..\Auth.Models23\Auth.Models23.csproj" />
    <ProjectReference Include="..\Reporting.Contracts371\Reporting.Contracts371.csproj" />
    <ProjectReference Include="..\DataAccess.Api307\DataAccess.Api307.csproj" />
    <ProjectReference Include="..\Notifications.Handlers\Notifications.Handlers.csproj" />
    <ProjectReference Include="..\Logging.Handlers141\Logging.Handlers141.csproj" />
    <ProjectReference Include="..\Common.Web\Common.Web.csproj" />
    <ProjectReference Include="..\DataAccess.Data36\DataAccess.Data36.csproj" />
    <ProjectReference Include="..\Integration.Service401\Integration.Service401.csproj" />
  </ItemGroup>
</Project>
