<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Reporting.Events220</RootNamespace>
    <AssemblyName>Reporting.Events220</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Shared310\Admin.Shared310.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data453\GalaxyWorks.Data453.csproj" />
    <ProjectReference Include="..\Billing.Tests194\Billing.Tests194.csproj" />
    <ProjectReference Include="..\Portal.Data\Portal.Data.csproj" />
    <ProjectReference Include="..\Documents.Tests171\Documents.Tests171.csproj" />
    <ProjectReference Include="..\BatchJobs.Processors410\BatchJobs.Processors410.csproj" />
    <ProjectReference Include="..\DataAccess.Contracts404\DataAccess.Contracts404.csproj" />
    <ProjectReference Include="..\Imaging.Client\Imaging.Client.csproj" />
    <ProjectReference Include="..\Imaging.Tests328\Imaging.Tests328.csproj" />
    <ProjectReference Include="..\Reporting.Shared\Reporting.Shared.csproj" />
    <ProjectReference Include="..\Documents.Tests458\Documents.Tests458.csproj" />
    <ProjectReference Include="..\Notifications.Models466\Notifications.Models466.csproj" />
    <ProjectReference Include="..\Admin.Events\Admin.Events.csproj" />
    <ProjectReference Include="..\Export.Models461\Export.Models461.csproj" />
    <ProjectReference Include="..\Export.Web130\Export.Web130.csproj" />
    <ProjectReference Include="..\Admin.Web154\Admin.Web154.csproj" />
  </ItemGroup>
</Project>
