<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Logging.Core159</RootNamespace>
    <AssemblyName>Logging.Core159</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Tests10\Admin.Tests10.csproj" />
    <ProjectReference Include="..\Auth.Contracts395\Auth.Contracts395.csproj" />
    <ProjectReference Include="..\Admin.Shared363\Admin.Shared363.csproj" />
    <ProjectReference Include="..\Auth.Data135\Auth.Data135.csproj" />
    <ProjectReference Include="..\Notifications.Mappers110\Notifications.Mappers110.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data375\GalaxyWorks.Data375.csproj" />
    <ProjectReference Include="..\Scheduling.Mappers48\Scheduling.Mappers48.csproj" />
    <ProjectReference Include="..\Notifications.Api144\Notifications.Api144.csproj" />
    <ProjectReference Include="..\Imaging.Api\Imaging.Api.csproj" />
    <ProjectReference Include="..\Utilities.Shared\Utilities.Shared.csproj" />
    <ProjectReference Include="..\Notifications.Service\Notifications.Service.csproj" />
    <ProjectReference Include="..\Notifications.Shared380\Notifications.Shared380.csproj" />
    <ProjectReference Include="..\Common.Validators430\Common.Validators430.csproj" />
    <ProjectReference Include="..\Utilities.Web\Utilities.Web.csproj" />
    <ProjectReference Include="..\Portal.Api\Portal.Api.csproj" />
    <ProjectReference Include="..\Common.Data81\Common.Data81.csproj" />
    <ProjectReference Include="..\Workflow.Web\Workflow.Web.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Api390\GalaxyWorks.Api390.csproj" />
  </ItemGroup>
</Project>
