<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Import.Service15</RootNamespace>
    <AssemblyName>Import.Service15</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Shared363\Admin.Shared363.csproj" />
    <ProjectReference Include="..\Auth.Tests498\Auth.Tests498.csproj" />
    <ProjectReference Include="..\Utilities.Mappers\Utilities.Mappers.csproj" />
    <ProjectReference Include="..\Common.Service\Common.Service.csproj" />
    <ProjectReference Include="..\Documents.Data484\Documents.Data484.csproj" />
    <ProjectReference Include="..\Admin.Service364\Admin.Service364.csproj" />
    <ProjectReference Include="..\Billing.Api\Billing.Api.csproj" />
    <ProjectReference Include="..\Security.Web230\Security.Web230.csproj" />
    <ProjectReference Include="..\Import.Client7\Import.Client7.csproj" />
    <ProjectReference Include="..\Auth.Client38\Auth.Client38.csproj" />
    <ProjectReference Include="..\Export.Shared145\Export.Shared145.csproj" />
    <ProjectReference Include="..\Reporting.Shared394\Reporting.Shared394.csproj" />
    <ProjectReference Include="..\Workflow.Api\Workflow.Api.csproj" />
    <ProjectReference Include="..\Notifications.Processors20\Notifications.Processors20.csproj" />
    <ProjectReference Include="..\Import.Processors472\Import.Processors472.csproj" />
    <ProjectReference Include="..\Admin.Client346\Admin.Client346.csproj" />
  </ItemGroup>
</Project>
