<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>Import.Processors472</RootNamespace>
    <AssemblyName>Import.Processors472</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Api\Admin.Api.csproj" />
    <ProjectReference Include="..\Security.Client137\Security.Client137.csproj" />
    <ProjectReference Include="..\Import.Service496\Import.Service496.csproj" />
    <ProjectReference Include="..\DataAccess.Web200\DataAccess.Web200.csproj" />
    <ProjectReference Include="..\Export.Service\Export.Service.csproj" />
    <ProjectReference Include="..\DataAccess.Shared486\DataAccess.Shared486.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Data96\GalaxyWorks.Data96.csproj" />
    <ProjectReference Include="..\Security.Core274\Security.Core274.csproj" />
    <ProjectReference Include="..\Reporting.Api287\Reporting.Api287.csproj" />
    <ProjectReference Include="..\Export.Data344\Export.Data344.csproj" />
    <ProjectReference Include="..\Logging.Tests292\Logging.Tests292.csproj" />
    <ProjectReference Include="..\Logging.Validators359\Logging.Validators359.csproj" />
    <ProjectReference Include="..\Common.Mappers190\Common.Mappers190.csproj" />
    <ProjectReference Include="..\Utilities.Handlers268\Utilities.Handlers268.csproj" />
    <ProjectReference Include="..\Auth.Handlers281\Auth.Handlers281.csproj" />
    <ProjectReference Include="..\Notifications.Processors20\Notifications.Processors20.csproj" />
  </ItemGroup>
</Project>
