<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Export.Events276</RootNamespace>
    <AssemblyName>Export.Events276</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Models\Auth.Models.csproj" />
    <ProjectReference Include="..\Auth.Client38\Auth.Client38.csproj" />
    <ProjectReference Include="..\Notifications.Api144\Notifications.Api144.csproj" />
    <ProjectReference Include="..\Utilities.Web40\Utilities.Web40.csproj" />
    <ProjectReference Include="..\Security.Processors295\Security.Processors295.csproj" />
    <ProjectReference Include="..\Security.Core\Security.Core.csproj" />
    <ProjectReference Include="..\Scheduling.Web\Scheduling.Web.csproj" />
    <ProjectReference Include="..\Import.Client\Import.Client.csproj" />
    <ProjectReference Include="..\Notifications.Web308\Notifications.Web308.csproj" />
    <ProjectReference Include="..\Admin.Service247\Admin.Service247.csproj" />
    <ProjectReference Include="..\Admin.Shared14\Admin.Shared14.csproj" />
    <ProjectReference Include="..\Portal.Core8\Portal.Core8.csproj" />
    <ProjectReference Include="..\Scheduling.Shared39\Scheduling.Shared39.csproj" />
    <ProjectReference Include="..\Export.Validators152\Export.Validators152.csproj" />
    <ProjectReference Include="..\Utilities.Api234\Utilities.Api234.csproj" />
    <ProjectReference Include="..\Security.Web230\Security.Web230.csproj" />
    <ProjectReference Include="..\Billing.Processors103\Billing.Processors103.csproj" />
  </ItemGroup>
</Project>
