<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Import.Api</RootNamespace>
    <AssemblyName>Import.Api</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Core\Auth.Core.csproj" />
    <ProjectReference Include="..\Auth.Data\Auth.Data.csproj" />
    <ProjectReference Include="..\Admin.Models199\Admin.Models199.csproj" />
    <ProjectReference Include="..\Imaging.Mappers275\Imaging.Mappers275.csproj" />
    <ProjectReference Include="..\Scheduling.Api\Scheduling.Api.csproj" />
    <ProjectReference Include="..\Admin.Models476\Admin.Models476.csproj" />
    <ProjectReference Include="..\DataAccess.Core\DataAccess.Core.csproj" />
    <ProjectReference Include="..\Security.Core243\Security.Core243.csproj" />
    <ProjectReference Include="..\Common.Processors245\Common.Processors245.csproj" />
    <ProjectReference Include="..\Import.Processors412\Import.Processors412.csproj" />
    <ProjectReference Include="..\Scheduling.Processors\Scheduling.Processors.csproj" />
    <ProjectReference Include="..\Scheduling.Core273\Scheduling.Core273.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Shared437\GalaxyWorks.Shared437.csproj" />
    <ProjectReference Include="..\Export.Web130\Export.Web130.csproj" />
    <ProjectReference Include="..\BatchJobs.Core11\BatchJobs.Core11.csproj" />
    <ProjectReference Include="..\DataAccess.Tests282\DataAccess.Tests282.csproj" />
    <ProjectReference Include="..\Billing.Events\Billing.Events.csproj" />
    <ProjectReference Include="..\Logging.Api316\Logging.Api316.csproj" />
  </ItemGroup>
</Project>
