<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>GalaxyWorks.Validators</RootNamespace>
    <AssemblyName>GalaxyWorks.Validators</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Models23\Auth.Models23.csproj" />
    <ProjectReference Include="..\Auth.Mappers28\Auth.Mappers28.csproj" />
    <ProjectReference Include="..\Auth.Models\Auth.Models.csproj" />
    <ProjectReference Include="..\Admin.Service339\Admin.Service339.csproj" />
    <ProjectReference Include="..\Security.Processors\Security.Processors.csproj" />
    <ProjectReference Include="..\Admin.Tests10\Admin.Tests10.csproj" />
    <ProjectReference Include="..\BatchJobs.Tests\BatchJobs.Tests.csproj" />
    <ProjectReference Include="..\Auth.Api143\Auth.Api143.csproj" />
    <ProjectReference Include="..\Notifications.Tests\Notifications.Tests.csproj" />
    <ProjectReference Include="..\Reporting.Events220\Reporting.Events220.csproj" />
    <ProjectReference Include="..\Portal.Data266\Portal.Data266.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Handlers385\GalaxyWorks.Handlers385.csproj" />
    <ProjectReference Include="..\Logging.Events\Logging.Events.csproj" />
    <ProjectReference Include="..\DataAccess.Validators254\DataAccess.Validators254.csproj" />
    <ProjectReference Include="..\Portal.Validators227\Portal.Validators227.csproj" />
    <ProjectReference Include="..\Admin.Handlers447\Admin.Handlers447.csproj" />
    <ProjectReference Include="..\Notifications.Shared396\Notifications.Shared396.csproj" />
    <ProjectReference Include="..\Documents.Api129\Documents.Api129.csproj" />
  </ItemGroup>
</Project>
