<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Scheduling.Client187</RootNamespace>
    <AssemblyName>Scheduling.Client187</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Service\Admin.Service.csproj" />
    <ProjectReference Include="..\Admin.Handlers447\Admin.Handlers447.csproj" />
    <ProjectReference Include="..\Reporting.Tests226\Reporting.Tests226.csproj" />
    <ProjectReference Include="..\Export.Web229\Export.Web229.csproj" />
    <ProjectReference Include="..\Logging.Data\Logging.Data.csproj" />
    <ProjectReference Include="..\DataAccess.Models\DataAccess.Models.csproj" />
    <ProjectReference Include="..\Workflow.Handlers421\Workflow.Handlers421.csproj" />
    <ProjectReference Include="..\Logging.Shared315\Logging.Shared315.csproj" />
    <ProjectReference Include="..\Notifications.Client\Notifications.Client.csproj" />
    <ProjectReference Include="..\Scheduling.Web264\Scheduling.Web264.csproj" />
    <ProjectReference Include="..\DataAccess.Contracts404\DataAccess.Contracts404.csproj" />
    <ProjectReference Include="..\Billing.Api497\Billing.Api497.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Tests\GalaxyWorks.Tests.csproj" />
    <ProjectReference Include="..\Portal.Web\Portal.Web.csproj" />
    <ProjectReference Include="..\Imaging.Contracts473\Imaging.Contracts473.csproj" />
    <ProjectReference Include="..\Integration.Processors\Integration.Processors.csproj" />
    <ProjectReference Include="..\Security.Web\Security.Web.csproj" />
  </ItemGroup>
</Project>
