<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Auth.Validators</RootNamespace>
    <AssemblyName>Auth.Validators</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Validators37\Admin.Validators37.csproj" />
    <ProjectReference Include="..\Common.Shared\Common.Shared.csproj" />
    <ProjectReference Include="..\Notifications.Shared380\Notifications.Shared380.csproj" />
    <ProjectReference Include="..\Workflow.Mappers370\Workflow.Mappers370.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Events\GalaxyWorks.Events.csproj" />
    <ProjectReference Include="..\Utilities.Events\Utilities.Events.csproj" />
    <ProjectReference Include="..\Logging.Events289\Logging.Events289.csproj" />
    <ProjectReference Include="..\Common.Mappers190\Common.Mappers190.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Handlers84\GalaxyWorks.Handlers84.csproj" />
    <ProjectReference Include="..\Imaging.Validators\Imaging.Validators.csproj" />
    <ProjectReference Include="..\Common.Core169\Common.Core169.csproj" />
    <ProjectReference Include="..\Portal.Tests323\Portal.Tests323.csproj" />
    <ProjectReference Include="..\Common.Data21\Common.Data21.csproj" />
    <ProjectReference Include="..\Import.Contracts180\Import.Contracts180.csproj" />
    <ProjectReference Include="..\Reporting.Client146\Reporting.Client146.csproj" />
    <ProjectReference Include="..\DataAccess.Service464\DataAccess.Service464.csproj" />
  </ItemGroup>
</Project>
