<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Security.Service383</RootNamespace>
    <AssemblyName>Security.Service383</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Mappers\Admin.Mappers.csproj" />
    <ProjectReference Include="..\Auth.Processors319\Auth.Processors319.csproj" />
    <ProjectReference Include="..\Auth.Client\Auth.Client.csproj" />
    <ProjectReference Include="..\Export.Models262\Export.Models262.csproj" />
    <ProjectReference Include="..\Documents.Validators\Documents.Validators.csproj" />
    <ProjectReference Include="..\Export.Processors426\Export.Processors426.csproj" />
    <ProjectReference Include="..\Integration.Service401\Integration.Service401.csproj" />
    <ProjectReference Include="..\Workflow.Validators201\Workflow.Validators201.csproj" />
    <ProjectReference Include="..\Logging.Tests\Logging.Tests.csproj" />
    <ProjectReference Include="..\Common.Models381\Common.Models381.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Client366\GalaxyWorks.Client366.csproj" />
    <ProjectReference Include="..\Admin.Data\Admin.Data.csproj" />
    <ProjectReference Include="..\Notifications.Shared380\Notifications.Shared380.csproj" />
    <ProjectReference Include="..\Export.Core372\Export.Core372.csproj" />
    <ProjectReference Include="..\Security.Core243\Security.Core243.csproj" />
    <ProjectReference Include="..\Common.Service\Common.Service.csproj" />
    <ProjectReference Include="..\Documents.Contracts\Documents.Contracts.csproj" />
    <ProjectReference Include="..\Workflow.Api433\Workflow.Api433.csproj" />
  </ItemGroup>
</Project>
