<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Auth.Service</RootNamespace>
    <AssemblyName>Auth.Service</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Core121\Admin.Core121.csproj" />
    <ProjectReference Include="..\Auth.Core2\Auth.Core2.csproj" />
    <ProjectReference Include="..\Auth.Events5\Auth.Events5.csproj" />
    <ProjectReference Include="..\Reporting.Tests226\Reporting.Tests226.csproj" />
    <ProjectReference Include="..\Notifications.Shared396\Notifications.Shared396.csproj" />
    <ProjectReference Include="..\Logging.Service\Logging.Service.csproj" />
    <ProjectReference Include="..\Imaging.Shared338\Imaging.Shared338.csproj" />
    <ProjectReference Include="..\Portal.Api\Portal.Api.csproj" />
    <ProjectReference Include="..\Billing.Tests194\Billing.Tests194.csproj" />
    <ProjectReference Include="..\Scheduling.Core\Scheduling.Core.csproj" />
    <ProjectReference Include="..\Portal.Tests481\Portal.Tests481.csproj" />
    <ProjectReference Include="..\Integration.Contracts\Integration.Contracts.csproj" />
    <ProjectReference Include="..\Notifications.Client257\Notifications.Client257.csproj" />
    <ProjectReference Include="..\Logging.Tests\Logging.Tests.csproj" />
    <ProjectReference Include="..\Utilities.Data\Utilities.Data.csproj" />
    <ProjectReference Include="..\Billing.Web\Billing.Web.csproj" />
    <ProjectReference Include="..\Billing.Events\Billing.Events.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Api390\GalaxyWorks.Api390.csproj" />
  </ItemGroup>
</Project>
