<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Documents.Shared452</RootNamespace>
    <AssemblyName>Documents.Shared452</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Shared310\Admin.Shared310.csproj" />
    <ProjectReference Include="..\Import.Client\Import.Client.csproj" />
    <ProjectReference Include="..\Security.Handlers460\Security.Handlers460.csproj" />
    <ProjectReference Include="..\Logging.Models379\Logging.Models379.csproj" />
    <ProjectReference Include="..\Export.Api49\Export.Api49.csproj" />
    <ProjectReference Include="..\BatchJobs.Mappers362\BatchJobs.Mappers362.csproj" />
    <ProjectReference Include="..\Documents.Api129\Documents.Api129.csproj" />
    <ProjectReference Include="..\Admin.Contracts120\Admin.Contracts120.csproj" />
    <ProjectReference Include="..\Logging.Handlers285\Logging.Handlers285.csproj" />
    <ProjectReference Include="..\Security.Client349\Security.Client349.csproj" />
    <ProjectReference Include="..\Export.Validators152\Export.Validators152.csproj" />
    <ProjectReference Include="..\DataAccess.Validators\DataAccess.Validators.csproj" />
    <ProjectReference Include="..\Portal.Events151\Portal.Events151.csproj" />
    <ProjectReference Include="..\Export.Processors79\Export.Processors79.csproj" />
    <ProjectReference Include="..\Workflow.Tests27\Workflow.Tests27.csproj" />
    <ProjectReference Include="..\Billing.Client\Billing.Client.csproj" />
  </ItemGroup>
</Project>
