<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Import.Contracts180</RootNamespace>
    <AssemblyName>Import.Contracts180</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Handlers467\Auth.Handlers467.csproj" />
    <ProjectReference Include="..\Auth.Mappers28\Auth.Mappers28.csproj" />
    <ProjectReference Include="..\Auth.Core140\Auth.Core140.csproj" />
    <ProjectReference Include="..\Utilities.Web398\Utilities.Web398.csproj" />
    <ProjectReference Include="..\Utilities.Contracts32\Utilities.Contracts32.csproj" />
    <ProjectReference Include="..\Scheduling.Api185\Scheduling.Api185.csproj" />
    <ProjectReference Include="..\Admin.Web4\Admin.Web4.csproj" />
    <ProjectReference Include="..\Imaging.Validators\Imaging.Validators.csproj" />
    <ProjectReference Include="..\Admin.Data\Admin.Data.csproj" />
    <ProjectReference Include="..\Portal.Api\Portal.Api.csproj" />
    <ProjectReference Include="..\Utilities.Service\Utilities.Service.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Events\GalaxyWorks.Events.csproj" />
    <ProjectReference Include="..\Export.Processors361\Export.Processors361.csproj" />
    <ProjectReference Include="..\Portal.Api352\Portal.Api352.csproj" />
    <ProjectReference Include="..\Auth.Validators87\Auth.Validators87.csproj" />
    <ProjectReference Include="..\Portal.Contracts\Portal.Contracts.csproj" />
    <ProjectReference Include="..\Import.Service291\Import.Service291.csproj" />
    <ProjectReference Include="..\Logging.Events\Logging.Events.csproj" />
  </ItemGroup>
</Project>
