<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Notifications.Tests299</RootNamespace>
    <AssemblyName>Notifications.Tests299</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Api\Admin.Api.csproj" />
    <ProjectReference Include="..\Admin.Validators240\Admin.Validators240.csproj" />
    <ProjectReference Include="..\Documents.Data490\Documents.Data490.csproj" />
    <ProjectReference Include="..\Export.Service205\Export.Service205.csproj" />
    <ProjectReference Include="..\Logging.Models\Logging.Models.csproj" />
    <ProjectReference Include="..\Documents.Processors300\Documents.Processors300.csproj" />
    <ProjectReference Include="..\Billing.Client\Billing.Client.csproj" />
    <ProjectReference Include="..\Utilities.Api234\Utilities.Api234.csproj" />
    <ProjectReference Include="..\Common.Contracts\Common.Contracts.csproj" />
    <ProjectReference Include="..\Export.Web210\Export.Web210.csproj" />
    <ProjectReference Include="..\DataAccess.Tests\DataAccess.Tests.csproj" />
    <ProjectReference Include="..\Auth.Models236\Auth.Models236.csproj" />
    <ProjectReference Include="..\Scheduling.Validators\Scheduling.Validators.csproj" />
    <ProjectReference Include="..\Common.Validators50\Common.Validators50.csproj" />
    <ProjectReference Include="..\Logging.Events\Logging.Events.csproj" />
    <ProjectReference Include="..\Scheduling.Web221\Scheduling.Web221.csproj" />
    <ProjectReference Include="..\Scheduling.Api185\Scheduling.Api185.csproj" />
  </ItemGroup>
</Project>
