<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Integration.Models</RootNamespace>
    <AssemblyName>Integration.Models</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Client38\Auth.Client38.csproj" />
    <ProjectReference Include="..\Admin.Data117\Admin.Data117.csproj" />
    <ProjectReference Include="..\Admin.Validators37\Admin.Validators37.csproj" />
    <ProjectReference Include="..\Reporting.Events317\Reporting.Events317.csproj" />
    <ProjectReference Include="..\Integration.Mappers242\Integration.Mappers242.csproj" />
    <ProjectReference Include="..\Import.Shared\Import.Shared.csproj" />
    <ProjectReference Include="..\Documents.Service\Documents.Service.csproj" />
    <ProjectReference Include="..\Workflow.Web59\Workflow.Web59.csproj" />
    <ProjectReference Include="..\Admin.Data\Admin.Data.csproj" />
    <ProjectReference Include="..\Export.Validators152\Export.Validators152.csproj" />
    <ProjectReference Include="..\Common.Validators430\Common.Validators430.csproj" />
    <ProjectReference Include="..\Security.Handlers460\Security.Handlers460.csproj" />
    <ProjectReference Include="..\Scheduling.Validators\Scheduling.Validators.csproj" />
    <ProjectReference Include="..\Utilities.Validators\Utilities.Validators.csproj" />
    <ProjectReference Include="..\GalaxyWorks.Client\GalaxyWorks.Client.csproj" />
    <ProjectReference Include="..\Import.Events493\Import.Events493.csproj" />
    <ProjectReference Include="..\Integration.Processors\Integration.Processors.csproj" />
    <ProjectReference Include="..\Auth.Events\Auth.Events.csproj" />
  </ItemGroup>
</Project>
