<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Import.Tests119</RootNamespace>
    <AssemblyName>Import.Tests119</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.Data\Auth.Data.csproj" />
    <ProjectReference Include="..\Admin.Handlers61\Admin.Handlers61.csproj" />
    <ProjectReference Include="..\Admin.Handlers\Admin.Handlers.csproj" />
    <ProjectReference Include="..\DataAccess.Client\DataAccess.Client.csproj" />
    <ProjectReference Include="..\Security.Data278\Security.Data278.csproj" />
    <ProjectReference Include="..\Reporting.Events317\Reporting.Events317.csproj" />
    <ProjectReference Include="..\Workflow.Mappers\Workflow.Mappers.csproj" />
    <ProjectReference Include="..\Reporting.Client422\Reporting.Client422.csproj" />
    <ProjectReference Include="..\Scheduling.Handlers63\Scheduling.Handlers63.csproj" />
    <ProjectReference Include="..\Imaging.Shared322\Imaging.Shared322.csproj" />
    <ProjectReference Include="..\Documents.Handlers\Documents.Handlers.csproj" />
    <ProjectReference Include="..\Logging.Events289\Logging.Events289.csproj" />
    <ProjectReference Include="..\Logging.Models436\Logging.Models436.csproj" />
    <ProjectReference Include="..\Workflow.Web\Workflow.Web.csproj" />
    <ProjectReference Include="..\Billing.Client182\Billing.Client182.csproj" />
    <ProjectReference Include="..\Notifications.Validators\Notifications.Validators.csproj" />
    <ProjectReference Include="..\DataAccess.Api294\DataAccess.Api294.csproj" />
    <ProjectReference Include="..\Logging.Handlers368\Logging.Handlers368.csproj" />
  </ItemGroup>
</Project>
