<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>Export.Tests62</RootNamespace>
    <AssemblyName>Export.Tests62</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Client177\Admin.Client177.csproj" />
    <ProjectReference Include="..\Auth.Mappers178\Auth.Mappers178.csproj" />
    <ProjectReference Include="..\Admin.Web\Admin.Web.csproj" />
    <ProjectReference Include="..\BatchJobs.Events\BatchJobs.Events.csproj" />
    <ProjectReference Include="..\Common.Web438\Common.Web438.csproj" />
    <ProjectReference Include="..\DataAccess.Client82\DataAccess.Client82.csproj" />
    <ProjectReference Include="..\Utilities.Mappers\Utilities.Mappers.csproj" />
    <ProjectReference Include="..\BatchJobs.Processors\BatchJobs.Processors.csproj" />
    <ProjectReference Include="..\DataAccess.Shared486\DataAccess.Shared486.csproj" />
    <ProjectReference Include="..\Scheduling.Tests85\Scheduling.Tests85.csproj" />
    <ProjectReference Include="..\Notifications.Web\Notifications.Web.csproj" />
    <ProjectReference Include="..\Workflow.Models\Workflow.Models.csproj" />
    <ProjectReference Include="..\Admin.Validators431\Admin.Validators431.csproj" />
    <ProjectReference Include="..\Admin.Web46\Admin.Web46.csproj" />
    <ProjectReference Include="..\Export.Api\Export.Api.csproj" />
    <ProjectReference Include="..\Portal.Tests323\Portal.Tests323.csproj" />
    <ProjectReference Include="..\Notifications.Tests299\Notifications.Tests299.csproj" />
    <ProjectReference Include="..\DataAccess.Tests\DataAccess.Tests.csproj" />
  </ItemGroup>
</Project>
