<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <RootNamespace>Integration.Client</RootNamespace>
    <AssemblyName>Integration.Client</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Admin.Handlers450\Admin.Handlers450.csproj" />
    <ProjectReference Include="..\Auth.Api143\Auth.Api143.csproj" />
    <ProjectReference Include="..\Auth.Models236\Auth.Models236.csproj" />
    <ProjectReference Include="..\Admin.Client346\Admin.Client346.csproj" />
    <ProjectReference Include="..\Logging.Data29\Logging.Data29.csproj" />
    <ProjectReference Include="..\Admin.Data\Admin.Data.csproj" />
    <ProjectReference Include="..\DataAccess.Mappers\DataAccess.Mappers.csproj" />
    <ProjectReference Include="..\DataAccess.Api\DataAccess.Api.csproj" />
    <ProjectReference Include="..\Imaging.Client331\Imaging.Client331.csproj" />
    <ProjectReference Include="..\Auth.Api116\Auth.Api116.csproj" />
    <ProjectReference Include="..\Scheduling.Service211\Scheduling.Service211.csproj" />
    <ProjectReference Include="..\Notifications.Models\Notifications.Models.csproj" />
    <ProjectReference Include="..\Workflow.Shared\Workflow.Shared.csproj" />
    <ProjectReference Include="..\Documents.Service\Documents.Service.csproj" />
    <ProjectReference Include="..\Common.Api\Common.Api.csproj" />
    <ProjectReference Include="..\Export.Core168\Export.Core168.csproj" />
    <ProjectReference Include="..\DataAccess.Data36\DataAccess.Data36.csproj" />
  </ItemGroup>
</Project>
